-- 供应商（supplier）的 CRUD 查询。由 fries-gen 生成。
-- Code generated by fries-gen. DO NOT EDIT.

-- name: ListSuppliers :many
SELECT * FROM suppliers
WHERE tenant_id = sqlc.arg('tenant_id')
  AND deleted_at IS NULL
  AND (sqlc.narg('keyword')::varchar IS NULL OR name ILIKE sqlc.narg('keyword'))
  AND (sqlc.narg('status')::varchar IS NULL OR status = sqlc.narg('status'))
  AND (sqlc.narg('started_at')::date IS NULL OR started_at = sqlc.narg('started_at'))
ORDER BY created_at DESC
LIMIT sqlc.arg('limit') OFFSET sqlc.arg('offset');

-- name: CountSuppliers :one
SELECT count(*) FROM suppliers
WHERE tenant_id = sqlc.arg('tenant_id')
  AND deleted_at IS NULL
  AND (sqlc.narg('keyword')::varchar IS NULL OR name ILIKE sqlc.narg('keyword'))
  AND (sqlc.narg('status')::varchar IS NULL OR status = sqlc.narg('status'))
  AND (sqlc.narg('started_at')::date IS NULL OR started_at = sqlc.narg('started_at'));

-- name: GetSupplier :one
SELECT * FROM suppliers
WHERE tenant_id = sqlc.arg('tenant_id') AND id = sqlc.arg('id') AND deleted_at IS NULL;

-- name: CreateSupplier :one
INSERT INTO suppliers (tenant_id, id, name, status, credit, started_at, remark, created_by)
VALUES (sqlc.arg('tenant_id'), sqlc.arg('id'), sqlc.arg('name'), sqlc.narg('status'), sqlc.narg('credit'), sqlc.narg('started_at'), sqlc.narg('remark'), sqlc.narg('created_by'))
RETURNING *;

-- name: UpdateSupplier :one
UPDATE suppliers
SET name = sqlc.arg('name'),
    status = sqlc.narg('status'),
    credit = sqlc.narg('credit'),
    started_at = sqlc.narg('started_at'),
    remark = sqlc.narg('remark'),
    version = version + 1
WHERE tenant_id = sqlc.arg('tenant_id')
  AND id = sqlc.arg('id')
  AND version = sqlc.arg('version')
  AND deleted_at IS NULL
RETURNING *;

-- name: SoftDeleteSupplier :execrows
UPDATE suppliers
SET deleted_at = now(), version = version + 1
WHERE tenant_id = sqlc.arg('tenant_id')
  AND id = sqlc.arg('id')
  AND version = sqlc.arg('version')
  AND deleted_at IS NULL;
