// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

package supplier

import (
	"net/http"

	"github.com/ramoncjs3/fries/internal/errs"
)

// 模块专属错误码。前缀是模块 key（DECISIONS.md §4.5）。
var (
	// 唯一索引 uk_suppliers_name 冲突时用。
	ErrNameTaken = errs.Define("supplier.name_taken", http.StatusConflict,
		"供应商名称已被占用")
)
