// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

// Package supplier 是供应商模块的业务层。handler 只调这里，不直接碰 repo（红线 #6）。
package supplier

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/shopspring/decimal"

	"github.com/ramoncjs3/fries/internal/audit"
	"github.com/ramoncjs3/fries/internal/authz"
	"github.com/ramoncjs3/fries/internal/errs"
	"github.com/ramoncjs3/fries/internal/repo"
)

// Supplier 是供应商对外的视图。
type Supplier struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`       // 供应商名称
	Status    *string          `json:"status"`     // 状态
	Credit    *decimal.Decimal `json:"credit"`     // 授信额度
	StartedAt *time.Time       `json:"started_at"` // 合作起始日
	Remark    *string          `json:"remark"`     // 备注
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
	Version   int32            `json:"version"` // 乐观锁版本号，更新时原样传回
}

// Input 是新增/编辑供应商的入参。
type Input struct {
	Name      string           // 供应商名称
	Status    *string          // 状态
	Credit    *decimal.Decimal // 授信额度
	StartedAt *time.Time       // 合作起始日
	Remark    *string          // 备注
}

// ListFilter 是供应商列表的查询条件。
type ListFilter struct {
	Keyword   string     // 关键字，对可搜字段做 ILIKE
	Status    *string    // 按状态筛，nil 不筛
	StartedAt *time.Time // 按合作起始日筛，nil 不筛
	Page      int
	PageSize  int
}

// Service 是供应商服务。
type Service struct {
	store *repo.Store
}

// New 造供应商服务。
func New(store *repo.Store) *Service { return &Service{store: store} }

// tenant 取当前请求的租户句柄。每个对外方法第一行都该是它 ——
// 没有租户就报错，不是放行（MULTI-TENANCY.md §1.2 ②）。
func (s *Service) tenant(ctx context.Context) (*repo.TenantQueries, error) {
	id, err := authz.MustTenant(ctx)
	if err != nil {
		return nil, err
	}
	return s.store.ForTenant(id), nil
}

// List 分页查询供应商。
func (s *Service) List(ctx context.Context, f ListFilter) ([]Supplier, int64, error) {
	q, err := s.tenant(ctx)
	if err != nil {
		return nil, 0, err
	}
	keyword := repo.LikePattern(f.Keyword)
	rows, err := q.ListSuppliers(ctx, repo.ListSuppliersArgs{
		Limit:     int32(f.PageSize),
		Offset:    int32((f.Page - 1) * f.PageSize),
		Keyword:   keyword,
		Status:    f.Status,
		StartedAt: f.StartedAt,
	})
	if err != nil {
		return nil, 0, errs.Internal.Wrap(err)
	}
	total, err := q.CountSuppliers(ctx, repo.CountSuppliersArgs{
		Keyword:   keyword,
		Status:    f.Status,
		StartedAt: f.StartedAt,
	})
	if err != nil {
		return nil, 0, errs.Internal.Wrap(err)
	}
	out := make([]Supplier, 0, len(rows))
	for _, row := range rows {
		out = append(out, fromRow(row))
	}
	return out, total, nil
}

// Get 按 id 查一行（句柄已绑租户，改 URL 里的 id 只会查到 0 行）。
func (s *Service) Get(ctx context.Context, id uuid.UUID) (Supplier, error) {
	q, err := s.tenant(ctx)
	if err != nil {
		return Supplier{}, err
	}
	row, err := q.GetSupplier(ctx, id)
	if err != nil {
		return Supplier{}, notFoundOr(err)
	}
	return fromRow(row), nil
}

// Create 新增一条供应商。
func (s *Service) Create(ctx context.Context, in Input) (Supplier, error) {
	q, err := s.tenant(ctx)
	if err != nil {
		return Supplier{}, err
	}
	in.applyDefaults()
	id, err := uuid.NewV7()
	if err != nil {
		return Supplier{}, errs.Internal.Wrap(err)
	}
	row, err := q.CreateSupplier(ctx, repo.CreateSupplierArgs{
		ID:        id,
		Name:      in.Name,
		Status:    in.Status,
		Credit:    in.Credit,
		StartedAt: in.StartedAt,
		Remark:    in.Remark,
		CreatedBy: actorID(ctx),
	})
	if err != nil {
		return Supplier{}, uniqueOr(err)
	}
	audit.SetResourceID(ctx, row.ID)
	return fromRow(row), nil
}

// Update 编辑供应商。version 对不上返回 common.version_conflict（§2.4）。
func (s *Service) Update(ctx context.Context, id uuid.UUID, version int, in Input) (Supplier, error) {
	q, err := s.tenant(ctx)
	if err != nil {
		return Supplier{}, err
	}
	in.applyDefaults()
	row, err := q.UpdateSupplier(ctx, repo.UpdateSupplierArgs{
		ID:        id,
		Name:      in.Name,
		Status:    in.Status,
		Credit:    in.Credit,
		StartedAt: in.StartedAt,
		Remark:    in.Remark,
		Version:   int32(version),
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Supplier{}, conflictOrNotFound(ctx, q, id)
		}
		return Supplier{}, uniqueOr(err)
	}
	audit.SetResourceID(ctx, row.ID)
	return fromRow(row), nil
}

// Delete 软删除。version 对不上或已不在返回冲突/未找到。
func (s *Service) Delete(ctx context.Context, id uuid.UUID, version int) error {
	q, err := s.tenant(ctx)
	if err != nil {
		return err
	}
	rows, err := q.SoftDeleteSupplier(ctx, repo.SoftDeleteSupplierArgs{ID: id, Version: int32(version)})
	if err != nil {
		return errs.Internal.Wrap(err)
	}
	if rows == 0 {
		return conflictOrNotFound(ctx, q, id)
	}
	audit.SetResourceID(ctx, id)
	return nil
}

// fromRow 把 sqlc 行映射成对外视图。
func fromRow(row repo.Supplier) Supplier {
	return Supplier{
		ID:        row.ID,
		Name:      row.Name,
		Status:    row.Status,
		Credit:    row.Credit,
		StartedAt: row.StartedAt,
		Remark:    row.Remark,
		CreatedAt: row.CreatedAt,
		UpdatedAt: row.UpdatedAt,
		Version:   row.Version,
	}
}

// applyDefaults 给没传的可选字段补默认值。
//
// 为什么在这里补：列可空 + narg，入参 nil 时 INSERT 会显式写 NULL，绕过 DB 的 DEFAULT。
func (in *Input) applyDefaults() {
	if in.Status == nil {
		v := "active"
		in.Status = &v
	}
}

// uniqueOr 把唯一索引冲突翻成模块的错误码。
func uniqueOr(err error) error {
	if repo.IsUniqueViolation(err, "uk_suppliers_name") {
		return ErrNameTaken
	}
	return errs.Internal.Wrap(err)
}

// notFoundOr 把「查不到」翻成 NotFound，其余算内部错误。
func notFoundOr(err error) error {
	if errors.Is(err, pgx.ErrNoRows) {
		return errs.NotFound
	}
	return errs.Internal.Wrap(err)
}

// conflictOrNotFound 区分「版本过期」和「记录不存在」：改/删命中 0 行时再查一次。
func conflictOrNotFound(ctx context.Context, q *repo.TenantQueries, id uuid.UUID) error {
	if _, err := q.GetSupplier(ctx, id); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return errs.NotFound
		}
		return errs.Internal.Wrap(err)
	}
	return errs.VersionConflict
}

// actorID 取当前操作者 id（非用户主体返回 nil）。
func actorID(ctx context.Context) *uuid.UUID {
	p, ok := authz.PrincipalFrom(ctx)
	if !ok || !p.IsUser() {
		return nil
	}
	id := p.ID
	return &id
}
