// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE tenant_id = $1::uuid
  AND ($2::uuid IS NULL OR actor_id = $2)
  AND ($3::varchar IS NULL OR resource ILIKE $3)
  AND ($4::varchar IS NULL OR action ILIKE $4)
  AND ($5::timestamptz IS NULL OR occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR occurred_at < $6)
`

type CountAuditLogsParams struct {
	TenantID uuid.UUID
	ActorID  *uuid.UUID
	Resource *string
	Action   *string
	From     *time.Time
	To       *time.Time
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.TenantID,
		arg.ActorID,
		arg.Resource,
		arg.Action,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dropOldAuditPartitions = `-- name: DropOldAuditPartitions :one
SELECT drop_audit_partitions_before($1)::int AS dropped
`

// tenant-exempt: 同上。保留期到了整分区 DROP，保留天数也是平台级配置
func (q *Queries) DropOldAuditPartitions(ctx context.Context, cutoff time.Time) (int32, error) {
	row := q.db.QueryRow(ctx, dropOldAuditPartitions, cutoff)
	var dropped int32
	err := row.Scan(&dropped)
	return dropped, err
}

const ensureAuditPartition = `-- name: EnsureAuditPartition :one
SELECT ensure_audit_partition($1)::text AS partition_name
`

// tenant-exempt: 建分区是跨租户的后台任务 —— 分区按月切，不按租户切
func (q *Queries) EnsureAuditPartition(ctx context.Context, target time.Time) (string, error) {
	row := q.db.QueryRow(ctx, ensureAuditPartition, target)
	var partition_name string
	err := row.Scan(&partition_name)
	return partition_name, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec

INSERT INTO audit_logs (
    id, tenant_id, occurred_at, request_id,
    actor_type, actor_id, actor_name,
    resource, action, resource_id,
    method, path, ip, user_agent, http_status, duration_ms, detail
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16, $17
)
`

type InsertAuditLogParams struct {
	ID         uuid.UUID
	TenantID   *uuid.UUID
	OccurredAt time.Time
	RequestID  string
	ActorType  string
	ActorID    *uuid.UUID
	ActorName  string
	Resource   string
	Action     string
	ResourceID *uuid.UUID
	Method     string
	Path       string
	IP         *netip.Addr
	UserAgent  string
	HTTPStatus int32
	DurationMs int32
	Detail     []byte
}

// 审计日志（DECISIONS.md §6）。只有写入和查询 —— 改和删在 DB 层就被禁了。
//
// ⚠️ audit_logs 的 tenant_id **可空**（MULTI-TENANCY.md §7.1）：未认证请求
// （登录失败、健康检查、直接打接口）也要写审计，那些记录没有租户。
// NULL = 平台级 / 无租户事件，只有平台端看得到。
// 细节：公司代码有效、密码错误的登录失败要记在**那个租户名下**，客户才能看到
// 「有人在爆破我们的账号」；只有公司代码本身无效时才记 NULL。
// tenant-exempt: 写审计的中间件不是租户绑定的 —— 未认证请求也要写，那时 tenant_id 是 NULL。
//
//	列里带着 tenant_id，租户归属由调用方显式传，不靠 ForTenant 注入。
//
// prev_hash / hash 由触发器算，应用不传：应用能算就意味着应用能伪造。
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.TenantID,
		arg.OccurredAt,
		arg.RequestID,
		arg.ActorType,
		arg.ActorID,
		arg.ActorName,
		arg.Resource,
		arg.Action,
		arg.ResourceID,
		arg.Method,
		arg.Path,
		arg.IP,
		arg.UserAgent,
		arg.HTTPStatus,
		arg.DurationMs,
		arg.Detail,
	)
	return err
}

const listAuditChain = `-- name: ListAuditChain :many
SELECT id, occurred_at, tenant_id, actor_type, actor_id, resource, action, resource_id,
       http_status, detail, prev_hash, hash
FROM audit_logs
WHERE tenant_id = $1::uuid
ORDER BY occurred_at, id
`

type ListAuditChainRow struct {
	ID         uuid.UUID
	OccurredAt time.Time
	TenantID   *uuid.UUID
	ActorType  string
	ActorID    *uuid.UUID
	Resource   string
	Action     string
	ResourceID *uuid.UUID
	HTTPStatus int32
	Detail     []byte
	PrevHash   []byte
	Hash       []byte
}

// 按写入顺序取出某个租户的哈希链，用来验完整性。链现在**每租户各一条**（§2.4）。
func (q *Queries) ListAuditChain(ctx context.Context, tenantID uuid.UUID) ([]ListAuditChainRow, error) {
	rows, err := q.db.Query(ctx, listAuditChain, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditChainRow{}
	for rows.Next() {
		var i ListAuditChainRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Resource,
			&i.Action,
			&i.ResourceID,
			&i.HTTPStatus,
			&i.Detail,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, occurred_at, request_id, actor_type, actor_id, actor_name, resource, action, resource_id, method, path, ip, user_agent, http_status, duration_ms, detail, prev_hash, hash, tenant_id FROM audit_logs
WHERE tenant_id = $1::uuid
  AND ($2::uuid IS NULL OR actor_id = $2)
  AND ($3::varchar IS NULL OR resource ILIKE $3)
  AND ($4::varchar IS NULL OR action ILIKE $4)
  AND ($5::timestamptz IS NULL OR occurred_at >= $5)
  AND ($6::timestamptz IS NULL OR occurred_at < $6)
ORDER BY occurred_at DESC, id DESC
LIMIT $8 OFFSET $7
`

type ListAuditLogsParams struct {
	TenantID uuid.UUID
	ActorID  *uuid.UUID
	Resource *string
	Action   *string
	From     *time.Time
	To       *time.Time
	Offset   int32
	Limit    int32
}

// resource / action 传的是 ILIKE 模式（`%li%`），由 repo.LikePattern 拼 ——
// **别在这里拼 '%' || ... || '%'**，那样用户输入的 % 和 _ 就成了通配符。
//
// tenant_id = ? 是等值条件，NULL 的那批（平台级事件）自然落不进来 —— 这是想要的。
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.TenantID,
		arg.ActorID,
		arg.Resource,
		arg.Action,
		arg.From,
		arg.To,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.RequestID,
			&i.ActorType,
			&i.ActorID,
			&i.ActorName,
			&i.Resource,
			&i.Action,
			&i.ResourceID,
			&i.Method,
			&i.Path,
			&i.IP,
			&i.UserAgent,
			&i.HTTPStatus,
			&i.DurationMs,
			&i.Detail,
			&i.PrevHash,
			&i.Hash,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformAuditChain = `-- name: ListPlatformAuditChain :many
SELECT id, occurred_at, tenant_id, actor_type, actor_id, resource, action, resource_id,
       http_status, detail, prev_hash, hash
FROM audit_logs
WHERE tenant_id IS NULL
ORDER BY occurred_at, id
`

type ListPlatformAuditChainRow struct {
	ID         uuid.UUID
	OccurredAt time.Time
	TenantID   *uuid.UUID
	ActorType  string
	ActorID    *uuid.UUID
	Resource   string
	Action     string
	ResourceID *uuid.UUID
	HTTPStatus int32
	Detail     []byte
	PrevHash   []byte
	Hash       []byte
}

// tenant-exempt: 平台级事件（未认证请求）的那条链，tenant_id 就是 NULL ——
//
//	它不属于任何租户，按定义就带不了租户条件。只有平台管理端查得到。
//
// 单独一条查询而不是在 ListAuditChain 里 coalesce：
//  1. 那样 ListAuditChain 用不上 (tenant_id, occurred_at) 索引
//  2. 更要紧的是，coalesce 版本要传全零哨兵 UUID 才能取到平台链，
//     而 ForTenant 现在拒绝零值租户（零值只该来自 bug）。两件事分开各走各的路。
func (q *Queries) ListPlatformAuditChain(ctx context.Context) ([]ListPlatformAuditChainRow, error) {
	rows, err := q.db.Query(ctx, listPlatformAuditChain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformAuditChainRow{}
	for rows.Next() {
		var i ListPlatformAuditChainRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.TenantID,
			&i.ActorType,
			&i.ActorID,
			&i.Resource,
			&i.Action,
			&i.ResourceID,
			&i.HTTPStatus,
			&i.Detail,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
