// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (tenant_id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AssignUserRoleParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.TenantID, arg.UserID, arg.RoleID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE tenant_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (tenant_id, id, token_hash, user_id, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
RETURNING id, token_hash, user_id, ip, user_agent, expires_at, last_seen_at, revoked_at, created_at, tenant_id
`

type CreateSessionParams struct {
	TenantID  uuid.UUID
	ID        uuid.UUID
	TokenHash []byte
	UserID    uuid.UUID
	IP        *netip.Addr
	UserAgent string
	ExpiresAt time.Time
}

// ---------------------------------------------------------------- 会话
// sessions.tenant_id 看着像冗余（能从 users 推出来），但整套隔离都以「会话里的租户」
// 为唯一来源，所以它必须存在这里。两份真相会不会漂？不会 ——
// 复合外键 (tenant_id, user_id) → users (tenant_id, id) 让数据库保证它们永远一致（§10.2）。
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TenantID,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.IP,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.IP,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, id, username, display_name, email, phone,
                   password_hash, must_change_password, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9)
RETURNING id, username, display_name, email, password_hash, password_changed_at, must_change_password, status, failed_attempts, locked_until, last_login_at, created_at, updated_at, deleted_at, created_by, version, phone, department_id, tenant_id
`

type CreateUserParams struct {
	TenantID           uuid.UUID
	ID                 uuid.UUID
	Username           string
	DisplayName        string
	Email              *string
	Phone              *string
	PasswordHash       string
	MustChangePassword bool
	CreatedBy          *uuid.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.Phone,
		&i.DepartmentID,
		&i.TenantID,
	)
	return i, err
}

const deleteDeadSessions = `-- name: DeleteDeadSessions :execrows
DELETE FROM sessions
WHERE expires_at < now() - interval '7 days'
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '7 days')
`

// tenant-exempt: 清理过期会话的后台任务是跨租户的一次扫描，不属于任何租户。
//
//	它只按时间删已经死掉的行，读不到任何租户数据。
func (q *Queries) DeleteDeadSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeadSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT s.id, s.token_hash, s.user_id, s.ip, s.user_agent, s.expires_at, s.last_seen_at, s.revoked_at, s.created_at, s.tenant_id, u.id, u.username, u.display_name, u.email, u.password_hash, u.password_changed_at, u.must_change_password, u.status, u.failed_attempts, u.locked_until, u.last_login_at, u.created_at, u.updated_at, u.deleted_at, u.created_by, u.version, u.phone, u.department_id, u.tenant_id, t.status AS tenant_status
FROM sessions s
JOIN users u ON u.id = s.user_id AND u.tenant_id = s.tenant_id
JOIN tenants t ON t.id = s.tenant_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND u.deleted_at IS NULL
`

type GetLiveSessionRow struct {
	Session      Session
	User         User
	TenantStatus string
}

// tenant-exempt: 这就是「认证发生在租户上下文之前」的那一刻 —— 拿 cookie 里的 token
//
//	查这是谁，查出来的这一行才告诉我们 tenant_id。所以 uk_sessions_token 也保持
//	全平台唯一，没加 tenant_id（§2.2）。
//	⚠️ 返回的 session.tenant_id 是后续所有隔离的唯一来源，谁都别再从别处推。
//
// 顺带把租户状态一起取出来（§8.2）。**停用一个租户必须立刻生效** ——
// 只挡新登录的话，客户的人拿着已有 cookie 能一直用到过期，而界面上显示「已停用」。
// 在这里查而不是「停用时逐条吊销会话」：这样连绕过应用直接改库的停用也照样生效。
func (q *Queries) GetLiveSession(ctx context.Context, tokenHash []byte) (GetLiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getLiveSession, tokenHash)
	var i GetLiveSessionRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.TokenHash,
		&i.Session.UserID,
		&i.Session.IP,
		&i.Session.UserAgent,
		&i.Session.ExpiresAt,
		&i.Session.LastSeenAt,
		&i.Session.RevokedAt,
		&i.Session.CreatedAt,
		&i.Session.TenantID,
		&i.User.ID,
		&i.User.Username,
		&i.User.DisplayName,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.PasswordChangedAt,
		&i.User.MustChangePassword,
		&i.User.Status,
		&i.User.FailedAttempts,
		&i.User.LockedUntil,
		&i.User.LastLoginAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.User.CreatedBy,
		&i.User.Version,
		&i.User.Phone,
		&i.User.DepartmentID,
		&i.User.TenantID,
		&i.TenantStatus,
	)
	return i, err
}

const getRoleByKey = `-- name: GetRoleByKey :one

SELECT id, key, name, description, data_scope, builtin, status, created_at, updated_at, deleted_at, created_by, version, tenant_id FROM roles
WHERE tenant_id = $1 AND key = $2 AND deleted_at IS NULL
`

type GetRoleByKeyParams struct {
	TenantID uuid.UUID
	Key      string
}

// ---------------------------------------------------------------- 角色
// 角色 key 现在是**租户内**唯一：每家公司各有一个自己的内置 admin（§3.2 ①）。
func (q *Queries) GetRoleByKey(ctx context.Context, arg GetRoleByKeyParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByKey, arg.TenantID, arg.Key)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.DataScope,
		&i.Builtin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.TenantID,
	)
	return i, err
}

const getServiceAccountByPrefix = `-- name: GetServiceAccountByPrefix :one

SELECT sa.id, sa.name, sa.description, sa.key_prefix, sa.key_hash, sa.role_id, sa.status, sa.expires_at, sa.last_used_at, sa.created_at, sa.updated_at, sa.deleted_at, sa.created_by, sa.version, sa.tenant_id, t.status AS tenant_status
FROM service_accounts sa
JOIN tenants t ON t.id = sa.tenant_id
WHERE sa.key_prefix = $1
  AND sa.deleted_at IS NULL
  AND sa.status = 'active'
`

type GetServiceAccountByPrefixRow struct {
	ServiceAccount ServiceAccount
	TenantStatus   string
}

// ---------------------------------------------------------------- Service Account
// tenant-exempt: 和 GetLiveSession 同理 —— 拿 API Key 的 prefix 定位到一行，
//
//	那一行才告诉我们它属于哪个租户。uk_service_accounts_prefix 也保持全平台唯一。
//	租户状态同样要带上：机器身份也不能在停用的租户里继续跑（§8.2）。
func (q *Queries) GetServiceAccountByPrefix(ctx context.Context, keyPrefix string) (GetServiceAccountByPrefixRow, error) {
	row := q.db.QueryRow(ctx, getServiceAccountByPrefix, keyPrefix)
	var i GetServiceAccountByPrefixRow
	err := row.Scan(
		&i.ServiceAccount.ID,
		&i.ServiceAccount.Name,
		&i.ServiceAccount.Description,
		&i.ServiceAccount.KeyPrefix,
		&i.ServiceAccount.KeyHash,
		&i.ServiceAccount.RoleID,
		&i.ServiceAccount.Status,
		&i.ServiceAccount.ExpiresAt,
		&i.ServiceAccount.LastUsedAt,
		&i.ServiceAccount.CreatedAt,
		&i.ServiceAccount.UpdatedAt,
		&i.ServiceAccount.DeletedAt,
		&i.ServiceAccount.CreatedBy,
		&i.ServiceAccount.Version,
		&i.ServiceAccount.TenantID,
		&i.TenantStatus,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, email, password_hash, password_changed_at, must_change_password, status, failed_attempts, locked_until, last_login_at, created_at, updated_at, deleted_at, created_by, version, phone, department_id, tenant_id FROM users
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// ⚠️ 「按 id 查一行」也必须带 tenant_id（§11.1）—— 这是 OWASP API Top 10 第一名的 BOLA。
// id 唯一不代表这一行是你的。
func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.TenantID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.Phone,
		&i.DepartmentID,
		&i.TenantID,
	)
	return i, err
}

const getUserByIdentifier = `-- name: GetUserByIdentifier :one


SELECT id, username, display_name, email, password_hash, password_changed_at, must_change_password, status, failed_attempts, locked_until, last_login_at, created_at, updated_at, deleted_at, created_by, version, phone, department_id, tenant_id FROM users
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND (username = $2
       OR lower(email) = lower($2)
       OR phone = $2)
ORDER BY (username = $2) DESC
LIMIT 1
`

type GetUserByIdentifierParams struct {
	TenantID   uuid.UUID
	Identifier string
}

// 认证相关查询（DECISIONS.md §3、§6、§8.1）。
//
// ⚠️ 这个文件是整套租户隔离里**最需要小心**的地方（MULTI-TENANCY.md §3.2 ③）：
// 认证发生在租户上下文建立**之前**。验证会话是「拿 cookie 里的 token 去查这是谁」，
// 那一刻还不知道租户是谁；API Key 同理。所以查 sessions / service_accounts 的那几条
// 只能靠代码自觉，标了 `-- tenant-exempt:`。**其余每一条都必须带 tenant_id。**
// ---------------------------------------------------------------- 用户
// 登录标识符：用户名 / 邮箱 / 手机号都行。**租户内**唯一 ——
// 登录时先用公司代码查到租户，再拿租户 + 标识符查人。
// 万一有人的用户名恰好等于另一个人的邮箱，优先按用户名匹配，结果才是确定的。
func (q *Queries) GetUserByIdentifier(ctx context.Context, arg GetUserByIdentifierParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentifier, arg.TenantID, arg.Identifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.Phone,
		&i.DepartmentID,
		&i.TenantID,
	)
	return i, err
}

const listRolePolicies = `-- name: ListRolePolicies :many

SELECT r.key AS role_key, rp.resource, rp.action
FROM role_permissions rp
JOIN roles r ON r.id = rp.role_id AND r.tenant_id = rp.tenant_id
WHERE rp.tenant_id = $1
  AND r.deleted_at IS NULL AND r.status = 'active'
ORDER BY r.key, rp.resource, rp.action
`

type ListRolePoliciesRow struct {
	RoleKey  string
	Resource string
	Action   string
}

// 下面三个查询喂给 Casbin：策略加载进内存，变更靠 LISTEN/NOTIFY 触发重载。
//
// 都带上了 tenant_id —— 加载方按租户逐个加载。⚠️ Casbin 的 **domain 模型**
// 是第 ③ 步的事（§3.1），在那之前多个租户的同名角色 key 在 enforcer 里还是会撞。
// 查询这一层先摆正，③ 只用改 enforcer，不用回来改 SQL。
func (q *Queries) ListRolePolicies(ctx context.Context, tenantID uuid.UUID) ([]ListRolePoliciesRow, error) {
	rows, err := q.db.Query(ctx, listRolePolicies, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePoliciesRow{}
	for rows.Next() {
		var i ListRolePoliciesRow
		if err := rows.Scan(&i.RoleKey, &i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesOfUser = `-- name: ListRolesOfUser :many
SELECT r.id, r.key, r.name, r.description, r.data_scope, r.builtin, r.status, r.created_at, r.updated_at, r.deleted_at, r.created_by, r.version, r.tenant_id FROM roles r
JOIN user_roles ur ON ur.role_id = r.id AND ur.tenant_id = r.tenant_id
WHERE r.tenant_id = $1
  AND ur.user_id = $2
  AND r.deleted_at IS NULL
  AND r.status = 'active'
ORDER BY r.key
`

type ListRolesOfUserParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListRolesOfUser(ctx context.Context, arg ListRolesOfUserParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesOfUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.DataScope,
			&i.Builtin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.Version,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceAccountRoleBindings = `-- name: ListServiceAccountRoleBindings :many
SELECT sa.id AS service_account_id, r.key AS role_key, r.data_scope
FROM service_accounts sa
JOIN roles r ON r.id = sa.role_id AND r.tenant_id = sa.tenant_id
WHERE sa.tenant_id = $1
  AND sa.deleted_at IS NULL AND sa.status = 'active'
  AND r.deleted_at IS NULL AND r.status = 'active'
ORDER BY sa.id
`

type ListServiceAccountRoleBindingsRow struct {
	ServiceAccountID uuid.UUID
	RoleKey          string
	DataScope        string
}

func (q *Queries) ListServiceAccountRoleBindings(ctx context.Context, tenantID uuid.UUID) ([]ListServiceAccountRoleBindingsRow, error) {
	rows, err := q.db.Query(ctx, listServiceAccountRoleBindings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceAccountRoleBindingsRow{}
	for rows.Next() {
		var i ListServiceAccountRoleBindingsRow
		if err := rows.Scan(&i.ServiceAccountID, &i.RoleKey, &i.DataScope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleBindings = `-- name: ListUserRoleBindings :many
SELECT ur.user_id, r.key AS role_key, r.data_scope
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id AND r.tenant_id = ur.tenant_id
JOIN users u ON u.id = ur.user_id AND u.tenant_id = ur.tenant_id
WHERE ur.tenant_id = $1
  AND r.deleted_at IS NULL AND r.status = 'active'
  AND u.deleted_at IS NULL AND u.status = 'active'
ORDER BY ur.user_id
`

type ListUserRoleBindingsRow struct {
	UserID    uuid.UUID
	RoleKey   string
	DataScope string
}

func (q *Queries) ListUserRoleBindings(ctx context.Context, tenantID uuid.UUID) ([]ListUserRoleBindingsRow, error) {
	rows, err := q.db.Query(ctx, listUserRoleBindings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRoleBindingsRow{}
	for rows.Next() {
		var i ListUserRoleBindingsRow
		if err := rows.Scan(&i.UserID, &i.RoleKey, &i.DataScope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLoginFailure = `-- name: MarkLoginFailure :one
UPDATE users
SET failed_attempts = failed_attempts + 1,
    -- 达到阈值就锁一段时间；阈值和时长来自 settings 表（现在是**租户级**的）
    locked_until    = CASE WHEN failed_attempts + 1 >= $1::int
                           THEN now() + make_interval(mins => $2::int)
                           ELSE locked_until END
WHERE tenant_id = $3 AND id = $4
RETURNING failed_attempts, locked_until
`

type MarkLoginFailureParams struct {
	MaxFailures int32
	LockMinutes int32
	TenantID    uuid.UUID
	ID          uuid.UUID
}

type MarkLoginFailureRow struct {
	FailedAttempts int32
	LockedUntil    *time.Time
}

func (q *Queries) MarkLoginFailure(ctx context.Context, arg MarkLoginFailureParams) (MarkLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, markLoginFailure,
		arg.MaxFailures,
		arg.LockMinutes,
		arg.TenantID,
		arg.ID,
	)
	var i MarkLoginFailureRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return i, err
}

const markLoginSuccess = `-- name: MarkLoginSuccess :exec
UPDATE users
SET failed_attempts = 0,
    locked_until    = NULL,
    last_login_at   = now()
WHERE tenant_id = $1 AND id = $2
`

type MarkLoginSuccessParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MarkLoginSuccess(ctx context.Context, arg MarkLoginSuccessParams) error {
	_, err := q.db.Exec(ctx, markLoginSuccess, arg.TenantID, arg.ID)
	return err
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE tenant_id = $1
  AND user_id = $2
  AND id <> $3
  AND revoked_at IS NULL
`

type RevokeOtherUserSessionsParams struct {
	TenantID      uuid.UUID
	UserID        uuid.UUID
	KeepSessionID uuid.UUID
}

// 改密码之后用：把这个人的其它会话全踢掉，只留当前这条。
func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherUserSessions, arg.TenantID, arg.UserID, arg.KeepSessionID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now()
WHERE tenant_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.TenantID, arg.ID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE tenant_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, arg.TenantID, arg.UserID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users
SET password_hash        = $1,
    password_changed_at  = now(),
    must_change_password = false,
    failed_attempts      = 0,
    locked_until         = NULL,
    version              = version + 1
WHERE tenant_id = $2 AND id = $3 AND deleted_at IS NULL
`

type SetUserPasswordParams struct {
	PasswordHash string
	TenantID     uuid.UUID
	ID           uuid.UUID
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.PasswordHash, arg.TenantID, arg.ID)
	return err
}

const touchServiceAccount = `-- name: TouchServiceAccount :exec
UPDATE service_accounts SET last_used_at = now()
WHERE tenant_id = $1 AND id = $2
`

type TouchServiceAccountParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) TouchServiceAccount(ctx context.Context, arg TouchServiceAccountParams) error {
	_, err := q.db.Exec(ctx, touchServiceAccount, arg.TenantID, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now()
WHERE tenant_id = $1 AND id = $2
`

type TouchSessionParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.TenantID, arg.ID)
	return err
}
