// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: department.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDepartmentChildren = `-- name: CountDepartmentChildren :one
SELECT count(*) FROM departments
WHERE tenant_id = $1 AND parent_id = $2 AND deleted_at IS NULL
`

type CountDepartmentChildrenParams struct {
	TenantID uuid.UUID
	ParentID *uuid.UUID
}

func (q *Queries) CountDepartmentChildren(ctx context.Context, arg CountDepartmentChildrenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartmentChildren, arg.TenantID, arg.ParentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDepartmentUsers = `-- name: CountDepartmentUsers :one
SELECT count(*) FROM users
WHERE tenant_id = $1 AND department_id = $2
  AND deleted_at IS NULL
`

type CountDepartmentUsersParams struct {
	TenantID     uuid.UUID
	DepartmentID *uuid.UUID
}

func (q *Queries) CountDepartmentUsers(ctx context.Context, arg CountDepartmentUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartmentUsers, arg.TenantID, arg.DepartmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (tenant_id, id, parent_id, name, code, sort_order, remark, status, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9)
RETURNING id, parent_id, name, code, sort_order, remark, status, created_at, updated_at, deleted_at, created_by, version, tenant_id
`

type CreateDepartmentParams struct {
	TenantID  uuid.UUID
	ID        uuid.UUID
	ParentID  *uuid.UUID
	Name      string
	Code      string
	SortOrder int32
	Remark    string
	Status    string
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.TenantID,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Code,
		arg.SortOrder,
		arg.Remark,
		arg.Status,
		arg.CreatedBy,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.SortOrder,
		&i.Remark,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.TenantID,
	)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, parent_id, name, code, sort_order, remark, status, created_at, updated_at, deleted_at, created_by, version, tenant_id FROM departments
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetDepartmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetDepartment(ctx context.Context, arg GetDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, arg.TenantID, arg.ID)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.SortOrder,
		&i.Remark,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.TenantID,
	)
	return i, err
}

const listDepartmentSubtreeIDs = `-- name: ListDepartmentSubtreeIDs :many
WITH RECURSIVE subtree AS (
    SELECT d.id AS node_id FROM departments d
    WHERE d.tenant_id = $1 AND d.id = $2 AND d.deleted_at IS NULL
    UNION ALL
    SELECT d.id FROM departments d
    JOIN subtree s ON d.parent_id = s.node_id
    WHERE d.tenant_id = $1 AND d.deleted_at IS NULL
)
SELECT node_id FROM subtree
`

type ListDepartmentSubtreeIDsParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// 取一个节点和它所有后代的 id。改父节点时用来挡「把自己挂到自己的子孙下面」——
// 那会造出一个从树上断开的环，整棵树直接查不出来。
//
// ⚠️ **递归那一半也要带 tenant_id**（§10.7）。种子那半带了就完事，是最容易漏的一处：
// 递归部分只靠 parent_id 关联，看着「跟着种子走自然就在租户里」。
// 复合外键确实保证了不会有跨租户的父子关系，所以实际泄不了 —— 但这里要的是**纵深防御**：
// 不依赖另一个约束的正确性。SQL 静态检查也会拦下不带租户条件的那一半。
func (q *Queries) ListDepartmentSubtreeIDs(ctx context.Context, arg ListDepartmentSubtreeIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDepartmentSubtreeIDs, arg.TenantID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var node_id uuid.UUID
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many

SELECT d.id, d.parent_id, d.name, d.code, d.sort_order, d.remark, d.status, d.created_at, d.updated_at, d.deleted_at, d.created_by, d.version, d.tenant_id, (SELECT count(*) FROM users u
             WHERE u.tenant_id = d.tenant_id AND u.department_id = d.id
               AND u.deleted_at IS NULL) AS user_count
FROM departments d
WHERE d.tenant_id = $1
  AND d.deleted_at IS NULL
  AND ($2::varchar IS NULL
       OR d.name ILIKE $2 OR d.code ILIKE $2)
  AND ($3::varchar IS NULL OR d.status = $3)
ORDER BY d.sort_order, d.name
`

type ListDepartmentsParams struct {
	TenantID uuid.UUID
	Keyword  *string
	Status   *string
}

type ListDepartmentsRow struct {
	ID        uuid.UUID
	ParentID  *uuid.UUID
	Name      string
	Code      string
	SortOrder int32
	Remark    string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	CreatedBy *uuid.UUID
	Version   int32
	TenantID  uuid.UUID
	UserCount int64
}

// 部门（DECISIONS.md §2）。
// 部门是树，**一次全取**：内部系统撑死几百个节点，分页反而会把树切断。
// 排序保证同一个父下按 sort_order，前端拼树时不用再排一遍。
func (q *Queries) ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]ListDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listDepartments, arg.TenantID, arg.Keyword, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDepartmentsRow{}
	for rows.Next() {
		var i ListDepartmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Code,
			&i.SortOrder,
			&i.Remark,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.Version,
			&i.TenantID,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDepartment = `-- name: SoftDeleteDepartment :one
UPDATE departments
SET deleted_at = now(), version = version + 1
WHERE tenant_id = $1
  AND id = $2
  AND version = $3
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteDepartmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Version  int32
}

func (q *Queries) SoftDeleteDepartment(ctx context.Context, arg SoftDeleteDepartmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteDepartment, arg.TenantID, arg.ID, arg.Version)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET parent_id  = $1,
    name       = $2,
    code       = $3,
    sort_order = $4,
    remark     = $5,
    status     = $6,
    version    = version + 1
WHERE tenant_id = $7
  AND id = $8
  AND version = $9
  AND deleted_at IS NULL
RETURNING id, parent_id, name, code, sort_order, remark, status, created_at, updated_at, deleted_at, created_by, version, tenant_id
`

type UpdateDepartmentParams struct {
	ParentID  *uuid.UUID
	Name      string
	Code      string
	SortOrder int32
	Remark    string
	Status    string
	TenantID  uuid.UUID
	ID        uuid.UUID
	Version   int32
}

// 乐观锁：影响 0 行说明版本对不上，service 层翻成 common.version_conflict（§2.4）
func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ParentID,
		arg.Name,
		arg.Code,
		arg.SortOrder,
		arg.Remark,
		arg.Status,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Code,
		&i.SortOrder,
		&i.Remark,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.TenantID,
	)
	return i, err
}
