// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package sqlcgen

import (
	"context"
	"time"
)

const databaseNow = `-- name: DatabaseNow :one

SELECT now()::timestamptz AS now
`

// 探活用的最小查询：/readyz 靠它确认「连得上库，且库真的在响应」，
// 而不是只看连接池状态。
// tenant-exempt: 探活查询，一张表都不碰
func (q *Queries) DatabaseNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}
