// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlcgen

import (
	"context"
	"time"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :execrows

INSERT INTO idempotency_keys (key, expires_at)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
    SET expires_at = EXCLUDED.expires_at
    WHERE idempotency_keys.expires_at <= now()
`

type ClaimIdempotencyKeyParams struct {
	Key       string
	ExpiresAt time.Time
}

// 幂等键的持久化存储（SCALING.md §1）。表没有 tenant_id（租户已拼进 key），
// 是跨租户的 infra 表 —— 不在 tenantsql 的租户表清单里，查询天然走 Unscoped 句柄。
// 豁免注释一律写在 `-- name:` 之后（SplitQueries 按此归属，写在前面会错位到上一条）。
// ClaimIdempotencyKey 原子地「认领」一个键：能认领（新键、或旧键已过期）返回 1 行，
// 键还有效（重放）返回 0 行。靠 ON CONFLICT ... WHERE 一条语句做完，不用先查后写。
// tenant-exempt: idempotency_keys 是跨租户 infra 表，没有 tenant_id 列（租户已拼进 key 字符串）
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimIdempotencyKey, arg.Key, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE expires_at <= now()
`

// DeleteExpiredIdempotencyKeys 清过期键，后台任务定时调。
// tenant-exempt: 清过期键的后台任务，跨租户一次扫描
func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const forgetIdempotencyKey = `-- name: ForgetIdempotencyKey :exec
DELETE FROM idempotency_keys WHERE key = $1
`

// ForgetIdempotencyKey 释放一个键，让客户端能安全重试。请求失败时调。
// tenant-exempt: 同上，跨租户 infra 表
func (q *Queries) ForgetIdempotencyKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, forgetIdempotencyKey, key)
	return err
}
