// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type AuditChainHead struct {
	Hash     []byte
	TenantID uuid.UUID
}

type AuditLog struct {
	ID         uuid.UUID
	OccurredAt time.Time
	RequestID  string
	ActorType  string
	ActorID    *uuid.UUID
	ActorName  string
	Resource   string
	Action     string
	ResourceID *uuid.UUID
	Method     string
	Path       string
	IP         *netip.Addr
	UserAgent  string
	HTTPStatus int32
	DurationMs int32
	Detail     []byte
	PrevHash   []byte
	Hash       []byte
	TenantID   *uuid.UUID
}

type Department struct {
	ID        uuid.UUID
	ParentID  *uuid.UUID
	Name      string
	Code      string
	SortOrder int32
	Remark    string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	CreatedBy *uuid.UUID
	Version   int32
	TenantID  uuid.UUID
}

type IdempotencyKey struct {
	Key       string
	ExpiresAt time.Time
}

type PasswordResetToken struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type PendingRegistration struct {
	ID                uuid.UUID
	Email             string
	CompanyName       string
	DesiredCode       string
	AdminPasswordHash string
	TokenHash         []byte
	ExpiresAt         time.Time
	CreatedAt         time.Time
}

type PlatformAdmin struct {
	ID                 uuid.UUID
	Username           string
	DisplayName        string
	PasswordHash       string
	PasswordChangedAt  time.Time
	MustChangePassword bool
	Status             string
	FailedAttempts     int32
	LockedUntil        *time.Time
	LastLoginAt        *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	CreatedBy          *uuid.UUID
	Version            int32
}

type PlatformSession struct {
	ID         uuid.UUID
	TokenHash  []byte
	AdminID    uuid.UUID
	IP         *netip.Addr
	UserAgent  string
	ExpiresAt  time.Time
	LastSeenAt time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
}

type PlatformSetting struct {
	Key         string
	Value       []byte
	Description string
	UpdatedAt   time.Time
	UpdatedBy   *uuid.UUID
}

type RateLimit struct {
	Key         string
	WindowStart time.Time
	Count       int32
}

type Role struct {
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	DataScope   string
	Builtin     bool
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	CreatedBy   *uuid.UUID
	Version     int32
	TenantID    uuid.UUID
}

type RolePermission struct {
	RoleID    uuid.UUID
	Resource  string
	Action    string
	CreatedAt time.Time
	TenantID  uuid.UUID
}

type ServiceAccount struct {
	ID          uuid.UUID
	Name        string
	Description string
	KeyPrefix   string
	KeyHash     []byte
	RoleID      uuid.UUID
	Status      string
	ExpiresAt   *time.Time
	LastUsedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
	CreatedBy   *uuid.UUID
	Version     int32
	TenantID    uuid.UUID
}

type Session struct {
	ID         uuid.UUID
	TokenHash  []byte
	UserID     uuid.UUID
	IP         *netip.Addr
	UserAgent  string
	ExpiresAt  time.Time
	LastSeenAt time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
	TenantID   uuid.UUID
}

type Setting struct {
	Key         string
	Value       []byte
	Description string
	UpdatedAt   time.Time
	UpdatedBy   *uuid.UUID
	TenantID    uuid.UUID
}

type Supplier struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Status    *string
	Credit    *decimal.Decimal
	StartedAt *time.Time
	Remark    *string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
	CreatedBy *uuid.UUID
	Version   int32
}

type Tenant struct {
	ID        uuid.UUID
	Code      string
	Name      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy *uuid.UUID
	Version   int32
	UserCount int32
}

type User struct {
	ID                 uuid.UUID
	Username           string
	DisplayName        string
	Email              *string
	PasswordHash       string
	PasswordChangedAt  time.Time
	MustChangePassword bool
	Status             string
	FailedAttempts     int32
	LockedUntil        *time.Time
	LastLoginAt        *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	CreatedBy          *uuid.UUID
	Version            int32
	Phone              *string
	DepartmentID       *uuid.UUID
	TenantID           uuid.UUID
}

type UserRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt time.Time
	TenantID  uuid.UUID
}
