// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec

INSERT INTO password_reset_tokens (tenant_id, id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3,
        $4, $5)
`

type CreatePasswordResetTokenParams struct {
	TenantID  uuid.UUID
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

// 忘记密码的一次性 token（MULTI-TENANCY.md §5）。库里只存哈希。
// 租户已知的（申请、改密）走 ForTenant；按 token_hash 校验那一条租户未知，走 Unscoped + 豁免。
// 豁免注释写在 `-- name:` 之后（SplitQueries 按此归属）。
// CreatePasswordResetToken 建一条 token。申请时按公司代码定位了租户，走 ForTenant。
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.TenantID,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :execrows
DELETE FROM password_reset_tokens WHERE expires_at < now() OR used_at IS NOT NULL
`

// DeleteExpiredPasswordResetTokens 清死掉的 token（过期或已用），后台任务定时调。
// tenant-exempt: 清理任务跨租户一次扫描，只按状态删死掉的行。
func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLivePasswordResetToken = `-- name: GetLivePasswordResetToken :one
SELECT id, tenant_id, user_id FROM password_reset_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
`

type GetLivePasswordResetTokenRow struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	UserID   uuid.UUID
}

// GetLivePasswordResetToken 按 token_hash 取一条还有效的 token（未用、未过期）。
// tenant-exempt: 校验 token 的那一刻用户还没登录、租户未知 —— 查出来的这行才告诉我们
//
//	tenant_id + user_id（和 GetLiveSession 一个道理，token_hash 全平台唯一）。
func (q *Queries) GetLivePasswordResetToken(ctx context.Context, tokenHash []byte) (GetLivePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getLivePasswordResetToken, tokenHash)
	var i GetLivePasswordResetTokenRow
	err := row.Scan(&i.ID, &i.TenantID, &i.UserID)
	return i, err
}

const invalidateUserResetTokens = `-- name: InvalidateUserResetTokens :exec
UPDATE password_reset_tokens
SET used_at = now()
WHERE tenant_id = $1
  AND user_id = $2
  AND used_at IS NULL
`

type InvalidateUserResetTokensParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

// InvalidateUserResetTokens 把某人还没用的 token 全标记成已用 —— 申请新的时先作废旧的，
// 保证一个用户同时只有一条有效 token。
func (q *Queries) InvalidateUserResetTokens(ctx context.Context, arg InvalidateUserResetTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateUserResetTokens, arg.TenantID, arg.UserID)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :execrows
UPDATE password_reset_tokens
SET used_at = now()
WHERE tenant_id = $1 AND id = $2 AND used_at IS NULL
`

type MarkPasswordResetTokenUsedParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// MarkPasswordResetTokenUsed **原子认领**一条 token：只有还没被用的才标记成功、返回 1 行。
// 改密前先认领，认领到 0 行说明并发里别人已经用掉了 —— 保证一次性、防 TOCTOU 重用。
func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, arg MarkPasswordResetTokenUsedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPasswordResetTokenUsed, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
