// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_registration.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimPendingRegistrationByToken = `-- name: ClaimPendingRegistrationByToken :one
DELETE FROM pending_registrations
WHERE token_hash = $1 AND expires_at > now()
RETURNING email, company_name, desired_code, admin_password_hash
`

type ClaimPendingRegistrationByTokenRow struct {
	Email             string
	CompanyName       string
	DesiredCode       string
	AdminPasswordHash string
}

// ClaimPendingRegistrationByToken 按 token_hash **原子认领**一条还没过期的待验证记录：
// 一条 DELETE ... RETURNING 同时删掉并取回资料。并发里两次验证只有一个能拿到行，
// 另一个 0 行 → 「链接无效或已过期」，天然防重复建租户（TOCTOU）。
// tenant-exempt: 验证时还没有租户，按 token 定位（token_hash 全平台唯一）
func (q *Queries) ClaimPendingRegistrationByToken(ctx context.Context, tokenHash []byte) (ClaimPendingRegistrationByTokenRow, error) {
	row := q.db.QueryRow(ctx, claimPendingRegistrationByToken, tokenHash)
	var i ClaimPendingRegistrationByTokenRow
	err := row.Scan(
		&i.Email,
		&i.CompanyName,
		&i.DesiredCode,
		&i.AdminPasswordHash,
	)
	return i, err
}

const createPendingRegistration = `-- name: CreatePendingRegistration :exec

INSERT INTO pending_registrations
    (id, email, company_name, desired_code, admin_password_hash, token_hash, expires_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type CreatePendingRegistrationParams struct {
	ID                uuid.UUID
	Email             string
	CompanyName       string
	DesiredCode       string
	AdminPasswordHash string
	TokenHash         []byte
	ExpiresAt         time.Time
}

// 自助注册的待验证记录（MULTI-TENANCY.md §5）。表没有 tenant_id（还没建租户），
// 跨租户 infra 表，全走 Unscoped 句柄。豁免注释写在 `-- name:` 之后。
// CreatePendingRegistration 存一条待验证注册。
// tenant-exempt: pending_registrations 是「建租户之前」的 infra 表，没有 tenant_id
func (q *Queries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) error {
	_, err := q.db.Exec(ctx, createPendingRegistration,
		arg.ID,
		arg.Email,
		arg.CompanyName,
		arg.DesiredCode,
		arg.AdminPasswordHash,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredPendingRegistrations = `-- name: DeleteExpiredPendingRegistrations :execrows
DELETE FROM pending_registrations WHERE expires_at < now()
`

// DeleteExpiredPendingRegistrations 清过期记录，后台任务定时调。
// tenant-exempt: 清理任务跨租户一次扫描
func (q *Queries) DeleteExpiredPendingRegistrations(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPendingRegistrations)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const invalidatePendingRegistrationsByEmail = `-- name: InvalidatePendingRegistrationsByEmail :exec
DELETE FROM pending_registrations WHERE lower(email) = lower($1)
`

// InvalidatePendingRegistrationsByEmail 删掉同一邮箱之前没验证的记录 —— 重发验证信时先清旧的。
// tenant-exempt: 同上，跨租户 infra 表
func (q *Queries) InvalidatePendingRegistrationsByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, invalidatePendingRegistrationsByEmail, email)
	return err
}
