// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const countPlatformAdmins = `-- name: CountPlatformAdmins :one

SELECT count(*) FROM platform_admins WHERE deleted_at IS NULL
`

// ---------------------------------------------------------------- 平台管理员
// tenant-exempt: platform_admins 是平台级表，平台管理员不属于任何租户（§2.3）
func (q *Queries) CountPlatformAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantsForPlatform = `-- name: CountTenantsForPlatform :one
SELECT count(*) FROM tenants
WHERE ($1::varchar IS NULL
       OR name ILIKE $1 OR code ILIKE $1)
  AND ($2::varchar IS NULL OR status = $2)
`

type CountTenantsForPlatformParams struct {
	Keyword *string
	Status  *string
}

// tenant-exempt: 同上
func (q *Queries) CountTenantsForPlatform(ctx context.Context, arg CountTenantsForPlatformParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantsForPlatform, arg.Keyword, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatformAdmin = `-- name: CreatePlatformAdmin :one
INSERT INTO platform_admins (id, username, display_name, password_hash, must_change_password)
VALUES ($1, $2, $3,
        $4, $5)
RETURNING id, username, display_name, password_hash, password_changed_at, must_change_password, status, failed_attempts, locked_until, last_login_at, created_at, updated_at, deleted_at, created_by, version
`

type CreatePlatformAdminParams struct {
	ID                 uuid.UUID
	Username           string
	DisplayName        string
	PasswordHash       string
	MustChangePassword bool
}

// tenant-exempt: 同上
func (q *Queries) CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, createPlatformAdmin,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.MustChangePassword,
	)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const createPlatformSession = `-- name: CreatePlatformSession :one

INSERT INTO platform_sessions (id, token_hash, admin_id, ip, user_agent, expires_at)
VALUES ($1, $2, $3,
        $4, $5, $6)
RETURNING id, token_hash, admin_id, ip, user_agent, expires_at, last_seen_at, revoked_at, created_at
`

type CreatePlatformSessionParams struct {
	ID        uuid.UUID
	TokenHash []byte
	AdminID   uuid.UUID
	IP        *netip.Addr
	UserAgent string
	ExpiresAt time.Time
}

// ---------------------------------------------------------------- 平台会话
// tenant-exempt: 平台会话不属于任何租户（§10.1）
func (q *Queries) CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, createPlatformSession,
		arg.ID,
		arg.TokenHash,
		arg.AdminID,
		arg.IP,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AdminID,
		&i.IP,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeadPlatformSessions = `-- name: DeleteDeadPlatformSessions :execrows
DELETE FROM platform_sessions
WHERE expires_at < now() - interval '7 days'
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '7 days')
`

// tenant-exempt: 清理任务，只按时间删已经死掉的行
func (q *Queries) DeleteDeadPlatformSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeadPlatformSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLivePlatformSession = `-- name: GetLivePlatformSession :one
SELECT s.id, s.token_hash, s.admin_id, s.ip, s.user_agent, s.expires_at, s.last_seen_at, s.revoked_at, s.created_at, a.id, a.username, a.display_name, a.password_hash, a.password_changed_at, a.must_change_password, a.status, a.failed_attempts, a.locked_until, a.last_login_at, a.created_at, a.updated_at, a.deleted_at, a.created_by, a.version
FROM platform_sessions s
JOIN platform_admins a ON a.id = s.admin_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND a.deleted_at IS NULL
`

type GetLivePlatformSessionRow struct {
	PlatformSession PlatformSession
	PlatformAdmin   PlatformAdmin
}

// tenant-exempt: 和租户那边的 GetLiveSession 同理 —— 拿 token 查这是谁
func (q *Queries) GetLivePlatformSession(ctx context.Context, tokenHash []byte) (GetLivePlatformSessionRow, error) {
	row := q.db.QueryRow(ctx, getLivePlatformSession, tokenHash)
	var i GetLivePlatformSessionRow
	err := row.Scan(
		&i.PlatformSession.ID,
		&i.PlatformSession.TokenHash,
		&i.PlatformSession.AdminID,
		&i.PlatformSession.IP,
		&i.PlatformSession.UserAgent,
		&i.PlatformSession.ExpiresAt,
		&i.PlatformSession.LastSeenAt,
		&i.PlatformSession.RevokedAt,
		&i.PlatformSession.CreatedAt,
		&i.PlatformAdmin.ID,
		&i.PlatformAdmin.Username,
		&i.PlatformAdmin.DisplayName,
		&i.PlatformAdmin.PasswordHash,
		&i.PlatformAdmin.PasswordChangedAt,
		&i.PlatformAdmin.MustChangePassword,
		&i.PlatformAdmin.Status,
		&i.PlatformAdmin.FailedAttempts,
		&i.PlatformAdmin.LockedUntil,
		&i.PlatformAdmin.LastLoginAt,
		&i.PlatformAdmin.CreatedAt,
		&i.PlatformAdmin.UpdatedAt,
		&i.PlatformAdmin.DeletedAt,
		&i.PlatformAdmin.CreatedBy,
		&i.PlatformAdmin.Version,
	)
	return i, err
}

const getPlatformAdminByID = `-- name: GetPlatformAdminByID :one
SELECT id, username, display_name, password_hash, password_changed_at, must_change_password, status, failed_attempts, locked_until, last_login_at, created_at, updated_at, deleted_at, created_by, version FROM platform_admins WHERE id = $1 AND deleted_at IS NULL
`

// tenant-exempt: 同上
func (q *Queries) GetPlatformAdminByID(ctx context.Context, id uuid.UUID) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByID, id)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const getPlatformAdminByUsername = `-- name: GetPlatformAdminByUsername :one
SELECT id, username, display_name, password_hash, password_changed_at, must_change_password, status, failed_attempts, locked_until, last_login_at, created_at, updated_at, deleted_at, created_by, version FROM platform_admins WHERE username = $1 AND deleted_at IS NULL
`

// tenant-exempt: 同上。平台登录只按用户名 —— 没有公司代码这一层
func (q *Queries) GetPlatformAdminByUsername(ctx context.Context, username string) (PlatformAdmin, error) {
	row := q.db.QueryRow(ctx, getPlatformAdminByUsername, username)
	var i PlatformAdmin
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const listPlatformSettings = `-- name: ListPlatformSettings :many


SELECT key, value FROM platform_settings ORDER BY key
`

type ListPlatformSettingsRow struct {
	Key   string
	Value []byte
}

// 平台管理端（MULTI-TENANCY.md §6、第 ⑤ 步）+ 平台级配置（§7.2）。
//
// ⚠️ **这个文件里的查询只许碰四张平台级表**：
// `tenants` / `platform_admins` / `platform_sessions` / `platform_settings`。
//
// 这不是口头约定：生成器按「引用的表全在平台级清单里」把它们分流到
// `Store.Platform()` 那个句柄上，平台服务**结构上就够不到业务表**。
// 哪天有人在这里写一条 `SELECT ... FROM users`，这条查询会掉到别的句柄上，
// 平台服务编译不过。
//
// 为什么这么在意：一旦平台端能查 users，「平台端结构上碰不到客户业务数据」
// 这个性质就没了 —— 而那句话是将来跟客户解释隔离时最有力的一句（§10.11）。
// 「租户列表要显示人数」这个需求就是靠 tenants.user_count 冗余绕开的，不是靠 join。
// ---------------------------------------------------------------- 平台级配置
// tenant-exempt: platform_settings 是平台级表，没有 tenant_id 这一列
func (q *Queries) ListPlatformSettings(ctx context.Context) ([]ListPlatformSettingsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformSettingsRow{}
	for rows.Next() {
		var i ListPlatformSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsForPlatform = `-- name: ListTenantsForPlatform :many

SELECT id, code, name, status, created_at, updated_at, created_by, version, user_count FROM tenants
WHERE ($1::varchar IS NULL
       OR name ILIKE $1 OR code ILIKE $1)
  AND ($2::varchar IS NULL OR status = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListTenantsForPlatformParams struct {
	Keyword *string
	Status  *string
	Offset  int32
	Limit   int32
}

// ---------------------------------------------------------------- 租户
// tenant-exempt: tenants 是平台级表。这是平台端的租户列表 ——
//
//	人数走 tenants.user_count 冗余列，**不 join users**（§6）
func (q *Queries) ListTenantsForPlatform(ctx context.Context, arg ListTenantsForPlatformParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsForPlatform,
		arg.Keyword,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Version,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlatformLoginFailure = `-- name: MarkPlatformLoginFailure :one
UPDATE platform_admins
SET failed_attempts = failed_attempts + 1,
    locked_until    = CASE WHEN failed_attempts + 1 >= $1::int
                           THEN now() + make_interval(mins => $2::int)
                           ELSE locked_until END
WHERE id = $3
RETURNING failed_attempts, locked_until
`

type MarkPlatformLoginFailureParams struct {
	MaxFailures int32
	LockMinutes int32
	ID          uuid.UUID
}

type MarkPlatformLoginFailureRow struct {
	FailedAttempts int32
	LockedUntil    *time.Time
}

// tenant-exempt: 同上
func (q *Queries) MarkPlatformLoginFailure(ctx context.Context, arg MarkPlatformLoginFailureParams) (MarkPlatformLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, markPlatformLoginFailure, arg.MaxFailures, arg.LockMinutes, arg.ID)
	var i MarkPlatformLoginFailureRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return i, err
}

const markPlatformLoginSuccess = `-- name: MarkPlatformLoginSuccess :exec
UPDATE platform_admins
SET failed_attempts = 0, locked_until = NULL, last_login_at = now()
WHERE id = $1
`

// tenant-exempt: 同上
func (q *Queries) MarkPlatformLoginSuccess(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPlatformLoginSuccess, id)
	return err
}

const revokeOtherPlatformSessions = `-- name: RevokeOtherPlatformSessions :exec
UPDATE platform_sessions SET revoked_at = now()
WHERE admin_id = $1
  AND id <> $2
  AND revoked_at IS NULL
`

type RevokeOtherPlatformSessionsParams struct {
	AdminID       uuid.UUID
	KeepSessionID uuid.UUID
}

// tenant-exempt: 同上。改密码之后把其它会话全踢掉，只留当前这条
func (q *Queries) RevokeOtherPlatformSessions(ctx context.Context, arg RevokeOtherPlatformSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherPlatformSessions, arg.AdminID, arg.KeepSessionID)
	return err
}

const revokePlatformSession = `-- name: RevokePlatformSession :exec
UPDATE platform_sessions SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

// tenant-exempt: 同上
func (q *Queries) RevokePlatformSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokePlatformSession, id)
	return err
}

const setPlatformAdminPassword = `-- name: SetPlatformAdminPassword :exec
UPDATE platform_admins
SET password_hash        = $1,
    password_changed_at  = now(),
    must_change_password = false,
    failed_attempts      = 0,
    locked_until         = NULL,
    version              = version + 1
WHERE id = $2 AND deleted_at IS NULL
`

type SetPlatformAdminPasswordParams struct {
	PasswordHash string
	ID           uuid.UUID
}

// tenant-exempt: 同上
func (q *Queries) SetPlatformAdminPassword(ctx context.Context, arg SetPlatformAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, setPlatformAdminPassword, arg.PasswordHash, arg.ID)
	return err
}

const setTenantStatus = `-- name: SetTenantStatus :one
UPDATE tenants
SET status = $1, version = version + 1
WHERE id = $2 AND version = $3
RETURNING id, code, name, status, created_at, updated_at, created_by, version, user_count
`

type SetTenantStatusParams struct {
	Status  string
	ID      uuid.UUID
	Version int32
}

// tenant-exempt: 同上。租户只停用不删除（§9.3）—— 没有删除语句是有意的
func (q *Queries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantStatus, arg.Status, arg.ID, arg.Version)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Version,
		&i.UserCount,
	)
	return i, err
}

const touchPlatformSession = `-- name: TouchPlatformSession :exec
UPDATE platform_sessions SET last_seen_at = now() WHERE id = $1
`

// tenant-exempt: 同上
func (q *Queries) TouchPlatformSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPlatformSession, id)
	return err
}

const upsertPlatformSetting = `-- name: UpsertPlatformSetting :exec
INSERT INTO platform_settings (key, value, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = excluded.value, updated_by = excluded.updated_by
`

type UpsertPlatformSettingParams struct {
	Key       string
	Value     []byte
	UpdatedBy *uuid.UUID
}

// tenant-exempt: 同上
func (q *Queries) UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) error {
	_, err := q.db.Exec(ctx, upsertPlatformSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
