// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	// 限流器的持久化存储（SCALING.md §1）。表没有 tenant_id（维度已拼进 key），
	// 跨租户 infra 表，走 Unscoped 句柄。豁免注释写在 `-- name:` 之后（SplitQueries 按此归属）。
	// BumpRateLimit 原子地把 (key, 当前窗口) 的计数 +1，返回加完之后的值。
	// 靠一条 INSERT ... ON CONFLICT DO UPDATE 完成，多副本并发自增不会丢。
	// tenant-exempt: rate_limits 是跨租户 infra 表，没有 tenant_id（维度已拼进 key）
	BumpRateLimit(ctx context.Context, arg BumpRateLimitParams) (int32, error)
	// 幂等键的持久化存储（SCALING.md §1）。表没有 tenant_id（租户已拼进 key），
	// 是跨租户的 infra 表 —— 不在 tenantsql 的租户表清单里，查询天然走 Unscoped 句柄。
	// 豁免注释一律写在 `-- name:` 之后（SplitQueries 按此归属，写在前面会错位到上一条）。
	// ClaimIdempotencyKey 原子地「认领」一个键：能认领（新键、或旧键已过期）返回 1 行，
	// 键还有效（重放）返回 0 行。靠 ON CONFLICT ... WHERE 一条语句做完，不用先查后写。
	// tenant-exempt: idempotency_keys 是跨租户 infra 表，没有 tenant_id 列（租户已拼进 key 字符串）
	ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error)
	// ClaimPendingRegistrationByToken 按 token_hash **原子认领**一条还没过期的待验证记录：
	// 一条 DELETE ... RETURNING 同时删掉并取回资料。并发里两次验证只有一个能拿到行，
	// 另一个 0 行 → 「链接无效或已过期」，天然防重复建租户（TOCTOU）。
	// tenant-exempt: 验证时还没有租户，按 token 定位（token_hash 全平台唯一）
	ClaimPendingRegistrationByToken(ctx context.Context, tokenHash []byte) (ClaimPendingRegistrationByTokenRow, error)
	ClearRolePermissions(ctx context.Context, arg ClearRolePermissionsParams) error
	ClearUserRoles(ctx context.Context, arg ClearUserRolesParams) error
	// 还有几个「启用状态 + 拥有通配权限」的人。
	// 停用/删除最后一个管理员会把所有人锁在门外，必须拦住。
	//
	// ⚠️ 这条**必须**按租户数（§3.2 ①）。原来是一条不带租户条件的全表 count，
	// 多租户下等于：A 公司还有 admin，B 公司删掉自己最后一个 admin 时检查照样通过 ——
	// **B 公司被锁在门外，只能上数据库救。**
	CountActiveAdmins(ctx context.Context, arg CountActiveAdminsParams) (int64, error)
	CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error)
	CountDepartmentChildren(ctx context.Context, arg CountDepartmentChildrenParams) (int64, error)
	CountDepartmentUsers(ctx context.Context, arg CountDepartmentUsersParams) (int64, error)
	// ---------------------------------------------------------------- 平台管理员
	// tenant-exempt: platform_admins 是平台级表，平台管理员不属于任何租户（§2.3）
	CountPlatformAdmins(ctx context.Context) (int64, error)
	CountRoleServiceAccounts(ctx context.Context, arg CountRoleServiceAccountsParams) (int64, error)
	CountRoleUsers(ctx context.Context, arg CountRoleUsersParams) (int64, error)
	CountRoles(ctx context.Context, arg CountRolesParams) (int64, error)
	CountServiceAccounts(ctx context.Context, arg CountServiceAccountsParams) (int64, error)
	CountSuppliers(ctx context.Context, arg CountSuppliersParams) (int64, error)
	// tenant-exempt: 同上
	CountTenantsForPlatform(ctx context.Context, arg CountTenantsForPlatformParams) (int64, error)
	CountUsers(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountUsersFiltered(ctx context.Context, arg CountUsersFilteredParams) (int64, error)
	// 开组织时给新组织建它自己的内置 admin 角色（MULTI-TENANCY.md §3.2 ①）。
	//
	// 和 CreateRole 分开是因为**只有这条能设 builtin = true**：
	// 管理页面新建出来的一律是普通角色，内置角色只由「开组织」这条链路建。
	// 内置角色不可改不可删，是权限体系的兜底 —— 它被谁随手建出来都不行。
	CreateBuiltinAdminRole(ctx context.Context, arg CreateBuiltinAdminRoleParams) (Role, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateManagedUser(ctx context.Context, arg CreateManagedUserParams) (User, error)
	// 忘记密码的一次性 token（MULTI-TENANCY.md §5）。库里只存哈希。
	// 租户已知的（申请、改密）走 ForTenant；按 token_hash 校验那一条租户未知，走 Unscoped + 豁免。
	// 豁免注释写在 `-- name:` 之后（SplitQueries 按此归属）。
	// CreatePasswordResetToken 建一条 token。申请时按公司代码定位了租户，走 ForTenant。
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	// 自助注册的待验证记录（MULTI-TENANCY.md §5）。表没有 tenant_id（还没建租户），
	// 跨租户 infra 表，全走 Unscoped 句柄。豁免注释写在 `-- name:` 之后。
	// CreatePendingRegistration 存一条待验证注册。
	// tenant-exempt: pending_registrations 是「建租户之前」的 infra 表，没有 tenant_id
	CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) error
	// tenant-exempt: 同上
	CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error)
	// ---------------------------------------------------------------- 平台会话
	// tenant-exempt: 平台会话不属于任何租户（§10.1）
	CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error)
	// builtin 不给传：内置角色只由「开租户」那条链路建（第 ⑤ 步），
	// 管理页面新建出来的一律是普通角色。
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	// 返回的行同样不含 key_hash：明文密钥在应用侧，调用方手里已经有了，
	// 不需要也不该从这里再拿一次。
	CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (CreateServiceAccountRow, error)
	// ---------------------------------------------------------------- 会话
	// sessions.tenant_id 看着像冗余（能从 users 推出来），但整套隔离都以「会话里的租户」
	// 为唯一来源，所以它必须存在这里。两份真相会不会漂？不会 ——
	// 复合外键 (tenant_id, user_id) → users (tenant_id, id) 让数据库保证它们永远一致（§10.2）。
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	// tenant-exempt: 同上
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// 探活用的最小查询：/readyz 靠它确认「连得上库，且库真的在响应」，
	// 而不是只看连接池状态。
	// tenant-exempt: 探活查询，一张表都不碰
	DatabaseNow(ctx context.Context) (time.Time, error)
	// tenant-exempt: 清理任务，只按时间删已经死掉的行
	DeleteDeadPlatformSessions(ctx context.Context) (int64, error)
	// tenant-exempt: 清理过期会话的后台任务是跨租户的一次扫描，不属于任何租户。
	//   它只按时间删已经死掉的行，读不到任何租户数据。
	DeleteDeadSessions(ctx context.Context) (int64, error)
	// DeleteExpiredIdempotencyKeys 清过期键，后台任务定时调。
	// tenant-exempt: 清过期键的后台任务，跨租户一次扫描
	DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	// DeleteExpiredPasswordResetTokens 清死掉的 token（过期或已用），后台任务定时调。
	// tenant-exempt: 清理任务跨租户一次扫描，只按状态删死掉的行。
	DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error)
	// DeleteExpiredPendingRegistrations 清过期记录，后台任务定时调。
	// tenant-exempt: 清理任务跨租户一次扫描
	DeleteExpiredPendingRegistrations(ctx context.Context) (int64, error)
	// DeleteOldRateLimits 清掉早于 cutoff 的窗口，后台任务定时调。
	// tenant-exempt: 清旧窗口的后台任务，跨租户一次扫描
	DeleteOldRateLimits(ctx context.Context, cutoff time.Time) (int64, error)
	// tenant-exempt: 同上。保留期到了整分区 DROP，保留天数也是平台级配置
	DropOldAuditPartitions(ctx context.Context, cutoff time.Time) (int32, error)
	// tenant-exempt: 建分区是跨租户的后台任务 —— 分区按月切，不按租户切
	EnsureAuditPartition(ctx context.Context, target time.Time) (string, error)
	// ForgetIdempotencyKey 释放一个键，让客户端能安全重试。请求失败时调。
	// tenant-exempt: 同上，跨租户 infra 表
	ForgetIdempotencyKey(ctx context.Context, key string) error
	GetDepartment(ctx context.Context, arg GetDepartmentParams) (Department, error)
	// GetLivePasswordResetToken 按 token_hash 取一条还有效的 token（未用、未过期）。
	// tenant-exempt: 校验 token 的那一刻用户还没登录、租户未知 —— 查出来的这行才告诉我们
	//   tenant_id + user_id（和 GetLiveSession 一个道理，token_hash 全平台唯一）。
	GetLivePasswordResetToken(ctx context.Context, tokenHash []byte) (GetLivePasswordResetTokenRow, error)
	// tenant-exempt: 和租户那边的 GetLiveSession 同理 —— 拿 token 查这是谁
	GetLivePlatformSession(ctx context.Context, tokenHash []byte) (GetLivePlatformSessionRow, error)
	// tenant-exempt: 这就是「认证发生在租户上下文之前」的那一刻 —— 拿 cookie 里的 token
	//   查这是谁，查出来的这一行才告诉我们 tenant_id。所以 uk_sessions_token 也保持
	//   全平台唯一，没加 tenant_id（§2.2）。
	//   ⚠️ 返回的 session.tenant_id 是后续所有隔离的唯一来源，谁都别再从别处推。
	//
	// 顺带把租户状态一起取出来（§8.2）。**停用一个租户必须立刻生效** ——
	// 只挡新登录的话，客户的人拿着已有 cookie 能一直用到过期，而界面上显示「已停用」。
	// 在这里查而不是「停用时逐条吊销会话」：这样连绕过应用直接改库的停用也照样生效。
	GetLiveSession(ctx context.Context, tokenHash []byte) (GetLiveSessionRow, error)
	// tenant-exempt: 同上
	GetPlatformAdminByID(ctx context.Context, id uuid.UUID) (PlatformAdmin, error)
	// tenant-exempt: 同上。平台登录只按用户名 —— 没有公司代码这一层
	GetPlatformAdminByUsername(ctx context.Context, username string) (PlatformAdmin, error)
	// 计数和 ListRoles 保持一致 —— 详情页要显示「有多少人在用这个角色」，
	// 少一个 user_count 就会显示成「还没有人用」，而列表上明明写着 2 个人。
	// 同一个字段两个接口说法不一样，比不显示还糟。
	GetRole(ctx context.Context, arg GetRoleParams) (GetRoleRow, error)
	// ---------------------------------------------------------------- 角色
	// 角色 key 现在是**租户内**唯一：每家公司各有一个自己的内置 admin（§3.2 ①）。
	GetRoleByKey(ctx context.Context, arg GetRoleByKeyParams) (Role, error)
	// ⚠️ 「按 id 查一行」也带 tenant_id（MULTI-TENANCY.md §11.1）—— id 唯一不代表这一行是你的。
	GetServiceAccount(ctx context.Context, arg GetServiceAccountParams) (GetServiceAccountRow, error)
	// ---------------------------------------------------------------- Service Account
	// tenant-exempt: 和 GetLiveSession 同理 —— 拿 API Key 的 prefix 定位到一行，
	//   那一行才告诉我们它属于哪个租户。uk_service_accounts_prefix 也保持全平台唯一。
	//   租户状态同样要带上：机器身份也不能在停用的租户里继续跑（§8.2）。
	GetServiceAccountByPrefix(ctx context.Context, keyPrefix string) (GetServiceAccountByPrefixRow, error)
	GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error)
	// 租户本身（MULTI-TENANCY.md §2.1）。
	//
	// ⚠️ `tenants` 是**平台级**的表，它自己没有 tenant_id ——
	// 和 sessions / service_accounts 一样属于「只能靠代码自觉」的那三张（§3.2 ③）。
	// 原因是认证发生在租户上下文建立**之前**：登录时先拿公司代码来这张表找租户，
	// 那一刻还不知道租户是谁。**清单就这三张，加第四张要单独讨论。**
	//
	// 所以这里每一条都要写 `-- tenant-exempt:`，让 SQL 静态检查放行并留下理由。
	//
	// 平台管理端自己的租户查询在 platform.sql 里。这里放的是**认证链路和启动加载**
	// 要用的那几条 —— 它们不属于平台端，但同样只碰 tenants 这一张平台级表。
	// tenant-exempt: tenants 是平台级表，登录按公司代码找租户时还没有租户上下文
	// code 存的一律是小写（DB 有 CHECK 保证），查询侧 lower() 是为了用上 uk_tenants_code
	// 这个函数索引 —— 用户在登录框里敲 ACME 也要认得出来。
	GetTenantByCode(ctx context.Context, code string) (Tenant, error)
	// tenant-exempt: 同上
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	// ⚠️ 「按 id 查一行」也必须带 tenant_id（§11.1）—— 这是 OWASP API Top 10 第一名的 BOLA。
	// id 唯一不代表这一行是你的。
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	// 认证相关查询（DECISIONS.md §3、§6、§8.1）。
	//
	// ⚠️ 这个文件是整套租户隔离里**最需要小心**的地方（MULTI-TENANCY.md §3.2 ③）：
	// 认证发生在租户上下文建立**之前**。验证会话是「拿 cookie 里的 token 去查这是谁」，
	// 那一刻还不知道租户是谁；API Key 同理。所以查 sessions / service_accounts 的那几条
	// 只能靠代码自觉，标了 `-- tenant-exempt:`。**其余每一条都必须带 tenant_id。**
	// ---------------------------------------------------------------- 用户
	// 登录标识符：用户名 / 邮箱 / 手机号都行。**租户内**唯一 ——
	// 登录时先用公司代码查到租户，再拿租户 + 标识符查人。
	// 万一有人的用户名恰好等于另一个人的邮箱，优先按用户名匹配，结果才是确定的。
	GetUserByIdentifier(ctx context.Context, arg GetUserByIdentifierParams) (User, error)
	GetUserWithDepartment(ctx context.Context, arg GetUserWithDepartmentParams) (GetUserWithDepartmentRow, error)
	// 审计日志（DECISIONS.md §6）。只有写入和查询 —— 改和删在 DB 层就被禁了。
	//
	// ⚠️ audit_logs 的 tenant_id **可空**（MULTI-TENANCY.md §7.1）：未认证请求
	// （登录失败、健康检查、直接打接口）也要写审计，那些记录没有租户。
	// NULL = 平台级 / 无租户事件，只有平台端看得到。
	// 细节：公司代码有效、密码错误的登录失败要记在**那个租户名下**，客户才能看到
	// 「有人在爆破我们的账号」；只有公司代码本身无效时才记 NULL。
	// tenant-exempt: 写审计的中间件不是租户绑定的 —— 未认证请求也要写，那时 tenant_id 是 NULL。
	//   列里带着 tenant_id，租户归属由调用方显式传，不靠 ForTenant 注入。
	// prev_hash / hash 由触发器算，应用不传：应用能算就意味着应用能伪造。
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// InvalidatePendingRegistrationsByEmail 删掉同一邮箱之前没验证的记录 —— 重发验证信时先清旧的。
	// tenant-exempt: 同上，跨租户 infra 表
	InvalidatePendingRegistrationsByEmail(ctx context.Context, email string) error
	// InvalidateUserResetTokens 把某人还没用的 token 全标记成已用 —— 申请新的时先作废旧的，
	// 保证一个用户同时只有一条有效 token。
	InvalidateUserResetTokens(ctx context.Context, arg InvalidateUserResetTokensParams) error
	// 按写入顺序取出某个租户的哈希链，用来验完整性。链现在**每租户各一条**（§2.4）。
	ListAuditChain(ctx context.Context, tenantID uuid.UUID) ([]ListAuditChainRow, error)
	// resource / action 传的是 ILIKE 模式（`%li%`），由 repo.LikePattern 拼 ——
	// **别在这里拼 '%' || ... || '%'**，那样用户输入的 % 和 _ 就成了通配符。
	//
	// tenant_id = ? 是等值条件，NULL 的那批（平台级事件）自然落不进来 —— 这是想要的。
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	// 取一个节点和它所有后代的 id。改父节点时用来挡「把自己挂到自己的子孙下面」——
	// 那会造出一个从树上断开的环，整棵树直接查不出来。
	//
	// ⚠️ **递归那一半也要带 tenant_id**（§10.7）。种子那半带了就完事，是最容易漏的一处：
	// 递归部分只靠 parent_id 关联，看着「跟着种子走自然就在租户里」。
	// 复合外键确实保证了不会有跨租户的父子关系，所以实际泄不了 —— 但这里要的是**纵深防御**：
	// 不依赖另一个约束的正确性。SQL 静态检查也会拦下不带租户条件的那一半。
	ListDepartmentSubtreeIDs(ctx context.Context, arg ListDepartmentSubtreeIDsParams) ([]uuid.UUID, error)
	// 部门（DECISIONS.md §2）。
	// 部门是树，**一次全取**：内部系统撑死几百个节点，分页反而会把树切断。
	// 排序保证同一个父下按 sort_order，前端拼树时不用再排一遍。
	ListDepartments(ctx context.Context, arg ListDepartmentsParams) ([]ListDepartmentsRow, error)
	// tenant-exempt: 平台级事件（未认证请求）的那条链，tenant_id 就是 NULL ——
	//   它不属于任何租户，按定义就带不了租户条件。只有平台管理端查得到。
	//
	// 单独一条查询而不是在 ListAuditChain 里 coalesce：
	//   1. 那样 ListAuditChain 用不上 (tenant_id, occurred_at) 索引
	//   2. 更要紧的是，coalesce 版本要传全零哨兵 UUID 才能取到平台链，
	//      而 ForTenant 现在拒绝零值租户（零值只该来自 bug）。两件事分开各走各的路。
	ListPlatformAuditChain(ctx context.Context) ([]ListPlatformAuditChainRow, error)
	// 平台管理端（MULTI-TENANCY.md §6、第 ⑤ 步）+ 平台级配置（§7.2）。
	//
	// ⚠️ **这个文件里的查询只许碰四张平台级表**：
	// `tenants` / `platform_admins` / `platform_sessions` / `platform_settings`。
	//
	// 这不是口头约定：生成器按「引用的表全在平台级清单里」把它们分流到
	// `Store.Platform()` 那个句柄上，平台服务**结构上就够不到业务表**。
	// 哪天有人在这里写一条 `SELECT ... FROM users`，这条查询会掉到别的句柄上，
	// 平台服务编译不过。
	//
	// 为什么这么在意：一旦平台端能查 users，「平台端结构上碰不到客户业务数据」
	// 这个性质就没了 —— 而那句话是将来跟客户解释隔离时最有力的一句（§10.11）。
	// 「租户列表要显示人数」这个需求就是靠 tenants.user_count 冗余绕开的，不是靠 join。
	// ---------------------------------------------------------------- 平台级配置
	// tenant-exempt: platform_settings 是平台级表，没有 tenant_id 这一列
	ListPlatformSettings(ctx context.Context) ([]ListPlatformSettingsRow, error)
	ListRoleIDsOfUser(ctx context.Context, arg ListRoleIDsOfUserParams) ([]uuid.UUID, error)
	ListRolePermissions(ctx context.Context, arg ListRolePermissionsParams) ([]ListRolePermissionsRow, error)
	// 下面三个查询喂给 Casbin：策略加载进内存，变更靠 LISTEN/NOTIFY 触发重载。
	//
	// 都带上了 tenant_id —— 加载方按租户逐个加载。Casbin 的 **domain 模型已经落地**：
	// 策略和角色绑定都以 tenant_id 作为 domain 写进 enforcer（authz/checker.go 的 Reload），
	// 所以两个租户的同名角色 key 不会串。判定侧没有租户（TenantID 为 Nil）一律拒绝。
	ListRolePolicies(ctx context.Context, tenantID uuid.UUID) ([]ListRolePoliciesRow, error)
	// 角色管理（DECISIONS.md §3）。
	//
	// Casbin 用的那几个策略查询在 auth.sql 里，别混在一起：
	// 那些是**认证链路**用的（加载进内存），这里是**管理页面**用的。
	//
	// 角色的 key 现在是**租户内**唯一：每家公司各有一个自己的内置 admin（§3.2 ①）。
	// 子查询里的 count 也要带租户 —— 少一处就会把别家公司的人数算进来。
	ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error)
	ListRolesByIDs(ctx context.Context, arg ListRolesByIDsParams) ([]Role, error)
	ListRolesOfUser(ctx context.Context, arg ListRolesOfUserParams) ([]Role, error)
	ListServiceAccountRoleBindings(ctx context.Context, tenantID uuid.UUID) ([]ListServiceAccountRoleBindingsRow, error)
	// Service Account（机器身份）管理（DECISIONS.md §8.1）。
	//
	// 🔴 **这个文件里的查询一律不返回 `key_hash`。**
	// 所以每条都写明列名，不用 `SELECT *` —— 加一列的时候 `*` 会把新列自动带出去，
	// 而这张表上「不该出去的列」正是它的核心资产。密钥只在新建和轮换时以明文返回一次，
	// 之后库里只有哈希，谁都取不回来。
	//
	// ⚠️ 认证链路用的那两条（按 prefix 定位、写 last_used_at）在 auth.sql 里，别混：
	// 那条按 prefix 查的是**不带租户条件**的（认证发生在租户上下文之前，§3.2 ③），
	// 而这里每一条都必须带租户。
	ListServiceAccounts(ctx context.Context, arg ListServiceAccountsParams) ([]ListServiceAccountsRow, error)
	// 配置的第二层：可在后台改、改完立即生效（DECISIONS.md §5）。
	//
	// 多租户之后 settings 是**租户级**的（主键 `(tenant_id, key)`，MULTI-TENANCY.md §7.2）：
	// 密码策略、会话超时每家公司自己定。平台级的那些（是否允许自助注册、租户设置的上下界）
	// 在 platform_settings 里，不走这里。
	ListSettings(ctx context.Context, tenantID uuid.UUID) ([]ListSettingsRow, error)
	// 供应商（supplier）的 CRUD 查询。由 fries-gen 生成。
	// Code generated by fries-gen. DO NOT EDIT.
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	// tenant-exempt: 同上。加载权限策略、加载各租户配置都要遍历租户
	//
	// ⚠️ **不要按 status 过滤。** 这里曾经写的是 `WHERE status = 'active'`，
	// 结果是：停用一个租户 → 下次刷新策略时它的权限从 enforcer 里消失 →
	// 重新启用之后**没有任何东西会触发重载**（authz_changed 只在角色相关的表上有触发器），
	// 那家公司的人能登录但**每个请求都 403**，只能重启服务或者随便改个角色才恢复。
	//
	// 停用的租户根本认证不过去（认证时会核 tenants.status），
	// 所以把它们的策略留在内存里没有任何风险，反而省掉一整类「状态没跟上」的问题。
	ListTenants(ctx context.Context) ([]Tenant, error)
	// ---------------------------------------------------------------- 租户
	// tenant-exempt: tenants 是平台级表。这是平台端的租户列表 ——
	//   人数走 tenants.user_count 冗余列，**不 join users**（§6）
	ListTenantsForPlatform(ctx context.Context, arg ListTenantsForPlatformParams) ([]Tenant, error)
	ListUserRoleBindings(ctx context.Context, tenantID uuid.UUID) ([]ListUserRoleBindingsRow, error)
	// 用户管理（DECISIONS.md §3、§6）。
	//
	// 登录链路用的那几个查询在 auth.sql 里，别混：那些是**认证**用的，
	// 这里是**管理页面**用的。
	//
	// ⚠️ 这个文件里**每一条**都必须带 tenant_id，包括「按 id 改一行」的那些（§11.1）：
	// 按 id 更新时最容易觉得「id 是唯一的，够了」—— 不够，那是 BOLA。
	// 跨租户测试会拿 A 的上下文去 update/delete B 的 id，影响行数必须是 0（§10.8）。
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	// 「添加成员」候选：不在这个部门里的人。department_id 传 NULL 表示「不在任何部门的人」。
	ListUsersNotInDepartment(ctx context.Context, arg ListUsersNotInDepartmentParams) ([]ListUsersNotInDepartmentRow, error)
	MarkLoginFailure(ctx context.Context, arg MarkLoginFailureParams) (MarkLoginFailureRow, error)
	MarkLoginSuccess(ctx context.Context, arg MarkLoginSuccessParams) error
	// MarkPasswordResetTokenUsed **原子认领**一条 token：只有还没被用的才标记成功、返回 1 行。
	// 改密前先认领，认领到 0 行说明并发里别人已经用掉了 —— 保证一次性、防 TOCTOU 重用。
	MarkPasswordResetTokenUsed(ctx context.Context, arg MarkPasswordResetTokenUsedParams) (int64, error)
	// tenant-exempt: 同上
	MarkPlatformLoginFailure(ctx context.Context, arg MarkPlatformLoginFailureParams) (MarkPlatformLoginFailureRow, error)
	// tenant-exempt: 同上
	MarkPlatformLoginSuccess(ctx context.Context, id uuid.UUID) error
	// 管理员重置密码：**一定要 must_change_password = true** ——
	// 临时密码经过了管理员的手，本人必须马上换掉。
	ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (int64, error)
	// tenant-exempt: 同上。改密码之后把其它会话全踢掉，只留当前这条
	RevokeOtherPlatformSessions(ctx context.Context, arg RevokeOtherPlatformSessionsParams) error
	// 改密码之后用：把这个人的其它会话全踢掉，只留当前这条。
	RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) error
	// tenant-exempt: 同上
	RevokePlatformSession(ctx context.Context, id uuid.UUID) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeUserSessions(ctx context.Context, arg RevokeUserSessionsParams) error
	// 换一副新密钥，记录本身不动。
	//
	// 泄露之后要的就是这个：对接方换一串新的继续跑，不用重建记录、不用重配权限。
	// 旧密钥当场失效 —— 认证是按 key_prefix 定位的，prefix 一换，旧的那串谁也对不上。
	RotateServiceAccountKey(ctx context.Context, arg RotateServiceAccountKeyParams) (int64, error)
	// tenant-exempt: 同上
	SetPlatformAdminPassword(ctx context.Context, arg SetPlatformAdminPasswordParams) error
	// tenant-exempt: 同上。租户只停用不删除（§9.3）—— 没有删除语句是有意的
	SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	// 批量调整部门归属。department_id 传 NULL 就是移出部门。
	// **不动 version**：调部门是管理动作，不该让正在编辑这个人的另一个页面撞版本冲突。
	//
	// ⚠️ 批量按 id 改是 BOLA 的重灾区：不带 tenant_id 的话，传一串别家公司的 user_id
	// 就能把人从他们的部门里摘出来。影响行数会如实返回，也就成了一个存在性探针。
	SetUsersDepartment(ctx context.Context, arg SetUsersDepartmentParams) (int64, error)
	SoftDeleteDepartment(ctx context.Context, arg SoftDeleteDepartmentParams) (uuid.UUID, error)
	SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) (uuid.UUID, error)
	SoftDeleteServiceAccount(ctx context.Context, arg SoftDeleteServiceAccountParams) (uuid.UUID, error)
	SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierParams) (int64, error)
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (uuid.UUID, error)
	// tenant-exempt: 同上
	TouchPlatformSession(ctx context.Context, id uuid.UUID) error
	TouchServiceAccount(ctx context.Context, arg TouchServiceAccountParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	// 乐观锁：影响 0 行说明版本对不上，service 层翻成 common.version_conflict（§2.4）
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	// username 不给改：它是登录标识，也是审计里认人的依据。
	// 改了之后老审计记录指向的那个人就对不上了。
	UpdateManagedUser(ctx context.Context, arg UpdateManagedUserParams) (User, error)
	// key 不给改：它是 Casbin 策略里的标识，改了等于换了一个角色，
	// 而已经发出去的会话还带着老 key。要换就新建一个。
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	// 乐观锁：影响 0 行说明版本对不上，service 层翻成 common.version_conflict。
	//
	// ⚠️ **key_prefix / key_hash 不在这里改** —— 换密钥是另一个动作、另一个权限点，
	// 走 RotateServiceAccountKey。混在一起的话，「改个描述」和「作废对接方手里的凭据」
	// 就成了同一个按钮。
	UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) (UpdateServiceAccountRow, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	// tenant-exempt: 同上
	UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
