// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rate_limits.sql

package sqlcgen

import (
	"context"
	"time"
)

const bumpRateLimit = `-- name: BumpRateLimit :one

INSERT INTO rate_limits (key, window_start, count)
VALUES ($1, $2, 1)
ON CONFLICT (key, window_start) DO UPDATE
    SET count = rate_limits.count + 1
RETURNING count
`

type BumpRateLimitParams struct {
	Key         string
	WindowStart time.Time
}

// 限流器的持久化存储（SCALING.md §1）。表没有 tenant_id（维度已拼进 key），
// 跨租户 infra 表，走 Unscoped 句柄。豁免注释写在 `-- name:` 之后（SplitQueries 按此归属）。
// BumpRateLimit 原子地把 (key, 当前窗口) 的计数 +1，返回加完之后的值。
// 靠一条 INSERT ... ON CONFLICT DO UPDATE 完成，多副本并发自增不会丢。
// tenant-exempt: rate_limits 是跨租户 infra 表，没有 tenant_id（维度已拼进 key）
func (q *Queries) BumpRateLimit(ctx context.Context, arg BumpRateLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, bumpRateLimit, arg.Key, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const deleteOldRateLimits = `-- name: DeleteOldRateLimits :execrows
DELETE FROM rate_limits WHERE window_start < $1
`

// DeleteOldRateLimits 清掉早于 cutoff 的窗口，后台任务定时调。
// tenant-exempt: 清旧窗口的后台任务，跨租户一次扫描
func (q *Queries) DeleteOldRateLimits(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldRateLimits, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
