// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addRolePermission = `-- name: AddRolePermission :exec
INSERT INTO role_permissions (tenant_id, role_id, resource, action)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddRolePermissionParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
	Resource string
	Action   string
}

func (q *Queries) AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error {
	_, err := q.db.Exec(ctx, addRolePermission,
		arg.TenantID,
		arg.RoleID,
		arg.Resource,
		arg.Action,
	)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions
WHERE tenant_id = $1 AND role_id = $2
`

type ClearRolePermissionsParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) ClearRolePermissions(ctx context.Context, arg ClearRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, arg.TenantID, arg.RoleID)
	return err
}

const countRoleServiceAccounts = `-- name: CountRoleServiceAccounts :one
SELECT count(*) FROM service_accounts
WHERE tenant_id = $1 AND role_id = $2 AND deleted_at IS NULL
`

type CountRoleServiceAccountsParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) CountRoleServiceAccounts(ctx context.Context, arg CountRoleServiceAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleServiceAccounts, arg.TenantID, arg.RoleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoleUsers = `-- name: CountRoleUsers :one
SELECT count(*) FROM user_roles
WHERE tenant_id = $1 AND role_id = $2
`

type CountRoleUsersParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

func (q *Queries) CountRoleUsers(ctx context.Context, arg CountRoleUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleUsers, arg.TenantID, arg.RoleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoles = `-- name: CountRoles :one
SELECT count(*) FROM roles r
WHERE r.tenant_id = $1
  AND r.deleted_at IS NULL
  AND ($2::varchar IS NULL
       OR r.name ILIKE $2 OR r.key ILIKE $2)
  AND ($3::varchar IS NULL OR r.status = $3)
`

type CountRolesParams struct {
	TenantID uuid.UUID
	Keyword  *string
	Status   *string
}

func (q *Queries) CountRoles(ctx context.Context, arg CountRolesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles, arg.TenantID, arg.Keyword, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuiltinAdminRole = `-- name: CreateBuiltinAdminRole :one
INSERT INTO roles (tenant_id, id, key, name, description, data_scope, status, builtin)
VALUES ($1, $2,
        'admin', '超级管理员', '拥有全部权限，内置角色不可删除', 'all', 'active', true)
RETURNING id, key, name, description, data_scope, builtin, status, created_at, updated_at, deleted_at, created_by, version, tenant_id
`

type CreateBuiltinAdminRoleParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// 开组织时给新组织建它自己的内置 admin 角色（MULTI-TENANCY.md §3.2 ①）。
//
// 和 CreateRole 分开是因为**只有这条能设 builtin = true**：
// 管理页面新建出来的一律是普通角色，内置角色只由「开组织」这条链路建。
// 内置角色不可改不可删，是权限体系的兜底 —— 它被谁随手建出来都不行。
func (q *Queries) CreateBuiltinAdminRole(ctx context.Context, arg CreateBuiltinAdminRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createBuiltinAdminRole, arg.TenantID, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.DataScope,
		&i.Builtin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.TenantID,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (tenant_id, id, key, name, description, data_scope, status, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8)
RETURNING id, key, name, description, data_scope, builtin, status, created_at, updated_at, deleted_at, created_by, version, tenant_id
`

type CreateRoleParams struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	DataScope   string
	Status      string
	CreatedBy   *uuid.UUID
}

// builtin 不给传：内置角色只由「开租户」那条链路建（第 ⑤ 步），
// 管理页面新建出来的一律是普通角色。
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.TenantID,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.DataScope,
		arg.Status,
		arg.CreatedBy,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.DataScope,
		&i.Builtin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.TenantID,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT r.id, r.key, r.name, r.description, r.data_scope, r.builtin, r.status, r.created_at, r.updated_at, r.deleted_at, r.created_by, r.version, r.tenant_id,
       (SELECT count(*) FROM user_roles ur
        WHERE ur.tenant_id = r.tenant_id AND ur.role_id = r.id)       AS user_count,
       (SELECT count(*) FROM role_permissions rp
        WHERE rp.tenant_id = r.tenant_id AND rp.role_id = r.id)       AS permission_count
FROM roles r
WHERE r.tenant_id = $1 AND r.id = $2 AND r.deleted_at IS NULL
`

type GetRoleParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetRoleRow struct {
	ID              uuid.UUID
	Key             string
	Name            string
	Description     string
	DataScope       string
	Builtin         bool
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
	CreatedBy       *uuid.UUID
	Version         int32
	TenantID        uuid.UUID
	UserCount       int64
	PermissionCount int64
}

// 计数和 ListRoles 保持一致 —— 详情页要显示「有多少人在用这个角色」，
// 少一个 user_count 就会显示成「还没有人用」，而列表上明明写着 2 个人。
// 同一个字段两个接口说法不一样，比不显示还糟。
func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (GetRoleRow, error) {
	row := q.db.QueryRow(ctx, getRole, arg.TenantID, arg.ID)
	var i GetRoleRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.DataScope,
		&i.Builtin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.TenantID,
		&i.UserCount,
		&i.PermissionCount,
	)
	return i, err
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT resource, action FROM role_permissions
WHERE tenant_id = $1 AND role_id = $2
ORDER BY resource, action
`

type ListRolePermissionsParams struct {
	TenantID uuid.UUID
	RoleID   uuid.UUID
}

type ListRolePermissionsRow struct {
	Resource string
	Action   string
}

func (q *Queries) ListRolePermissions(ctx context.Context, arg ListRolePermissionsParams) ([]ListRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, arg.TenantID, arg.RoleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolePermissionsRow{}
	for rows.Next() {
		var i ListRolePermissionsRow
		if err := rows.Scan(&i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many

SELECT r.id, r.key, r.name, r.description, r.data_scope, r.builtin, r.status, r.created_at, r.updated_at, r.deleted_at, r.created_by, r.version, r.tenant_id,
       (SELECT count(*) FROM user_roles ur
        WHERE ur.tenant_id = r.tenant_id AND ur.role_id = r.id)       AS user_count,
       (SELECT count(*) FROM role_permissions rp
        WHERE rp.tenant_id = r.tenant_id AND rp.role_id = r.id)       AS permission_count
FROM roles r
WHERE r.tenant_id = $1
  AND r.deleted_at IS NULL
  AND ($2::varchar IS NULL
       OR r.name ILIKE $2 OR r.key ILIKE $2)
  AND ($3::varchar IS NULL OR r.status = $3)
ORDER BY r.builtin DESC, r.key
LIMIT $5 OFFSET $4
`

type ListRolesParams struct {
	TenantID uuid.UUID
	Keyword  *string
	Status   *string
	Offset   int32
	Limit    int32
}

type ListRolesRow struct {
	ID              uuid.UUID
	Key             string
	Name            string
	Description     string
	DataScope       string
	Builtin         bool
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       *time.Time
	CreatedBy       *uuid.UUID
	Version         int32
	TenantID        uuid.UUID
	UserCount       int64
	PermissionCount int64
}

// 角色管理（DECISIONS.md §3）。
//
// Casbin 用的那几个策略查询在 auth.sql 里，别混在一起：
// 那些是**认证链路**用的（加载进内存），这里是**管理页面**用的。
//
// 角色的 key 现在是**租户内**唯一：每家公司各有一个自己的内置 admin（§3.2 ①）。
// 子查询里的 count 也要带租户 —— 少一处就会把别家公司的人数算进来。
func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles,
		arg.TenantID,
		arg.Keyword,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.DataScope,
			&i.Builtin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.Version,
			&i.TenantID,
			&i.UserCount,
			&i.PermissionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :one
UPDATE roles
SET deleted_at = now(), version = version + 1
WHERE tenant_id = $1
  AND id = $2
  AND version = $3
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteRoleParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Version  int32
}

func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteRole, arg.TenantID, arg.ID, arg.Version)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name        = $1,
    description = $2,
    data_scope  = $3,
    status      = $4,
    version     = version + 1
WHERE tenant_id = $5
  AND id = $6
  AND version = $7
  AND deleted_at IS NULL
RETURNING id, key, name, description, data_scope, builtin, status, created_at, updated_at, deleted_at, created_by, version, tenant_id
`

type UpdateRoleParams struct {
	Name        string
	Description string
	DataScope   string
	Status      string
	TenantID    uuid.UUID
	ID          uuid.UUID
	Version     int32
}

// key 不给改：它是 Casbin 策略里的标识，改了等于换了一个角色，
// 而已经发出去的会话还带着老 key。要换就新建一个。
func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Description,
		arg.DataScope,
		arg.Status,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.DataScope,
		&i.Builtin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.TenantID,
	)
	return i, err
}
