// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_account.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countServiceAccounts = `-- name: CountServiceAccounts :one
SELECT count(*) FROM service_accounts sa
WHERE sa.tenant_id = $1
  AND sa.deleted_at IS NULL
  AND ($2::varchar IS NULL
       OR sa.name ILIKE $2
       OR sa.description ILIKE $2)
  AND ($3::varchar IS NULL OR sa.status = $3)
`

type CountServiceAccountsParams struct {
	TenantID uuid.UUID
	Keyword  *string
	Status   *string
}

func (q *Queries) CountServiceAccounts(ctx context.Context, arg CountServiceAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServiceAccounts, arg.TenantID, arg.Keyword, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO service_accounts (tenant_id, id, name, description, key_prefix, key_hash,
                              role_id, status, expires_at, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10)
RETURNING id, name, description, key_prefix, role_id, status, expires_at, created_at, version
`

type CreateServiceAccountParams struct {
	TenantID    uuid.UUID
	ID          uuid.UUID
	Name        string
	Description string
	KeyPrefix   string
	KeyHash     []byte
	RoleID      uuid.UUID
	Status      string
	ExpiresAt   *time.Time
	CreatedBy   *uuid.UUID
}

type CreateServiceAccountRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	KeyPrefix   string
	RoleID      uuid.UUID
	Status      string
	ExpiresAt   *time.Time
	CreatedAt   time.Time
	Version     int32
}

// 返回的行同样不含 key_hash：明文密钥在应用侧，调用方手里已经有了，
// 不需要也不该从这里再拿一次。
func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (CreateServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, createServiceAccount,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.RoleID,
		arg.Status,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i CreateServiceAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyPrefix,
		&i.RoleID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const getServiceAccount = `-- name: GetServiceAccount :one
SELECT sa.id, sa.name, sa.description, sa.key_prefix, sa.role_id,
       r.name AS role_name, sa.status, sa.expires_at, sa.last_used_at,
       sa.created_at, sa.version
FROM service_accounts sa
JOIN roles r ON r.id = sa.role_id AND r.tenant_id = sa.tenant_id
WHERE sa.tenant_id = $1 AND sa.id = $2
  AND sa.deleted_at IS NULL
`

type GetServiceAccountParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetServiceAccountRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	KeyPrefix   string
	RoleID      uuid.UUID
	RoleName    string
	Status      string
	ExpiresAt   *time.Time
	LastUsedAt  *time.Time
	CreatedAt   time.Time
	Version     int32
}

// ⚠️ 「按 id 查一行」也带 tenant_id（MULTI-TENANCY.md §11.1）—— id 唯一不代表这一行是你的。
func (q *Queries) GetServiceAccount(ctx context.Context, arg GetServiceAccountParams) (GetServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, getServiceAccount, arg.TenantID, arg.ID)
	var i GetServiceAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyPrefix,
		&i.RoleID,
		&i.RoleName,
		&i.Status,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}

const listServiceAccounts = `-- name: ListServiceAccounts :many

SELECT sa.id, sa.name, sa.description, sa.key_prefix, sa.role_id,
       r.name AS role_name, sa.status, sa.expires_at, sa.last_used_at,
       sa.created_at, sa.version
FROM service_accounts sa
JOIN roles r ON r.id = sa.role_id AND r.tenant_id = sa.tenant_id
WHERE sa.tenant_id = $1
  AND sa.deleted_at IS NULL
  AND ($2::varchar IS NULL
       OR sa.name ILIKE $2
       OR sa.description ILIKE $2)
  AND ($3::varchar IS NULL OR sa.status = $3)
ORDER BY sa.created_at DESC, sa.id DESC
LIMIT $5 OFFSET $4
`

type ListServiceAccountsParams struct {
	TenantID uuid.UUID
	Keyword  *string
	Status   *string
	Offset   int32
	Limit    int32
}

type ListServiceAccountsRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	KeyPrefix   string
	RoleID      uuid.UUID
	RoleName    string
	Status      string
	ExpiresAt   *time.Time
	LastUsedAt  *time.Time
	CreatedAt   time.Time
	Version     int32
}

// Service Account（机器身份）管理（DECISIONS.md §8.1）。
//
// 🔴 **这个文件里的查询一律不返回 `key_hash`。**
// 所以每条都写明列名，不用 `SELECT *` —— 加一列的时候 `*` 会把新列自动带出去，
// 而这张表上「不该出去的列」正是它的核心资产。密钥只在新建和轮换时以明文返回一次，
// 之后库里只有哈希，谁都取不回来。
//
// ⚠️ 认证链路用的那两条（按 prefix 定位、写 last_used_at）在 auth.sql 里，别混：
// 那条按 prefix 查的是**不带租户条件**的（认证发生在租户上下文之前，§3.2 ③），
// 而这里每一条都必须带租户。
func (q *Queries) ListServiceAccounts(ctx context.Context, arg ListServiceAccountsParams) ([]ListServiceAccountsRow, error) {
	rows, err := q.db.Query(ctx, listServiceAccounts,
		arg.TenantID,
		arg.Keyword,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceAccountsRow{}
	for rows.Next() {
		var i ListServiceAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.KeyPrefix,
			&i.RoleID,
			&i.RoleName,
			&i.Status,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateServiceAccountKey = `-- name: RotateServiceAccountKey :execrows
UPDATE service_accounts
SET key_prefix = $1,
    key_hash   = $2,
    version    = version + 1
WHERE tenant_id = $3 AND id = $4 AND deleted_at IS NULL
`

type RotateServiceAccountKeyParams struct {
	KeyPrefix string
	KeyHash   []byte
	TenantID  uuid.UUID
	ID        uuid.UUID
}

// 换一副新密钥，记录本身不动。
//
// 泄露之后要的就是这个：对接方换一串新的继续跑，不用重建记录、不用重配权限。
// 旧密钥当场失效 —— 认证是按 key_prefix 定位的，prefix 一换，旧的那串谁也对不上。
func (q *Queries) RotateServiceAccountKey(ctx context.Context, arg RotateServiceAccountKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateServiceAccountKey,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteServiceAccount = `-- name: SoftDeleteServiceAccount :one
UPDATE service_accounts
SET deleted_at = now(), version = version + 1
WHERE tenant_id = $1
  AND id = $2
  AND version = $3
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteServiceAccountParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Version  int32
}

func (q *Queries) SoftDeleteServiceAccount(ctx context.Context, arg SoftDeleteServiceAccountParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteServiceAccount, arg.TenantID, arg.ID, arg.Version)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateServiceAccount = `-- name: UpdateServiceAccount :one
UPDATE service_accounts
SET name        = $1,
    description = $2,
    role_id     = $3,
    status      = $4,
    expires_at  = $5,
    version     = version + 1
WHERE tenant_id = $6
  AND id = $7
  AND version = $8
  AND deleted_at IS NULL
RETURNING id, name, description, key_prefix, role_id, status, expires_at, created_at, version
`

type UpdateServiceAccountParams struct {
	Name        string
	Description string
	RoleID      uuid.UUID
	Status      string
	ExpiresAt   *time.Time
	TenantID    uuid.UUID
	ID          uuid.UUID
	Version     int32
}

type UpdateServiceAccountRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	KeyPrefix   string
	RoleID      uuid.UUID
	Status      string
	ExpiresAt   *time.Time
	CreatedAt   time.Time
	Version     int32
}

// 乐观锁：影响 0 行说明版本对不上，service 层翻成 common.version_conflict。
//
// ⚠️ **key_prefix / key_hash 不在这里改** —— 换密钥是另一个动作、另一个权限点，
// 走 RotateServiceAccountKey。混在一起的话，「改个描述」和「作废对接方手里的凭据」
// 就成了同一个按钮。
func (q *Queries) UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountParams) (UpdateServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, updateServiceAccount,
		arg.Name,
		arg.Description,
		arg.RoleID,
		arg.Status,
		arg.ExpiresAt,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var i UpdateServiceAccountRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.KeyPrefix,
		&i.RoleID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Version,
	)
	return i, err
}
