// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const listSettings = `-- name: ListSettings :many

SELECT key, value FROM settings
WHERE tenant_id = $1
ORDER BY key
`

type ListSettingsRow struct {
	Key   string
	Value []byte
}

// 配置的第二层：可在后台改、改完立即生效（DECISIONS.md §5）。
//
// 多租户之后 settings 是**租户级**的（主键 `(tenant_id, key)`，MULTI-TENANCY.md §7.2）：
// 密码策略、会话超时每家公司自己定。平台级的那些（是否允许自助注册、租户设置的上下界）
// 在 platform_settings 里，不走这里。
func (q *Queries) ListSettings(ctx context.Context, tenantID uuid.UUID) ([]ListSettingsRow, error) {
	rows, err := q.db.Query(ctx, listSettings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSettingsRow{}
	for rows.Next() {
		var i ListSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (tenant_id, key, value, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, key) DO UPDATE
SET value = excluded.value, updated_by = excluded.updated_by
`

type UpsertSettingParams struct {
	TenantID  uuid.UUID
	Key       string
	Value     []byte
	UpdatedBy *uuid.UUID
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting,
		arg.TenantID,
		arg.Key,
		arg.Value,
		arg.UpdatedBy,
	)
	return err
}
