// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplier.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countSuppliers = `-- name: CountSuppliers :one
SELECT count(*) FROM suppliers
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($2::varchar IS NULL OR name ILIKE $2)
  AND ($3::varchar IS NULL OR status = $3)
  AND ($4::date IS NULL OR started_at = $4)
`

type CountSuppliersParams struct {
	TenantID  uuid.UUID
	Keyword   *string
	Status    *string
	StartedAt *time.Time
}

func (q *Queries) CountSuppliers(ctx context.Context, arg CountSuppliersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers,
		arg.TenantID,
		arg.Keyword,
		arg.Status,
		arg.StartedAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (tenant_id, id, name, status, credit, started_at, remark, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, name, status, credit, started_at, remark, created_at, updated_at, deleted_at, created_by, version
`

type CreateSupplierParams struct {
	TenantID  uuid.UUID
	ID        uuid.UUID
	Name      string
	Status    *string
	Credit    *decimal.Decimal
	StartedAt *time.Time
	Remark    *string
	CreatedBy *uuid.UUID
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.Credit,
		arg.StartedAt,
		arg.Remark,
		arg.CreatedBy,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Credit,
		&i.StartedAt,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, tenant_id, name, status, credit, started_at, remark, created_at, updated_at, deleted_at, created_by, version FROM suppliers
WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetSupplierParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, arg.TenantID, arg.ID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Credit,
		&i.StartedAt,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many

SELECT id, tenant_id, name, status, credit, started_at, remark, created_at, updated_at, deleted_at, created_by, version FROM suppliers
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND ($2::varchar IS NULL OR name ILIKE $2)
  AND ($3::varchar IS NULL OR status = $3)
  AND ($4::date IS NULL OR started_at = $4)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListSuppliersParams struct {
	TenantID  uuid.UUID
	Keyword   *string
	Status    *string
	StartedAt *time.Time
	Offset    int32
	Limit     int32
}

// 供应商（supplier）的 CRUD 查询。由 fries-gen 生成。
// Code generated by fries-gen. DO NOT EDIT.
func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers,
		arg.TenantID,
		arg.Keyword,
		arg.Status,
		arg.StartedAt,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.Credit,
			&i.StartedAt,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSupplier = `-- name: SoftDeleteSupplier :execrows
UPDATE suppliers
SET deleted_at = now(), version = version + 1
WHERE tenant_id = $1
  AND id = $2
  AND version = $3
  AND deleted_at IS NULL
`

type SoftDeleteSupplierParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Version  int32
}

func (q *Queries) SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteSupplier, arg.TenantID, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name = $1,
    status = $2,
    credit = $3,
    started_at = $4,
    remark = $5,
    version = version + 1
WHERE tenant_id = $6
  AND id = $7
  AND version = $8
  AND deleted_at IS NULL
RETURNING id, tenant_id, name, status, credit, started_at, remark, created_at, updated_at, deleted_at, created_by, version
`

type UpdateSupplierParams struct {
	Name      string
	Status    *string
	Credit    *decimal.Decimal
	StartedAt *time.Time
	Remark    *string
	TenantID  uuid.UUID
	ID        uuid.UUID
	Version   int32
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.Name,
		arg.Status,
		arg.Credit,
		arg.StartedAt,
		arg.Remark,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Status,
		&i.Credit,
		&i.StartedAt,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
	)
	return i, err
}
