// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenant.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, code, name, status, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, status, created_at, updated_at, created_by, version, user_count
`

type CreateTenantParams struct {
	ID        uuid.UUID
	Code      string
	Name      string
	Status    string
	CreatedBy *uuid.UUID
}

// tenant-exempt: 同上
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.CreatedBy,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Version,
		&i.UserCount,
	)
	return i, err
}

const getTenantByCode = `-- name: GetTenantByCode :one

SELECT id, code, name, status, created_at, updated_at, created_by, version, user_count FROM tenants WHERE lower(code) = lower($1::text)
`

// 租户本身（MULTI-TENANCY.md §2.1）。
//
// ⚠️ `tenants` 是**平台级**的表，它自己没有 tenant_id ——
// 和 sessions / service_accounts 一样属于「只能靠代码自觉」的那三张（§3.2 ③）。
// 原因是认证发生在租户上下文建立**之前**：登录时先拿公司代码来这张表找租户，
// 那一刻还不知道租户是谁。**清单就这三张，加第四张要单独讨论。**
//
// 所以这里每一条都要写 `-- tenant-exempt:`，让 SQL 静态检查放行并留下理由。
//
// 平台管理端自己的租户查询在 platform.sql 里。这里放的是**认证链路和启动加载**
// 要用的那几条 —— 它们不属于平台端，但同样只碰 tenants 这一张平台级表。
// tenant-exempt: tenants 是平台级表，登录按公司代码找租户时还没有租户上下文
// code 存的一律是小写（DB 有 CHECK 保证），查询侧 lower() 是为了用上 uk_tenants_code
// 这个函数索引 —— 用户在登录框里敲 ACME 也要认得出来。
func (q *Queries) GetTenantByCode(ctx context.Context, code string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByCode, code)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Version,
		&i.UserCount,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, code, name, status, created_at, updated_at, created_by, version, user_count FROM tenants WHERE id = $1
`

// tenant-exempt: 同上
func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.Version,
		&i.UserCount,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, code, name, status, created_at, updated_at, created_by, version, user_count FROM tenants ORDER BY code
`

// tenant-exempt: 同上。加载权限策略、加载各租户配置都要遍历租户
//
// ⚠️ **不要按 status 过滤。** 这里曾经写的是 `WHERE status = 'active'`，
// 结果是：停用一个租户 → 下次刷新策略时它的权限从 enforcer 里消失 →
// 重新启用之后**没有任何东西会触发重载**（authz_changed 只在角色相关的表上有触发器），
// 那家公司的人能登录但**每个请求都 403**，只能重启服务或者随便改个角色才恢复。
//
// 停用的租户根本认证不过去（认证时会核 tenants.status），
// 所以把它们的策略留在内存里没有任何风险，反而省掉一整类「状态没跟上」的问题。
func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.Version,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
