// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const clearUserRoles = `-- name: ClearUserRoles :exec
DELETE FROM user_roles
WHERE tenant_id = $1 AND user_id = $2
`

type ClearUserRolesParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ClearUserRoles(ctx context.Context, arg ClearUserRolesParams) error {
	_, err := q.db.Exec(ctx, clearUserRoles, arg.TenantID, arg.UserID)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(DISTINCT u.id)
FROM users u
JOIN user_roles ur ON ur.user_id = u.id AND ur.tenant_id = u.tenant_id
JOIN roles r ON r.id = ur.role_id AND r.tenant_id = ur.tenant_id
JOIN role_permissions rp ON rp.role_id = r.id AND rp.tenant_id = r.tenant_id
WHERE u.tenant_id = $1
  AND u.deleted_at IS NULL AND u.status = 'active'
  AND r.deleted_at IS NULL AND r.status = 'active'
  AND rp.resource = '*' AND rp.action = '*'
  AND u.id <> $2::uuid
`

type CountActiveAdminsParams struct {
	TenantID      uuid.UUID
	ExcludeUserID uuid.UUID
}

// 还有几个「启用状态 + 拥有通配权限」的人。
// 停用/删除最后一个管理员会把所有人锁在门外，必须拦住。
//
// ⚠️ 这条**必须**按租户数（§3.2 ①）。原来是一条不带租户条件的全表 count，
// 多租户下等于：A 公司还有 admin，B 公司删掉自己最后一个 admin 时检查照样通过 ——
// **B 公司被锁在门外，只能上数据库救。**
func (q *Queries) CountActiveAdmins(ctx context.Context, arg CountActiveAdminsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins, arg.TenantID, arg.ExcludeUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersFiltered = `-- name: CountUsersFiltered :one
SELECT count(*) FROM users u
WHERE u.tenant_id = $1
  AND u.deleted_at IS NULL
  AND ($2::varchar IS NULL
       OR u.username ILIKE $2
       OR u.display_name ILIKE $2
       OR u.email ILIKE $2
       OR u.phone ILIKE $2)
  AND ($3::varchar IS NULL OR u.status = $3)
  AND (
    (cardinality($4::uuid[]) = 0 AND NOT $5::bool)
    OR u.department_id = ANY($4::uuid[])
    OR ($5::bool AND u.department_id IS NULL)
  )
`

type CountUsersFilteredParams struct {
	TenantID          uuid.UUID
	Keyword           *string
	Status            *string
	DepartmentIds     []uuid.UUID
	IncludeUnassigned bool
}

func (q *Queries) CountUsersFiltered(ctx context.Context, arg CountUsersFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersFiltered,
		arg.TenantID,
		arg.Keyword,
		arg.Status,
		arg.DepartmentIds,
		arg.IncludeUnassigned,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createManagedUser = `-- name: CreateManagedUser :one
INSERT INTO users (tenant_id, id, username, display_name, email, phone, password_hash,
                   must_change_password, status, department_id, created_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7,
        true, $8, $9, $10)
RETURNING id, username, display_name, email, password_hash, password_changed_at, must_change_password, status, failed_attempts, locked_until, last_login_at, created_at, updated_at, deleted_at, created_by, version, phone, department_id, tenant_id
`

type CreateManagedUserParams struct {
	TenantID     uuid.UUID
	ID           uuid.UUID
	Username     string
	DisplayName  string
	Email        *string
	Phone        *string
	PasswordHash string
	Status       string
	DepartmentID *uuid.UUID
	CreatedBy    *uuid.UUID
}

func (q *Queries) CreateManagedUser(ctx context.Context, arg CreateManagedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createManagedUser,
		arg.TenantID,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.Status,
		arg.DepartmentID,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.Phone,
		&i.DepartmentID,
		&i.TenantID,
	)
	return i, err
}

const getUserWithDepartment = `-- name: GetUserWithDepartment :one
SELECT u.id, u.username, u.display_name, u.email, u.password_hash, u.password_changed_at, u.must_change_password, u.status, u.failed_attempts, u.locked_until, u.last_login_at, u.created_at, u.updated_at, u.deleted_at, u.created_by, u.version, u.phone, u.department_id, u.tenant_id, d.name AS department_name
FROM users u
LEFT JOIN departments d ON d.id = u.department_id AND d.tenant_id = u.tenant_id
                       AND d.deleted_at IS NULL
WHERE u.tenant_id = $1 AND u.id = $2 AND u.deleted_at IS NULL
`

type GetUserWithDepartmentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetUserWithDepartmentRow struct {
	User           User
	DepartmentName *string
}

func (q *Queries) GetUserWithDepartment(ctx context.Context, arg GetUserWithDepartmentParams) (GetUserWithDepartmentRow, error) {
	row := q.db.QueryRow(ctx, getUserWithDepartment, arg.TenantID, arg.ID)
	var i GetUserWithDepartmentRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Username,
		&i.User.DisplayName,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.PasswordChangedAt,
		&i.User.MustChangePassword,
		&i.User.Status,
		&i.User.FailedAttempts,
		&i.User.LockedUntil,
		&i.User.LastLoginAt,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.DeletedAt,
		&i.User.CreatedBy,
		&i.User.Version,
		&i.User.Phone,
		&i.User.DepartmentID,
		&i.User.TenantID,
		&i.DepartmentName,
	)
	return i, err
}

const listRoleIDsOfUser = `-- name: ListRoleIDsOfUser :many
SELECT role_id FROM user_roles
WHERE tenant_id = $1 AND user_id = $2
`

type ListRoleIDsOfUserParams struct {
	TenantID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) ListRoleIDsOfUser(ctx context.Context, arg ListRoleIDsOfUserParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listRoleIDsOfUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByIDs = `-- name: ListRolesByIDs :many
SELECT id, key, name, description, data_scope, builtin, status, created_at, updated_at, deleted_at, created_by, version, tenant_id FROM roles
WHERE tenant_id = $1
  AND id = ANY($2::uuid[])
  AND deleted_at IS NULL
`

type ListRolesByIDsParams struct {
	TenantID uuid.UUID
	Ids      []uuid.UUID
}

func (q *Queries) ListRolesByIDs(ctx context.Context, arg ListRolesByIDsParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByIDs, arg.TenantID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.DataScope,
			&i.Builtin,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.Version,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many

SELECT u.id, u.username, u.display_name, u.email, u.password_hash, u.password_changed_at, u.must_change_password, u.status, u.failed_attempts, u.locked_until, u.last_login_at, u.created_at, u.updated_at, u.deleted_at, u.created_by, u.version, u.phone, u.department_id, u.tenant_id,
       d.name AS department_name,
       -- 角色名拼成一列返回，省掉 N+1。ORDER BY 保证多次查询顺序一致，
       -- 否则同一条记录每次刷新角色顺序都在变，看着像数据在跳。
       -- 显式 ::text —— 不加的话 sqlc 推不出 string_agg 的类型，生成 interface{}。
       COALESCE((SELECT string_agg(r.name, ',' ORDER BY r.key)
                 FROM user_roles ur
                 JOIN roles r ON r.id = ur.role_id AND r.tenant_id = ur.tenant_id
                 WHERE ur.tenant_id = u.tenant_id AND ur.user_id = u.id
                   AND r.deleted_at IS NULL), '')::text AS role_names
FROM users u
LEFT JOIN departments d ON d.id = u.department_id AND d.tenant_id = u.tenant_id
                       AND d.deleted_at IS NULL
WHERE u.tenant_id = $1
  AND u.deleted_at IS NULL
  AND ($2::varchar IS NULL
       OR u.username ILIKE $2
       OR u.display_name ILIKE $2
       OR u.email ILIKE $2
       OR u.phone ILIKE $2)
  AND ($3::varchar IS NULL OR u.status = $3)
  -- 部门筛选支持**多选 + 「未分配」**：
  --   department_ids 为空数组且 include_unassigned=false → 不按部门筛
  --   否则命中「在这些部门里」或「压根没部门」
  AND (
    (cardinality($4::uuid[]) = 0 AND NOT $5::bool)
    OR u.department_id = ANY($4::uuid[])
    OR ($5::bool AND u.department_id IS NULL)
  )
ORDER BY u.created_at DESC, u.id DESC
LIMIT $7 OFFSET $6
`

type ListUsersParams struct {
	TenantID          uuid.UUID
	Keyword           *string
	Status            *string
	DepartmentIds     []uuid.UUID
	IncludeUnassigned bool
	Offset            int32
	Limit             int32
}

type ListUsersRow struct {
	User           User
	DepartmentName *string
	RoleNames      string
}

// 用户管理（DECISIONS.md §3、§6）。
//
// 登录链路用的那几个查询在 auth.sql 里，别混：那些是**认证**用的，
// 这里是**管理页面**用的。
//
// ⚠️ 这个文件里**每一条**都必须带 tenant_id，包括「按 id 改一行」的那些（§11.1）：
// 按 id 更新时最容易觉得「id 是唯一的，够了」—— 不够，那是 BOLA。
// 跨租户测试会拿 A 的上下文去 update/delete B 的 id，影响行数必须是 0（§10.8）。
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.TenantID,
		arg.Keyword,
		arg.Status,
		arg.DepartmentIds,
		arg.IncludeUnassigned,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.DisplayName,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.PasswordChangedAt,
			&i.User.MustChangePassword,
			&i.User.Status,
			&i.User.FailedAttempts,
			&i.User.LockedUntil,
			&i.User.LastLoginAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.User.CreatedBy,
			&i.User.Version,
			&i.User.Phone,
			&i.User.DepartmentID,
			&i.User.TenantID,
			&i.DepartmentName,
			&i.RoleNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersNotInDepartment = `-- name: ListUsersNotInDepartment :many
SELECT u.id, u.username, u.display_name, u.email, u.password_hash, u.password_changed_at, u.must_change_password, u.status, u.failed_attempts, u.locked_until, u.last_login_at, u.created_at, u.updated_at, u.deleted_at, u.created_by, u.version, u.phone, u.department_id, u.tenant_id, d.name AS department_name
FROM users u
LEFT JOIN departments d ON d.id = u.department_id AND d.tenant_id = u.tenant_id
                       AND d.deleted_at IS NULL
WHERE u.tenant_id = $1
  AND u.deleted_at IS NULL
  AND u.status = 'active'
  AND (u.department_id IS DISTINCT FROM $2::uuid)
  AND ($3::varchar IS NULL
       OR u.username ILIKE $3
       OR u.display_name ILIKE $3)
ORDER BY u.display_name
LIMIT $4
`

type ListUsersNotInDepartmentParams struct {
	TenantID     uuid.UUID
	DepartmentID *uuid.UUID
	Keyword      *string
	Limit        int32
}

type ListUsersNotInDepartmentRow struct {
	User           User
	DepartmentName *string
}

// 「添加成员」候选：不在这个部门里的人。department_id 传 NULL 表示「不在任何部门的人」。
func (q *Queries) ListUsersNotInDepartment(ctx context.Context, arg ListUsersNotInDepartmentParams) ([]ListUsersNotInDepartmentRow, error) {
	rows, err := q.db.Query(ctx, listUsersNotInDepartment,
		arg.TenantID,
		arg.DepartmentID,
		arg.Keyword,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersNotInDepartmentRow{}
	for rows.Next() {
		var i ListUsersNotInDepartmentRow
		if err := rows.Scan(
			&i.User.ID,
			&i.User.Username,
			&i.User.DisplayName,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.PasswordChangedAt,
			&i.User.MustChangePassword,
			&i.User.Status,
			&i.User.FailedAttempts,
			&i.User.LockedUntil,
			&i.User.LastLoginAt,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User.DeletedAt,
			&i.User.CreatedBy,
			&i.User.Version,
			&i.User.Phone,
			&i.User.DepartmentID,
			&i.User.TenantID,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserPassword = `-- name: ResetUserPassword :execrows
UPDATE users
SET password_hash        = $1,
    password_changed_at  = now(),
    must_change_password = true,
    failed_attempts      = 0,
    locked_until         = NULL,
    version              = version + 1
WHERE tenant_id = $2 AND id = $3 AND deleted_at IS NULL
`

type ResetUserPasswordParams struct {
	PasswordHash string
	TenantID     uuid.UUID
	ID           uuid.UUID
}

// 管理员重置密码：**一定要 must_change_password = true** ——
// 临时密码经过了管理员的手，本人必须马上换掉。
func (q *Queries) ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, resetUserPassword, arg.PasswordHash, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUsersDepartment = `-- name: SetUsersDepartment :execrows
UPDATE users
SET department_id = $1
WHERE tenant_id = $2
  AND id = ANY($3::uuid[])
  AND deleted_at IS NULL
`

type SetUsersDepartmentParams struct {
	DepartmentID *uuid.UUID
	TenantID     uuid.UUID
	UserIds      []uuid.UUID
}

// 批量调整部门归属。department_id 传 NULL 就是移出部门。
// **不动 version**：调部门是管理动作，不该让正在编辑这个人的另一个页面撞版本冲突。
//
// ⚠️ 批量按 id 改是 BOLA 的重灾区：不带 tenant_id 的话，传一串别家公司的 user_id
// 就能把人从他们的部门里摘出来。影响行数会如实返回，也就成了一个存在性探针。
func (q *Queries) SetUsersDepartment(ctx context.Context, arg SetUsersDepartmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUsersDepartment, arg.DepartmentID, arg.TenantID, arg.UserIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :one
UPDATE users
SET deleted_at = now(), version = version + 1
WHERE tenant_id = $1
  AND id = $2
  AND version = $3
  AND deleted_at IS NULL
RETURNING id
`

type SoftDeleteUserParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Version  int32
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteUser, arg.TenantID, arg.ID, arg.Version)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateManagedUser = `-- name: UpdateManagedUser :one
UPDATE users
SET display_name  = $1,
    email         = $2,
    phone         = $3,
    status        = $4,
    department_id = $5,
    version       = version + 1
WHERE tenant_id = $6
  AND id = $7
  AND version = $8
  AND deleted_at IS NULL
RETURNING id, username, display_name, email, password_hash, password_changed_at, must_change_password, status, failed_attempts, locked_until, last_login_at, created_at, updated_at, deleted_at, created_by, version, phone, department_id, tenant_id
`

type UpdateManagedUserParams struct {
	DisplayName  string
	Email        *string
	Phone        *string
	Status       string
	DepartmentID *uuid.UUID
	TenantID     uuid.UUID
	ID           uuid.UUID
	Version      int32
}

// username 不给改：它是登录标识，也是审计里认人的依据。
// 改了之后老审计记录指向的那个人就对不上了。
func (q *Queries) UpdateManagedUser(ctx context.Context, arg UpdateManagedUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateManagedUser,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.Status,
		arg.DepartmentID,
		arg.TenantID,
		arg.ID,
		arg.Version,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordChangedAt,
		&i.MustChangePassword,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.Phone,
		&i.DepartmentID,
		&i.TenantID,
	)
	return i, err
}
