/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询审计日志
         * @description 按操作人、资源、动作、时间范围翻审计日志。审计表只增不改不删。
         */
        get: operations["list-audit-logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 忘记密码：申请重置邮件
         * @description 按公司代码 + 标识找到用户，发一封带一次性重置链接的邮件。⚠️ 无论账号是否存在都返回同一句成功（防用户枚举）。
         */
        post: operations["forgot-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description 校验账号密码，成功后种下 httpOnly 会话 cookie 和 CSRF cookie。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description 吊销当前会话并清除 cookie。服务端立即失效，不等 cookie 过期。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 自助注册：申请开一个组织
         * @description 校验后发一封验证邮件。⚠️ 需平台在设置里开启「允许自助注册」，否则拒绝。邮箱/公司代码是否已存在不在这一步暴露（防枚举）。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 自助注册：验证邮箱、完成建组织
         * @description 校验邮件里的一次性 token，建组织和首个管理员，返回登录要用的公司代码。
         */
        post: operations["register-verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 忘记密码：用 token 设新密码
         * @description 校验邮件里的一次性 token，设置新密码并踢掉该用户的全部会话。
         */
        post: operations["reset-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询部门
         * @description 一次返回全部部门节点（不分页），前端自己拼树。
         */
        get: operations["list-departments"];
        put?: never;
        /** 新增部门 */
        post: operations["create-department"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 编辑部门 */
        put: operations["update-department"];
        post?: never;
        /**
         * 删除部门
         * @description 软删除。下面还有子部门或成员时拒绝。
         */
        delete: operations["delete-department"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 可加入该部门的人
         * @description 列出**不在**这个部门里的活跃用户，给「添加成员」用。
         */
        get: operations["list-department-candidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 把人加入部门
         * @description 一个人只能属于一个部门，加入即从原部门移出。
         */
        post: operations["add-department-members"];
        /**
         * 把人移出部门
         * @description 移出后这些人不属于任何部门，账号本身不受影响。
         */
        delete: operations["remove-department-members"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前用户与菜单
         * @description 返回当前登录者、他拥有的权限点，以及过滤后的菜单树。
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改自己的密码
         * @description 改完会踢掉自己的其它会话，当前会话保留。
         */
        post: operations["change-own-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 连通性自检
         * @description 回显参数并返回服务端时间。用来确认接口链路、响应封套和 request_id 都通了。
         */
        get: operations["ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 平台管理员登录
         * @description 和租户登录完全分开：独立的会话表、独立的 cookie、更严的失败节流。
         */
        post: operations["platform-login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 平台管理员退出登录 */
        post: operations["platform-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前平台管理员 */
        get: operations["platform-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 平台管理员改自己的密码
         * @description 平台走自己的强密码要求，不吃租户级的密码策略。
         */
        post: operations["platform-change-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查看平台设置
         * @description 平台自己的配置，外加**给各组织划的可调范围**（MULTI-TENANCY.md §10.5）。
         */
        get: operations["list-platform-settings"];
        /**
         * 修改平台设置
         * @description 改可调范围会立刻约束所有组织的下一次配置修改，但**不会回改**它们已经设好的值 —— 那些值下次被改动时才会受新范围约束。
         */
        put: operations["save-platform-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 组织列表
         * @description 人数来自 tenants.user_count 冗余列，平台端不查客户的业务表。
         */
        get: operations["list-tenants"];
        put?: never;
        /**
         * 开通组织
         * @description 同时建好这个组织的第一个管理员，返回只显示一次的初始密码。
         */
        post: operations["create-tenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/tenants/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 停用 / 启用组织
         * @description 停用立刻生效：那家公司已经发出去的会话下一个请求就失效。组织只停用，不删除。
         */
        post: operations["set-tenant-status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询角色 */
        get: operations["list-roles"];
        put?: never;
        /** 新增角色 */
        post: operations["create-role"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/permission-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 权限点目录
         * @description 全部可勾选的权限点，按模块分组。角色配置页用它渲染勾选树。
         */
        get: operations["list-permission-catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 角色详情
         * @description 带上已勾选的权限点。
         */
        get: operations["get-role"];
        /**
         * 编辑角色
         * @description 角色标识（key）建后不可改。内置角色整体不可改。
         */
        put: operations["update-role"];
        post?: never;
        /**
         * 删除角色
         * @description 软删除。还有用户或系统账号在用时拒绝。
         */
        delete: operations["delete-role"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询机器账号
         * @description 外部系统拿 API Key 调进来的身份。**返回里没有密钥** —— 密钥只在新建和轮换时出现一次，之后库里只有哈希。
         */
        get: operations["list-service-accounts"];
        put?: never;
        /**
         * 新增机器账号
         * @description 返回**只显示一次**的完整密钥。关掉页面就再也拿不到，只能轮换。
         */
        post: operations["create-service-account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 机器账号详情 */
        get: operations["get-service-account"];
        /**
         * 编辑机器账号
         * @description 改名称、说明、角色、状态、到期时间。**不换密钥** —— 那是单独的动作。
         */
        put: operations["update-service-account"];
        post?: never;
        /**
         * 删除机器账号
         * @description 软删。删掉之后它的密钥立刻认证不过。
         */
        delete: operations["delete-service-account"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/service-accounts/{id}/rotate-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 轮换密钥
         * @description 换一副新密钥并返回一次。⚠️ **旧密钥当场失效**，对接方在换上新密钥之前会一直 401。
         */
        post: operations["rotate-service-account-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查看本组织的设置
         * @description 返回分组 → 配置项，每项带当前值和**平台允许的取值范围**。范围由服务端给，前端不要硬编码 —— 它是平台随时能调的。
         */
        get: operations["list-settings"];
        /**
         * 修改本组织的设置
         * @description 改完立即生效（写库 → NOTIFY → 各实例刷新缓存）。密码策略只影响下次改密，**不影响已有密码**。
         */
        put: operations["save-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询供应商 */
        get: operations["list-suppliers"];
        put?: never;
        /** 新增供应商 */
        post: operations["create-supplier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出供应商 */
        get: operations["export-suppliers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看供应商 */
        get: operations["get-supplier"];
        /** 编辑供应商 */
        put: operations["update-supplier"];
        post?: never;
        /** 删除供应商 */
        delete: operations["delete-supplier"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询用户 */
        get: operations["list-users"];
        put?: never;
        /**
         * 新增用户
         * @description 初始密码由系统随机生成，**只在响应里出现一次**，且本人首次登录必须修改。
         */
        post: operations["create-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 用户详情
         * @description 带上角色 ID 列表。
         */
        get: operations["get-user"];
        /**
         * 编辑用户
         * @description 用户名建后不可改。停用会立刻踢掉这个人的全部会话。
         */
        put: operations["update-user"];
        post?: never;
        /**
         * 删除用户
         * @description 软删除，并立刻吊销全部会话。不能删自己，也不能删掉最后一个管理员。
         */
        delete: operations["delete-user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重置密码
         * @description 生成临时密码并踢掉该用户全部会话。临时密码只在响应里出现一次。
         */
        post: operations["reset-user-password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditEntry: {
            action: string;
            actor_id: string;
            actor_name: string;
            /** @description user / service / anonymous / system */
            actor_type: string;
            /** @description 参数摘要，敏感字段已脱敏 */
            detail: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            duration_ms: number;
            /**
             * Format: int64
             * @description HTTP 响应状态码
             */
            http_status: number;
            id: string;
            ip: string;
            method: string;
            /** Format: date-time */
            occurred_at: string;
            path: string;
            request_id: string;
            resource: string;
            /** @description 操作的是哪条记录 */
            resource_id: string;
            user_agent: string;
        };
        ChangePasswordInputBody: {
            /** @description 新密码 */
            new_password: string;
            /** @description 原密码 */
            old_password: string;
        };
        CreateRoleInputBody: {
            /**
             * @description all=看本组织全部 / self=只看自己创建的
             * @default self
             * @enum {string}
             */
            data_scope: "all" | "self";
            description?: string;
            /** @description 角色标识，小写字母数字下划线，建后不可改 */
            key: string;
            name: string;
            /** @description 勾选的权限点，形如 user:list */
            permissions?: string[];
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        CreateTenantInputBody: {
            /** @description 公司代码，客户登录时要填；只能小写字母、数字、中划线 */
            code: string;
            /** @description 组织名 */
            name: string;
        };
        CreateUserInputBody: {
            /**
             * Format: uuid
             * @description 不传表示不属于任何部门
             */
            department_id?: string;
            display_name: string;
            /** @description 可空。填了就必须全局唯一 */
            email?: string;
            /** @description 可空。填了就必须全局唯一 */
            phone?: string;
            /** @description 绑定的角色 ID 列表 */
            role_ids?: string[];
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
            /** @description 登录用户名，建后不可改 */
            username: string;
        };
        CreatedKey: {
            account: components["schemas"]["ServiceAccount"];
            /** @description 完整密钥，只显示这一次，关掉就再也拿不到了 */
            key: string;
        };
        CreatedTenant: {
            /** @description 初始密码，只显示这一次 */
            admin_password: string;
            admin_username: string;
            tenant: components["schemas"]["Tenant"];
        };
        CreatedUser: {
            /** @description 初始密码，只显示这一次，请立即转交本人 */
            initial_password: string;
            user: components["schemas"]["User"];
        };
        CurrentTenant: {
            /** @description 公司代码，登录时要填的那个 */
            code: string;
            /** @description 组织名 */
            name: string;
        };
        DataCreatedKey: {
            data: components["schemas"]["CreatedKey"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataCreatedTenant: {
            data: components["schemas"]["CreatedTenant"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataCreatedUser: {
            data: components["schemas"]["CreatedUser"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataDepartment: {
            data: components["schemas"]["Department"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataListPermissionModule: {
            data: components["schemas"]["PermissionModule"][];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataLoginResult: {
            data: components["schemas"]["LoginResult"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataMeResult: {
            data: components["schemas"]["MeResult"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataMemberChangeResult: {
            data: components["schemas"]["MemberChangeResult"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataPingResult: {
            data: components["schemas"]["PingResult"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataPlatformMeResult: {
            data: components["schemas"]["PlatformMeResult"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataResetPasswordResult: {
            data: components["schemas"]["ResetPasswordResult"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataRole: {
            data: components["schemas"]["Role"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataServiceAccount: {
            data: components["schemas"]["ServiceAccount"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataSettingsResult: {
            data: components["schemas"]["SettingsResult"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        "DataStruct {}": {
            data: components["schemas"]["DataStruct {}DataStruct"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        "DataStruct {}DataStruct": Record<string, never>;
        DataSupplier: {
            data: components["schemas"]["Supplier"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataTenant: {
            data: components["schemas"]["Tenant"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataUser: {
            data: components["schemas"]["User"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DataVerifiedResult: {
            data: components["schemas"]["VerifiedResult"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        DeleteDepartmentInputBody: {
            /**
             * Format: int64
             * @description 乐观锁版本号
             */
            version: number;
        };
        DeleteRoleInputBody: {
            /** Format: int64 */
            version: number;
        };
        DeleteServiceAccountInputBody: {
            /**
             * Format: int64
             * @description 乐观锁版本号
             */
            version: number;
        };
        DeleteSupplierInputBody: {
            /**
             * Format: int64
             * @description 乐观锁版本号
             */
            version: number;
        };
        DeleteUserInputBody: {
            /** Format: int64 */
            version: number;
        };
        Department: {
            /** @description 部门编号，对接外部系统用 */
            code: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            name: string;
            /** @description 上级部门；根节点为 null */
            parent_id: string;
            remark: string;
            /**
             * Format: int64
             * @description 同级排序，小的在前
             */
            sort_order: number;
            /** @description active / disabled */
            status: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description 直属成员数，不含下级部门
             */
            user_count: number;
            /**
             * Format: int64
             * @description 乐观锁版本号，更新时原样传回
             */
            version: number;
        };
        DepartmentBody: {
            /** @description 部门编号，字母数字下划线中划线 */
            code: string;
            /** @description 部门名称 */
            name: string;
            /**
             * Format: uuid
             * @description 上级部门；不传或空串表示根节点
             */
            parent_id?: string;
            remark?: string;
            /**
             * Format: int64
             * @description 同级排序，小的在前
             */
            sort_order?: number;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        DepartmentMembersInputBody: {
            /** @description 要调整的用户 ID */
            user_ids: string[];
        };
        ForgotPasswordInputBody: {
            /** @description 用户名 / 邮箱 / 手机号 */
            identifier: string;
            /** @description 公司代码 */
            tenant_code: string;
        };
        Group: {
            items: components["schemas"]["Item"][];
            key: string;
            /** @description 分组中文名 */
            name: string;
        };
        Identity: {
            display_name: string;
            id: string;
            /** @description 角色 key 列表 */
            roles: string[];
            /** @description 数据范围：all 看本组织全部，self 只看自己创建的 */
            scope: string;
            username: string;
        };
        Item: {
            /** @description 说明，显示在输入框下面 */
            desc: string;
            key: string;
            /** @description int / bool / string，前端按它选控件 */
            kind: string;
            /** Format: int64 */
            max?: number;
            /** Format: int64 */
            min?: number;
            /** @description 中文名 */
            name: string;
            /** @description 单位，空表示没有单位 */
            unit: string;
            /** @description 当前值。库里没有这一项时是默认值 */
            value: unknown;
        };
        Item1: {
            /** @description 配置项 key，从列表接口拿 */
            key: string;
            /** @description 新值。整数项传数字，开关传 true/false，文本传字符串 */
            value: unknown;
        };
        LoginInputBody: {
            /** @description 用户名 / 邮箱 / 手机号 */
            account: string;
            /** @description 密码 */
            password: string;
            /** @description 公司代码 */
            tenant_code: string;
        };
        LoginResult: {
            csrf_token: string;
            /** Format: date-time */
            expires_at: string;
            must_change_password: boolean;
            user: components["schemas"]["Identity"];
        };
        MeResult: {
            /** @description 过滤后的菜单树 */
            menus: components["schemas"]["MenuItem"][];
            /** @description 拥有的权限点，形如 audit:list */
            permissions: string[];
            tenant: components["schemas"]["CurrentTenant"];
            user: components["schemas"]["Identity"];
        };
        MemberChangeResult: {
            /**
             * Format: int64
             * @description 实际调整了几个人
             */
            affected: number;
        };
        MenuItem: {
            /** @description 图标名 */
            icon: string;
            /** @description 模块 key */
            key: string;
            /** @description 菜单名 */
            name: string;
            /** @description 前端路由路径 */
            path: string;
        };
        PageAuditEntry: {
            data: components["schemas"]["AuditEntry"][];
            pagination: components["schemas"]["Pagination"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        PageDepartment: {
            data: components["schemas"]["Department"][];
            pagination: components["schemas"]["Pagination"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        PageRole: {
            data: components["schemas"]["Role"][];
            pagination: components["schemas"]["Pagination"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        PageServiceAccount: {
            data: components["schemas"]["ServiceAccount"][];
            pagination: components["schemas"]["Pagination"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        PageSupplier: {
            data: components["schemas"]["Supplier"][];
            pagination: components["schemas"]["Pagination"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        PageTenant: {
            data: components["schemas"]["Tenant"][];
            pagination: components["schemas"]["Pagination"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        PageUser: {
            data: components["schemas"]["User"][];
            pagination: components["schemas"]["Pagination"];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id: string;
        };
        Pagination: {
            /**
             * Format: int64
             * @description 当前页码，从 1 开始
             */
            page: number;
            /**
             * Format: int64
             * @description 每页条数
             */
            page_size: number;
            /**
             * Format: int64
             * @description 符合条件的总条数
             */
            total: number;
        };
        PermissionAction: {
            /** @description 动作标识，如 list */
            key: string;
            /** @description 中文名 */
            name: string;
            /** @description 完整权限点，如 user:list —— 勾选时提交的就是它 */
            point: string;
        };
        PermissionModule: {
            actions: components["schemas"]["PermissionAction"][];
            key: string;
            name: string;
            /** @description 是否参与数据权限 */
            scoped: boolean;
        };
        PingResult: {
            /** @description 回显内容 */
            message: string;
            /**
             * Format: date-time
             * @description 服务端当前时间（UTC，RFC3339）
             */
            server_time: string;
            /**
             * Format: int64
             * @description 回显次数
             */
            times: number;
            /** @description 服务版本 */
            version: string;
        };
        PlatformLoginInputBody: {
            /** @description 密码 */
            password: string;
            /** @description 平台管理员账号 */
            username: string;
        };
        PlatformMeResult: {
            user: components["schemas"]["Identity"];
        };
        Problem: {
            /**
             * @description 机器判断用的错误码，前端 switch 它
             * @example user.duplicate_username
             */
            code: string;
            /**
             * @description 给用户看的中文文案
             * @example 用户名已存在
             */
            detail?: string;
            /** @description 字段级错误，前端可自动映射到表单字段 */
            errors?: components["schemas"]["ProblemItem"][];
            /** @description 本次请求的 ID，报障时提供它就能定位日志 */
            request_id?: string;
            /**
             * Format: int64
             * @description HTTP 状态码
             * @example 409
             */
            status: number;
            /**
             * @description 错误类型的英文简述
             * @example Conflict
             */
            title: string;
            /**
             * @description 错误类型的文档地址，当前统一 about:blank
             * @example about:blank
             */
            type: string;
        };
        ProblemItem: {
            /** @description 出错位置，如 body.username / query.page */
            location?: string;
            /** @description 这一项的中文提示 */
            message: string;
            /** @description 原样回显的入参值，便于排查 */
            value?: unknown;
        };
        RegisterInputBody: {
            /** @description 公司代码，登录时要填 */
            code: string;
            /** @description 组织名 */
            company_name: string;
            /**
             * Format: email
             * @description 管理员邮箱，验证信发这里
             */
            email: string;
            /** @description 管理员密码 */
            password: string;
        };
        RegisterVerifyInputBody: {
            /** @description 验证邮件里的一次性 token */
            token: string;
        };
        ResetByTokenInputBody: {
            /** @description 新密码 */
            new_password: string;
            /** @description 重置邮件里的一次性 token */
            token: string;
        };
        ResetPasswordResult: {
            /** @description 临时密码，只显示这一次。本人下次登录必须改掉 */
            password: string;
        };
        Role: {
            /** @description 内置角色不可改不可删 */
            builtin: boolean;
            /** Format: date-time */
            created_at: string;
            /** @description all=看本组织全部 / self=只看自己创建的 */
            data_scope: string;
            description: string;
            id: string;
            /** @description 角色标识，创建后不可改 —— 它是 Casbin 策略里的身份 */
            key: string;
            name: string;
            /** Format: int64 */
            permission_count: number;
            permissions: string[];
            /** @description active / disabled */
            status: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: int64
             * @description 绑定了这个角色的用户数
             */
            user_count: number;
            /**
             * Format: int64
             * @description 乐观锁版本号，更新时原样传回
             */
            version: number;
        };
        SaveSettingsInputBody: {
            /** @description 要改的配置项 */
            items: components["schemas"]["Item1"][];
        };
        ServiceAccount: {
            /** Format: date-time */
            created_at: string;
            description: string;
            /**
             * Format: date-time
             * @description 到期后认证直接失败，空表示不过期
             */
            expires_at: string | null;
            id: string;
            key_prefix: string;
            /**
             * Format: date-time
             * @description 最后一次用它调接口的时间，空表示从没用过
             */
            last_used_at: string | null;
            name: string;
            role_id: string;
            role_name: string;
            /** @description active / disabled */
            status: string;
            /**
             * Format: int64
             * @description 乐观锁版本号，更新时原样传回
             */
            version: number;
        };
        ServiceAccountBody: {
            /** @description 说明：这个账号给谁用、干什么 */
            description?: string;
            /**
             * Format: date-time
             * @description 到期时间，空表示不过期
             */
            expires_at?: string;
            /** @description 名称，组织内唯一 */
            name: string;
            /**
             * Format: uuid
             * @description 绑定的角色，决定它能调哪些接口
             */
            role_id: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        SetTenantStatusInputBody: {
            /** @enum {string} */
            status: "active" | "suspended";
            /**
             * Format: int64
             * @description 乐观锁版本号
             */
            version: number;
        };
        SettingsResult: {
            groups: components["schemas"]["Group"][];
        };
        Supplier: {
            /** Format: date-time */
            created_at: string;
            credit: string | null;
            id: string;
            name: string;
            remark: string | null;
            /** Format: date-time */
            started_at: string | null;
            status: string | null;
            /** Format: date-time */
            updated_at: string;
            /** Format: int32 */
            version: number;
        };
        SupplierBody: {
            /** @description 数字，字符串传 */
            credit?: string;
            name: string;
            remark?: string;
            /** Format: date */
            started_at?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "terminated";
        };
        Tenant: {
            /** @description 公司代码，客户登录时要填的那个 */
            code: string;
            /** Format: date-time */
            created_at: string;
            id: string;
            /** @description 组织名 */
            name: string;
            /** @description active / suspended */
            status: string;
            /**
             * Format: int64
             * @description 成员数
             */
            user_count: number;
            /**
             * Format: int64
             * @description 乐观锁版本号，更新时原样传回
             */
            version: number;
        };
        UpdateDepartmentInputBody: {
            /** @description 部门编号，字母数字下划线中划线 */
            code: string;
            /** @description 部门名称 */
            name: string;
            /**
             * Format: uuid
             * @description 上级部门；不传或空串表示根节点
             */
            parent_id?: string;
            remark?: string;
            /**
             * Format: int64
             * @description 同级排序，小的在前
             */
            sort_order?: number;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
            /**
             * Format: int64
             * @description 乐观锁版本号，取自上次读到的值
             */
            version: number;
        };
        UpdateRoleInputBody: {
            /**
             * @description all=看本组织全部 / self=只看自己创建的
             * @default self
             * @enum {string}
             */
            data_scope: "all" | "self";
            description?: string;
            name: string;
            /** @description 勾选的权限点，形如 user:list */
            permissions?: string[];
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
            /**
             * Format: int64
             * @description 乐观锁版本号
             */
            version: number;
        };
        UpdateServiceAccountInputBody: {
            /** @description 说明：这个账号给谁用、干什么 */
            description?: string;
            /**
             * Format: date-time
             * @description 到期时间，空表示不过期
             */
            expires_at?: string;
            /** @description 名称，组织内唯一 */
            name: string;
            /**
             * Format: uuid
             * @description 绑定的角色，决定它能调哪些接口
             */
            role_id: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
            /**
             * Format: int64
             * @description 乐观锁版本号，从详情接口拿到什么就传什么
             */
            version: number;
        };
        UpdateSupplierInputBody: {
            /** @description 数字，字符串传 */
            credit?: string;
            name: string;
            remark?: string;
            /** Format: date */
            started_at?: string;
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "terminated";
            /**
             * Format: int64
             * @description 乐观锁版本号，取自上次读到的值
             */
            version: number;
        };
        UpdateUserInputBody: {
            /**
             * Format: uuid
             * @description 不传表示不属于任何部门
             */
            department_id?: string;
            display_name: string;
            /** @description 可空。填了就必须全局唯一 */
            email?: string;
            /** @description 可空。填了就必须全局唯一 */
            phone?: string;
            /** @description 绑定的角色 ID 列表 */
            role_ids?: string[];
            /**
             * @default active
             * @enum {string}
             */
            status: "active" | "disabled";
            /**
             * Format: int64
             * @description 乐观锁版本号
             */
            version: number;
        };
        User: {
            /** Format: date-time */
            created_at: string;
            department_id: string;
            department_name: string;
            display_name: string;
            email: string;
            id: string;
            /** Format: date-time */
            last_login_at: string | null;
            /**
             * Format: date-time
             * @description 登录失败过多被锁到什么时候
             */
            locked_until: string | null;
            /** @description 下次登录必须改密码 */
            must_change_password: boolean;
            phone: string;
            /** @description 绑定的角色 ID；列表接口不返回，详情才返回 */
            role_ids: string[];
            /** @description 角色名，逗号分隔，列表直接显示 */
            role_names: string;
            /** @description active / disabled */
            status: string;
            /** Format: date-time */
            updated_at: string;
            /** @description 登录用户名，建后不可改 */
            username: string;
            /**
             * Format: int64
             * @description 乐观锁版本号，更新时原样传回
             */
            version: number;
        };
        VerifiedResult: {
            /** @description 管理员用户名 */
            admin_username: string;
            /** @description 登录时填的公司代码 */
            tenant_code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-audit-logs": {
        parameters: {
            query?: {
                /** @description 页码，从 1 开始 */
                page?: number;
                /** @description 每页条数 */
                page_size?: number;
                /** @description 按资源筛选，如 audit */
                resource?: string;
                /** @description 按动作筛选，如 list */
                action?: string;
                /** @description 按操作人筛选 */
                actor_id?: string;
                /** @description 起始时间（含），RFC3339 */
                from?: string;
                /** @description 结束时间（不含），RFC3339 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAuditEntry"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                /** @description 浏览器标识，进审计 */
                "User-Agent"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataLoginResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "register-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterVerifyInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataVerifiedResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetByTokenInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-departments": {
        parameters: {
            query?: {
                /** @description 按名称或编号模糊匹配 */
                keyword?: string;
                /** @description 按状态筛选 */
                status?: "active" | "disabled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageDepartment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataDepartment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-department": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDepartmentInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataDepartment"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "delete-department": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteDepartmentInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-department-candidates": {
        parameters: {
            query?: {
                /** @description 按用户名或显示名模糊匹配 */
                keyword?: string;
                limit?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "add-department-members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentMembersInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataMemberChangeResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "remove-department-members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepartmentMembersInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataMemberChangeResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataMeResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "change-own-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    ping: {
        parameters: {
            query?: {
                /** @description 原样回显的内容 */
                echo?: string;
                /** @description 回显次数，1~5 */
                times?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataPingResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "platform-login": {
        parameters: {
            query?: never;
            header?: {
                /** @description 浏览器标识，进审计 */
                "User-Agent"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlatformLoginInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataLoginResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "platform-logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "platform-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataPlatformMeResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "platform-change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-platform-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSettingsResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "save-platform-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSettingsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSettingsResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-tenants": {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 按组织名或公司代码搜 */
                keyword?: string;
                status?: "" | "active" | "suspended";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageTenant"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCreatedTenant"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "set-tenant-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetTenantStatusInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataTenant"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-roles": {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 按名称或标识模糊匹配 */
                keyword?: string;
                status?: "active" | "disabled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageRole"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRole"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-permission-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataListPermissionModule"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "get-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRole"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataRole"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "delete-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteRoleInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-service-accounts": {
        parameters: {
            query?: {
                /** @description 页码，从 1 开始 */
                page?: number;
                /** @description 每页条数 */
                page_size?: number;
                /** @description 按名称或说明搜索 */
                keyword?: string;
                /** @description 按状态筛选 */
                status?: "active" | "disabled";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageServiceAccount"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-service-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceAccountBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCreatedKey"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "get-service-account": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataServiceAccount"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-service-account": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateServiceAccountInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataServiceAccount"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "delete-service-account": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteServiceAccountInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "rotate-service-account-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCreatedKey"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSettingsResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "save-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSettingsInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSettingsResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-suppliers": {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 关键字模糊匹配 */
                keyword?: string;
                /** @description 按状态筛选 */
                status?: "active" | "terminated";
                /** @description 按合作起始日筛选 */
                started_at?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageSupplier"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-supplier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSupplier"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "export-suppliers": {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 关键字模糊匹配 */
                keyword?: string;
                /** @description 按状态筛选 */
                status?: "active" | "terminated";
                /** @description 按合作起始日筛选 */
                started_at?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageSupplier"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "get-supplier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSupplier"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-supplier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSupplierInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataSupplier"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "delete-supplier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteSupplierInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "list-users": {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                /** @description 按用户名、显示名、邮箱、手机号模糊匹配 */
                keyword?: string;
                status?: "active" | "disabled";
                /** @description 部门 ID，可传多个；传 none 表示未分配部门的人 */
                department_id?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "create-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserInputBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataCreatedUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "get-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "update-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataUser"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "delete-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteUserInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStruct {}"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    "reset-user-password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResetPasswordResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
