// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

package modules

import "github.com/ramoncjs3/fries/internal/perm"

// Supplier 是供应商模块的权限声明。
var Supplier = perm.Register(perm.Module{
	Key:    "supplier",
	Name:   "供应商",
	Realm:  perm.RealmTenant,
	Scoped: true,
	Menu:   perm.Menu{Path: "/suppliers", Icon: "truck", ShowIf: perm.ActionList, Order: 500},
	Actions: []perm.Action{
		{Key: perm.ActionList, Name: "查询"},
		{Key: "read", Name: "查看"},
		{Key: perm.ActionCreate, Name: "新增"},
		{Key: perm.ActionUpdate, Name: "编辑"},
		{Key: perm.ActionDelete, Name: "删除"},
		{Key: "export", Name: "导出"},
	},
})
