// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

package handler

import (
	"context"
	"net/http"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/shopspring/decimal"

	"github.com/ramoncjs3/fries/internal/httpx"
	"github.com/ramoncjs3/fries/internal/perm"
	"github.com/ramoncjs3/fries/internal/perm/modules"
	suppliersvc "github.com/ramoncjs3/fries/internal/service/supplier"
)

// Supplier 是供应商管理接口。
type Supplier struct {
	svc *suppliersvc.Service
}

// NewSupplier 造供应商 handler。
func NewSupplier(svc *suppliersvc.Service) *Supplier { return &Supplier{svc: svc} }

// ListSupplierInput 是供应商列表查询入参。
type ListSupplierInput struct {
	Page      int    `query:"page" default:"1" minimum:"1"`
	PageSize  int    `query:"page_size" default:"20" minimum:"1" maximum:"100"`
	Keyword   string `query:"keyword" maxLength:"64" doc:"关键字模糊匹配"`
	Status    string `query:"status" enum:"active,terminated" doc:"按状态筛选"`
	StartedAt string `query:"started_at" doc:"按合作起始日筛选"`
}

// GetSupplierInput 是查看单条入参。
type GetSupplierInput struct {
	ID string `path:"id" format:"uuid"`
}

// SupplierBody 是新增/编辑供应商的请求体。校验写在 tag 上，service 不重复抄格式校验。
type SupplierBody struct {
	Name      string `json:"name" minLength:"1" maxLength:"100"`
	Status    string `json:"status,omitempty" enum:"active,terminated" default:"active"`
	Credit    string `json:"credit,omitempty" doc:"数字，字符串传"`
	StartedAt string `json:"started_at,omitempty" format:"date"`
	Remark    string `json:"remark,omitempty" maxLength:"2000"`
}

// CreateSupplierInput 是新增入参。
type CreateSupplierInput struct {
	Body SupplierBody
}

// UpdateSupplierInput 是编辑入参（带乐观锁版本号）。
type UpdateSupplierInput struct {
	ID   string `path:"id" format:"uuid"`
	Body struct {
		SupplierBody
		Version int `json:"version" minimum:"0" doc:"乐观锁版本号，取自上次读到的值"`
	}
}

// DeleteSupplierInput 是删除入参。
type DeleteSupplierInput struct {
	ID   string `path:"id" format:"uuid"`
	Body struct {
		Version int `json:"version" minimum:"0" doc:"乐观锁版本号"`
	}
}

// RegisterSupplier 注册供应商路由。
func RegisterSupplier(api huma.API, h *Supplier) {
	perm.Guard(api, modules.Supplier.Point(perm.ActionList), huma.Operation{
		OperationID: "list-suppliers",
		Method:      http.MethodGet,
		Path:        "/suppliers",
		Summary:     "查询供应商",
		Tags:        []string{modules.Supplier.Key},
	}, h.list)

	perm.Guard(api, modules.Supplier.Point("read"), huma.Operation{
		OperationID: "get-supplier",
		Method:      http.MethodGet,
		Path:        "/suppliers/{id}",
		Summary:     "查看供应商",
		Tags:        []string{modules.Supplier.Key},
	}, h.get)

	perm.Guard(api, modules.Supplier.Point(perm.ActionCreate), huma.Operation{
		OperationID:   "create-supplier",
		Method:        http.MethodPost,
		Path:          "/suppliers",
		Summary:       "新增供应商",
		Tags:          []string{modules.Supplier.Key},
		DefaultStatus: http.StatusCreated,
	}, h.create)

	perm.Guard(api, modules.Supplier.Point(perm.ActionUpdate), huma.Operation{
		OperationID: "update-supplier",
		Method:      http.MethodPut,
		Path:        "/suppliers/{id}",
		Summary:     "编辑供应商",
		Tags:        []string{modules.Supplier.Key},
	}, h.update)

	perm.Guard(api, modules.Supplier.Point(perm.ActionDelete), huma.Operation{
		OperationID: "delete-supplier",
		Method:      http.MethodDelete,
		Path:        "/suppliers/{id}",
		Summary:     "删除供应商",
		Tags:        []string{modules.Supplier.Key},
	}, h.remove)

	perm.Guard(api, modules.Supplier.Point("export"), huma.Operation{
		OperationID: "export-suppliers",
		Method:      http.MethodGet,
		Path:        "/suppliers/export",
		Summary:     "导出供应商",
		Tags:        []string{modules.Supplier.Key},
	}, h.export)
}

// list 分页查询。
func (h *Supplier) list(ctx context.Context, in *ListSupplierInput) (*httpx.PageResponse[suppliersvc.Supplier], error) {
	filter := suppliersvc.ListFilter{
		Page:     in.Page,
		PageSize: in.PageSize,
		Keyword:  in.Keyword,
	}
	if in.Status != "" {
		v := in.Status
		filter.Status = &v
	}
	if in.StartedAt != "" {
		v, err := time.Parse("2006-01-02", in.StartedAt)
		if err != nil {
			return nil, errInvalidField("query.started_at", "日期格式应为 YYYY-MM-DD")
		}
		filter.StartedAt = &v
	}
	items, total, err := h.svc.List(ctx, filter)
	if err != nil {
		return nil, err
	}
	return httpx.Paged(items, in.Page, in.PageSize, total), nil
}

// export 导出全部匹配行（不分页，取一个大上限）。
func (h *Supplier) export(ctx context.Context, in *ListSupplierInput) (*httpx.PageResponse[suppliersvc.Supplier], error) {
	in.Page = 1
	in.PageSize = 10000
	return h.list(ctx, in)
}

// get 查看单条。
func (h *Supplier) get(ctx context.Context, in *GetSupplierInput) (*httpx.Response[suppliersvc.Supplier], error) {
	id, err := parsePathID(in.ID)
	if err != nil {
		return nil, err
	}
	found, err := h.svc.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return httpx.OK(found), nil
}

// create 新增。
func (h *Supplier) create(ctx context.Context, in *CreateSupplierInput) (*httpx.Response[suppliersvc.Supplier], error) {
	input, err := toSupplierInput(in.Body)
	if err != nil {
		return nil, err
	}
	created, err := h.svc.Create(ctx, input)
	if err != nil {
		return nil, err
	}
	return httpx.OK(created), nil
}

// update 编辑。
func (h *Supplier) update(ctx context.Context, in *UpdateSupplierInput) (*httpx.Response[suppliersvc.Supplier], error) {
	id, err := parsePathID(in.ID)
	if err != nil {
		return nil, err
	}
	input, err := toSupplierInput(in.Body.SupplierBody)
	if err != nil {
		return nil, err
	}
	updated, err := h.svc.Update(ctx, id, in.Body.Version, input)
	if err != nil {
		return nil, err
	}
	return httpx.OK(updated), nil
}

// remove 软删除。
func (h *Supplier) remove(ctx context.Context, in *DeleteSupplierInput) (*httpx.Response[struct{}], error) {
	id, err := parsePathID(in.ID)
	if err != nil {
		return nil, err
	}
	if err := h.svc.Delete(ctx, id, in.Body.Version); err != nil {
		return nil, err
	}
	return httpx.OK(struct{}{}), nil
}

// toSupplierInput 把请求体翻成 service 入参（decimal/date 在这里解析，格式错回字段级错误）。
func toSupplierInput(body SupplierBody) (suppliersvc.Input, error) {
	in := suppliersvc.Input{}
	in.Name = body.Name
	if body.Status != "" {
		v := body.Status
		in.Status = &v
	}
	if body.Credit != "" {
		v, err := decimal.NewFromString(body.Credit)
		if err != nil {
			return in, errInvalidField("body.credit", "不是合法的数字")
		}
		in.Credit = &v
	}
	if body.StartedAt != "" {
		v, err := time.Parse("2006-01-02", body.StartedAt)
		if err != nil {
			return in, errInvalidField("body.started_at", "日期格式应为 YYYY-MM-DD")
		}
		in.StartedAt = &v
	}
	if body.Remark != "" {
		v := body.Remark
		in.Remark = &v
	}
	return in, nil
}
