// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

import { del, get, getPage, post, put, type PageResult } from '@/api/client'
import type { Supplier, SupplierInput, SupplierQuery } from '@/features/supplier/types'

export function listSuppliers(params: SupplierQuery): Promise<PageResult<Supplier>> {
  return getPage<Supplier>('/suppliers', {
    query: {
      page: params.page,
      page_size: params.pageSize,
      keyword: params.keyword,
      status: params.status,
      started_at: params.startedAt,
    },
  })
}

export function getSupplier(id: string): Promise<Supplier> {
  return get<Supplier>(`/suppliers/${id}`)
}

export function createSupplier(input: SupplierInput): Promise<Supplier> {
  return post<Supplier>('/suppliers', input)
}

export function updateSupplier(id: string, version: number, input: SupplierInput): Promise<Supplier> {
  return put<Supplier>(`/suppliers/${id}`, { ...input, version })
}

export function deleteSupplier(id: string, version: number): Promise<void> {
  return del<void>(`/suppliers/${id}`, { version })
}
