// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

import { Loader2, Pencil, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { useNavigate, useParams, useSearchParams } from 'react-router'

import { ApiError } from '@/api/client'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { DateTime } from '@/components/DateTime'
import { DetailItem, DetailPage, DetailSection } from '@/components/DetailPage'
import { FormAlert } from '@/components/PageState'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { SelectField } from '@/components/ui/select'
import { useSupplier, useSupplierMutations } from '@/features/supplier/queries'
import { supplierSchema, type SupplierFormValues } from '@/features/supplier/schema'
import { statusLabels, type Supplier } from '@/features/supplier/types'
import { useConfirm } from '@/lib/confirm'
import { useSession } from '@/lib/session'
import { zodResolver } from '@hookform/resolvers/zod'
import { useUnsavedGuard } from '@/lib/unsaved-guard'

const LIST_PATH = '/suppliers'
const FORM_ID = 'supplier-detail-form'

/** 供应商详情页。看和改在同一页，没有编辑弹窗（DECISIONS.md §7.6）。 */
export default function SupplierDetailPage() {
  const { id = '' } = useParams()
  const [searchParams, setSearchParams] = useSearchParams()
  const { can } = useSession()
  const detail = useSupplier(id)
  const entity = detail.data
  const editable = can('supplier', 'update')
  const editing = searchParams.get('edit') === '1' && editable
  const [editSeq, setEditSeq] = useState(0)

  function setEditing(next: boolean) {
    if (next) setEditSeq((n) => n + 1)
    setSearchParams(
      (current) => {
        const params = new URLSearchParams(current)
        if (next) params.set('edit', '1')
        else params.delete('edit')
        return params
      },
      { replace: true },
    )
  }

  if (!entity) {
    return (
      <DetailPage
        title="供应商详情"
        backTo={LIST_PATH}
        loading={detail.isPending}
        error={detail.isError ? detail.error : undefined}
        onRetry={() => void detail.refetch()}
      >
        {null}
      </DetailPage>
    )
  }

  return (
    <SupplierDetailBody
      key={editing ? `edit-${editSeq}` : 'read'}
      entity={entity}
      editing={editing}
      editable={editable}
      onEditingChange={setEditing}
      onReload={async () => {
        await detail.refetch()
        setEditSeq((n) => n + 1)
      }}
    />
  )
}

function SupplierDetailBody({
  entity,
  editing,
  editable,
  onEditingChange,
  onReload,
}: {
  entity: Supplier
  editing: boolean
  editable: boolean
  onEditingChange: (next: boolean) => void
  onReload: () => Promise<void>
}) {
  const navigate = useNavigate()
  const { can } = useSession()
  const confirm = useConfirm()
  const { remove, update } = useSupplierMutations()

  const form = useForm<SupplierFormValues>({
    resolver: zodResolver(supplierSchema),
    defaultValues: {
      name: entity.name ?? '',
      status: (entity.status ?? '') as SupplierFormValues['status'],
      credit: entity.credit ?? '',
      started_at: entity.started_at ?? '',
      remark: entity.remark ?? '',
    },
  })

  const dirty = editing && form.formState.isDirty
  const guard = useUnsavedGuard(dirty)
  const [failure, setFailure] = useState<{ message: string; conflict: boolean } | null>(null)
  const errors = editing ? form.formState.errors : {}

  async function onSubmit(values: SupplierFormValues) {
    setFailure(null)
    try {
      await update.mutateAsync({
        id: entity.id,
        version: entity.version,
        input: {
          name: values.name.trim(),
          status: values.status,
          credit: values.credit,
          started_at: values.started_at || undefined,
          remark: values.remark.trim(),
        },
      })
      onEditingChange(false)
      await onReload()
    } catch (err) {
      if (!(err instanceof ApiError)) {
        setFailure({ message: '保存失败了，请重试。', conflict: false })
        return
      }
      for (const item of err.formErrors()) {
        form.setError(item.field as keyof SupplierFormValues, { message: item.message })
      }
      if (err.formErrors().length === 0) {
        setFailure({ message: err.message, conflict: err.code === 'common.version_conflict' })
      }
    }
  }

  function cancelEdit() {
    if (!dirty) {
      onEditingChange(false)
      return
    }
    confirm.open({
      title: '放弃未保存的修改？',
      description: '取消之后这次改的内容不会保留。',
      confirmText: '放弃',
      destructive: true,
      onConfirm: () => onEditingChange(false),
    })
  }

  return (
    <>
      <DetailPage
        title={entity.name}
        backTo={LIST_PATH}
        alert={failure ? <FormAlert message={failure.message} /> : null}
        actions={
          editing ? (
            <span className="flex items-center gap-2">
              <Button variant="outline" onClick={cancelEdit} disabled={update.isPending}>
                取消
              </Button>
              <Button type="submit" form={FORM_ID} disabled={update.isPending}>
                {update.isPending ? <Loader2 className="animate-spin" /> : null}
                保存
              </Button>
            </span>
          ) : (
            <span className="flex items-center gap-2">
              {editable ? (
                <Button variant="outline" onClick={() => onEditingChange(true)}>
                  <Pencil /> 编辑
                </Button>
              ) : null}
              {can('supplier', 'delete') ? (
                <Button
                  variant="outline"
                  onClick={() =>
                    confirm.open({
                      title: '删除供应商？',
                      description: '删除后不可恢复。',
                      confirmText: '删除',
                      destructive: true,
                      onConfirm: async () => {
                        await remove.mutateAsync({ id: entity.id, version: entity.version })
                        void navigate(LIST_PATH)
                      },
                    })
                  }
                >
                  <Trash2 /> 删除
                </Button>
              ) : null}
            </span>
          )
        }
      >
        <form id={FORM_ID} className="space-y-8" onSubmit={(event) => void form.handleSubmit(onSubmit)(event)}>
          <DetailSection title="基本信息">
            <DetailItem label="供应商名称" required={editing} error={errors.name?.message}>
              {editing ? (
              <Input {...form.register("name")} />
              ) : (
                entity.name
              )}
            </DetailItem>

            <DetailItem label="状态" error={errors.status?.message}>
              {editing ? (
              <Controller
                control={form.control}
                name="status"
                render={({ field }) => (
                  <SelectField
                    ref={field.ref}
                    value={field.value}
                    onChange={field.onChange}
                    options={Object.entries(statusLabels).map(([value, label]) => ({ value, label }))}
                  />
                )}
              />
              ) : (
                entity.status ? (statusLabels[entity.status] ?? entity.status) : '—'
              )}
            </DetailItem>

            <DetailItem label="授信额度" error={errors.credit?.message}>
              {editing ? (
              <Input {...form.register("credit")} />
              ) : (
                entity.credit ?? '—'
              )}
            </DetailItem>

            <DetailItem label="合作起始日" error={errors.started_at?.message}>
              {editing ? (
              <Input type="date" {...form.register("started_at")} />
              ) : (
                <DateTime value={entity.started_at} />
              )}
            </DetailItem>

            <DetailItem label="备注" error={errors.remark?.message}>
              {editing ? (
              <Input {...form.register("remark")} />
              ) : (
                entity.remark ?? '—'
              )}
            </DetailItem>

          </DetailSection>
        </form>
      </DetailPage>

      <ConfirmDialog state={confirm} />
      <ConfirmDialog state={guard} />
    </>
  )
}
