// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

import { Pencil, Plus, Trash2 } from 'lucide-react'
import { Link, useNavigate } from 'react-router'

import type { FilterSpec } from '@/components/ListFilters'
import { ListPage, type Column } from '@/components/ListPage'
import { DateTime } from '@/components/DateTime'
import { RowActions } from '@/components/RowActions'
import { Button } from '@/components/ui/button'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { useSuppliers, useSupplierMutations } from '@/features/supplier/queries'
import { statusLabels, type Supplier } from '@/features/supplier/types'
import { useConfirm } from '@/lib/confirm'
import { FROM_LIST_STATE } from '@/lib/detail-nav'
import { useListParams } from '@/lib/list-params'
import { useSession } from '@/lib/session'

const filterSpecs: FilterSpec[] = [
  {
    key: "status",
    label: "状态",
    options: Object.entries(statusLabels).map(([value, label]) => ({ value, label })),
  },
]

export default function SupplierListPage() {
  const params = useListParams()
  const { can } = useSession()
  const navigate = useNavigate()
  const confirm = useConfirm()
  const { remove } = useSupplierMutations()

  const query = useSuppliers({
    page: params.page,
    pageSize: params.pageSize,
    keyword: params.search || undefined,
    status: params.filter("status") || undefined,
    startedAt: params.filter("started_at") || undefined,
  })

  const columns: Array<Column<Supplier>> = [
    { key: "name", header: "供应商名称", cell: (row) => row.name },
    { key: "status", header: "状态", cell: (row) => row.status ? (statusLabels[row.status] ?? row.status) : '—' },
    { key: "credit", header: "授信额度", cell: (row) => row.credit ?? '—' },
    { key: "started_at", header: "合作起始日", cell: (row) => <DateTime value={row.started_at} /> },
    { key: "remark", header: "备注", cell: (row) => row.remark ?? '—' },
    {
      key: 'actions',
      header: '',
      className: 'w-14',
      cell: (row) => (
        <RowActions
          actions={[
            ...(can('supplier', 'update')
              ? [
                  {
                    key: 'edit',
                    label: '编辑',
                    icon: <Pencil />,
                    onSelect: () => void navigate(`/suppliers/${row.id}?edit=1`, { state: FROM_LIST_STATE }),
                  },
                ]
              : []),
            ...(can('supplier', 'delete')
              ? [
                  {
                    key: 'delete',
                    label: '删除',
                    icon: <Trash2 />,
                    danger: true,
                    onSelect: () =>
                      confirm.open({
                        title: '删除供应商？',
                        description: '删除后不可恢复。',
                        confirmText: '删除',
                        destructive: true,
                        onConfirm: () => remove.mutateAsync({ id: row.id, version: row.version }),
                      }),
                  },
                ]
              : []),
          ]}
        />
      ),
    },
  ]

  return (
    <>
      <ListPage
        title="供应商管理"
        columns={columns}
        query={query}
        params={params}
        rowKey={(row) => row.id}
        rowLink={(row) => `/suppliers/${row.id}`}
        searchPlaceholder="搜索"
        filters={filterSpecs}
        emptyMessage="还没有供应商"
        actions={
          can('supplier', 'create') ? (
            <Button asChild>
              <Link to="/suppliers/new">
                <Plus /> 新增供应商
              </Link>
            </Button>
          ) : null
        }
      />

      <ConfirmDialog state={confirm} />
    </>
  )
}
