// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

import { zodResolver } from '@hookform/resolvers/zod'
import { Loader2 } from 'lucide-react'
import { useState } from 'react'
import { Controller, useForm } from 'react-hook-form'
import { useNavigate } from 'react-router'

import { ApiError } from '@/api/client'
import { ConfirmDialog } from '@/components/ConfirmDialog'
import { DetailItem, DetailPage, DetailSection } from '@/components/DetailPage'
import { FormAlert } from '@/components/PageState'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { SelectField } from '@/components/ui/select'
import { useSupplierMutations } from '@/features/supplier/queries'
import { emptySupplier, supplierSchema, type SupplierFormValues } from '@/features/supplier/schema'
import { statusLabels } from '@/features/supplier/types'
import { useUnsavedGuard } from '@/lib/unsaved-guard'

const LIST_PATH = '/suppliers'
const FORM_ID = 'supplier-new-form'

/** 新增供应商。是一个页面，不是弹窗（DECISIONS.md §7.6）。 */
export default function SupplierNewPage() {
  const navigate = useNavigate()
  const { create } = useSupplierMutations()
  const form = useForm<SupplierFormValues>({ resolver: zodResolver(supplierSchema), defaultValues: emptySupplier })
  const [failure, setFailure] = useState<string | null>(null)
  const guard = useUnsavedGuard(form.formState.isDirty)
  const errors = form.formState.errors

  async function onSubmit(values: SupplierFormValues) {
    setFailure(null)
    try {
      const created = await create.mutateAsync({
        name: values.name.trim(),
        status: values.status,
        credit: values.credit,
        started_at: values.started_at || undefined,
        remark: values.remark.trim(),
      })
      // 建完进详情页。replace 让「后退」不回到已提交的空表单。
      void navigate(`${LIST_PATH}/${created.id}`, { replace: true })
    } catch (error) {
      if (!(error instanceof ApiError)) {
        setFailure('创建失败了，请重试。')
        return
      }
      for (const item of error.formErrors()) {
        form.setError(item.field as keyof SupplierFormValues, { message: item.message })
      }
      if (error.formErrors().length === 0) setFailure(error.message)
    }
  }

  return (
    <>
      <DetailPage
        title="新增供应商"
        backTo={LIST_PATH}
        alert={failure ? <FormAlert message={failure} /> : null}
        actions={
          <span className="flex items-center gap-2">
            <Button variant="outline" onClick={() => void navigate(LIST_PATH)} disabled={create.isPending}>
              取消
            </Button>
            <Button type="submit" form={FORM_ID} disabled={create.isPending}>
              {create.isPending ? <Loader2 className="animate-spin" /> : null}
              创建
            </Button>
          </span>
        }
      >
        <form id={FORM_ID} className="space-y-8" onSubmit={(event) => void form.handleSubmit(onSubmit)(event)}>
          <DetailSection title="基本信息">
            <DetailItem label="供应商名称" required error={errors.name?.message}>
              <Input {...form.register("name")} />
            </DetailItem>

            <DetailItem label="状态" error={errors.status?.message}>
              <Controller
                control={form.control}
                name="status"
                render={({ field }) => (
                  <SelectField
                    ref={field.ref}
                    value={field.value}
                    onChange={field.onChange}
                    options={Object.entries(statusLabels).map(([value, label]) => ({ value, label }))}
                  />
                )}
              />
            </DetailItem>

            <DetailItem label="授信额度" error={errors.credit?.message}>
              <Input {...form.register("credit")} />
            </DetailItem>

            <DetailItem label="合作起始日" error={errors.started_at?.message}>
              <Input type="date" {...form.register("started_at")} />
            </DetailItem>

            <DetailItem label="备注" error={errors.remark?.message}>
              <Input {...form.register("remark")} />
            </DetailItem>

          </DetailSection>
        </form>
      </DetailPage>

      <ConfirmDialog state={guard} />
    </>
  )
}
