// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'

import { createSupplier, deleteSupplier, getSupplier, listSuppliers, updateSupplier } from '@/features/supplier/api'
import type { SupplierInput, SupplierQuery } from '@/features/supplier/types'

export const supplierKeys = {
  all: ['supplier'] as const,
  list: (params: SupplierQuery) => [...supplierKeys.all, 'list', params] as const,
  detail: (id: string) => [...supplierKeys.all, 'detail', id] as const,
}

export function useSuppliers(params: SupplierQuery) {
  return useQuery({ queryKey: supplierKeys.list(params), queryFn: () => listSuppliers(params) })
}

export function useSupplier(id: string | undefined) {
  return useQuery({
    queryKey: supplierKeys.detail(id ?? ''),
    queryFn: () => getSupplier(id as string),
    enabled: Boolean(id),
  })
}

export function useSupplierMutations() {
  const queryClient = useQueryClient()

  function invalidate() {
    return queryClient.invalidateQueries({ queryKey: supplierKeys.all })
  }

  const create = useMutation({
    mutationFn: (input: SupplierInput) => createSupplier(input),
    onSuccess: async () => {
      toast.success('供应商已创建')
      await invalidate()
    },
  })

  const update = useMutation({
    mutationFn: (args: { id: string; version: number; input: SupplierInput }) =>
      updateSupplier(args.id, args.version, args.input),
    onSuccess: async () => {
      toast.success('供应商已保存')
      await invalidate()
    },
  })

  const remove = useMutation({
    mutationFn: (args: { id: string; version: number }) => deleteSupplier(args.id, args.version),
    onSuccess: async () => {
      toast.success('供应商已删除')
      await invalidate()
    },
    onError: (error) => toast.error(error.message),
  })

  return { create, update, remove }
}
