// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

import { z } from 'zod'

/**
 * 表单校验规则。只放前端能判死的（非空、长度、枚举）——
 * 「是不是被占了」这类要查后端，不在这里复制一份（DECISIONS.md §5）。
 */
export const supplierSchema = z.object({
  name: z.string().trim().min(1, '请填写供应商名称').max(100, '供应商名称最多 100 个字符'),
  status: z.enum(['active', 'terminated']),
  credit: z.string(),
  started_at: z.string(),
  remark: z.string().max(2000, '备注最多 2000 个字'),
})

export type SupplierFormValues = z.infer<typeof supplierSchema>

export const emptySupplier: SupplierFormValues = {
  name: '',
  status: 'active',
  credit: '',
  started_at: '',
  remark: '',
}
