// Generated by fries-gen as a starting point.
// Safe to edit — regeneration will not overwrite.

import type { components } from '@/api/schema'

/**
 * 类型来自后端 OpenAPI，不手写一遍 —— 真相唯一在 Go 侧（DECISIONS.md §1）。
 * 重新生成：make gen-api
 */
export type Supplier = components['schemas']['Supplier']

/** 查询条件。 */
export interface SupplierQuery {
  page: number
  pageSize: number
  keyword?: string
  status?: string
  startedAt?: string
}

/** 新增/编辑的提交内容。字段名 snake_case，直接进请求体，须等于后端 json tag。 */
export interface SupplierInput {
  name: string
  status?: string
  credit?: string
  started_at?: string
  remark?: string
}

/** 状态的选项标签。 */
export const statusLabels: Record<string, string> = {
  active: '合作中',
  terminated: '已终止',
}
