-- 供应商（supplier）。由 fries-gen 生成的建表迁移。
-- Code generated by fries-gen. DO NOT EDIT.

-- +goose Up

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';

CREATE TABLE suppliers (
    id         uuid        PRIMARY KEY,
    tenant_id  uuid        NOT NULL REFERENCES tenants (id),
    name       varchar(100) NOT NULL,
    status     varchar(32) DEFAULT 'active' CHECK (status IN ('active', 'terminated')),
    credit     numeric(18, 2),
    started_at date,
    remark     text,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_by uuid,
    version    integer     NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uk_suppliers_tenant_id ON suppliers (tenant_id, id);
CREATE UNIQUE INDEX uk_suppliers_name ON suppliers (tenant_id, name) WHERE deleted_at IS NULL;
CREATE INDEX idx_suppliers_status ON suppliers (tenant_id, status);
CREATE INDEX idx_suppliers_started_at ON suppliers (tenant_id, started_at);
CREATE INDEX idx_suppliers_name_trgm ON suppliers USING gin (name gin_trgm_ops);

CREATE TRIGGER trg_suppliers_updated_at
    BEFORE UPDATE ON suppliers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- +goose Down
DROP TABLE suppliers;
