// Code generated by cmd/gen tenant-queries. DO NOT EDIT.
//
// 改这个文件是没用的 —— 它由 db/queries/*.sql 经 sqlc 再经 `make gen-tenant-queries` 生成。
// 要加查询就去改 SQL。

package repo

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"

	"github.com/ramoncjs3/fries/internal/repo/internal/sqlcgen"
)

// 类型别名。sqlcgen 是 internal 包，业务代码 import 不到，
// 这里把它的类型原样透出来 —— service 层继续写 repo.User，不用改。
type (
	AuditChainHead                     = sqlcgen.AuditChainHead
	AuditLog                           = sqlcgen.AuditLog
	BumpRateLimitParams                = sqlcgen.BumpRateLimitParams
	ClaimIdempotencyKeyParams          = sqlcgen.ClaimIdempotencyKeyParams
	ClaimPendingRegistrationByTokenRow = sqlcgen.ClaimPendingRegistrationByTokenRow
	CountTenantsForPlatformParams      = sqlcgen.CountTenantsForPlatformParams
	CreatePendingRegistrationParams    = sqlcgen.CreatePendingRegistrationParams
	CreatePlatformAdminParams          = sqlcgen.CreatePlatformAdminParams
	CreatePlatformSessionParams        = sqlcgen.CreatePlatformSessionParams
	CreateServiceAccountRow            = sqlcgen.CreateServiceAccountRow
	CreateTenantParams                 = sqlcgen.CreateTenantParams
	Department                         = sqlcgen.Department
	GetLivePasswordResetTokenRow       = sqlcgen.GetLivePasswordResetTokenRow
	GetLivePlatformSessionRow          = sqlcgen.GetLivePlatformSessionRow
	GetLiveSessionRow                  = sqlcgen.GetLiveSessionRow
	GetRoleRow                         = sqlcgen.GetRoleRow
	GetServiceAccountByPrefixRow       = sqlcgen.GetServiceAccountByPrefixRow
	GetServiceAccountRow               = sqlcgen.GetServiceAccountRow
	GetUserWithDepartmentRow           = sqlcgen.GetUserWithDepartmentRow
	IdempotencyKey                     = sqlcgen.IdempotencyKey
	InsertAuditLogParams               = sqlcgen.InsertAuditLogParams
	ListAuditChainRow                  = sqlcgen.ListAuditChainRow
	ListDepartmentsRow                 = sqlcgen.ListDepartmentsRow
	ListPlatformAuditChainRow          = sqlcgen.ListPlatformAuditChainRow
	ListPlatformSettingsRow            = sqlcgen.ListPlatformSettingsRow
	ListRolePermissionsRow             = sqlcgen.ListRolePermissionsRow
	ListRolePoliciesRow                = sqlcgen.ListRolePoliciesRow
	ListRolesRow                       = sqlcgen.ListRolesRow
	ListServiceAccountRoleBindingsRow  = sqlcgen.ListServiceAccountRoleBindingsRow
	ListServiceAccountsRow             = sqlcgen.ListServiceAccountsRow
	ListSettingsRow                    = sqlcgen.ListSettingsRow
	ListTenantsForPlatformParams       = sqlcgen.ListTenantsForPlatformParams
	ListUserRoleBindingsRow            = sqlcgen.ListUserRoleBindingsRow
	ListUsersNotInDepartmentRow        = sqlcgen.ListUsersNotInDepartmentRow
	ListUsersRow                       = sqlcgen.ListUsersRow
	MarkLoginFailureRow                = sqlcgen.MarkLoginFailureRow
	MarkPlatformLoginFailureParams     = sqlcgen.MarkPlatformLoginFailureParams
	MarkPlatformLoginFailureRow        = sqlcgen.MarkPlatformLoginFailureRow
	PasswordResetToken                 = sqlcgen.PasswordResetToken
	PendingRegistration                = sqlcgen.PendingRegistration
	PlatformAdmin                      = sqlcgen.PlatformAdmin
	PlatformSession                    = sqlcgen.PlatformSession
	PlatformSetting                    = sqlcgen.PlatformSetting
	RateLimit                          = sqlcgen.RateLimit
	RevokeOtherPlatformSessionsParams  = sqlcgen.RevokeOtherPlatformSessionsParams
	Role                               = sqlcgen.Role
	RolePermission                     = sqlcgen.RolePermission
	ServiceAccount                     = sqlcgen.ServiceAccount
	Session                            = sqlcgen.Session
	SetPlatformAdminPasswordParams     = sqlcgen.SetPlatformAdminPasswordParams
	SetTenantStatusParams              = sqlcgen.SetTenantStatusParams
	Setting                            = sqlcgen.Setting
	Supplier                           = sqlcgen.Supplier
	Tenant                             = sqlcgen.Tenant
	UpdateServiceAccountRow            = sqlcgen.UpdateServiceAccountRow
	UpsertPlatformSettingParams        = sqlcgen.UpsertPlatformSettingParams
	User                               = sqlcgen.User
	UserRole                           = sqlcgen.UserRole
)

// ---------------------------------------------------------------- 参数结构体

// 每个 XxxArgs 都是对应 XxxParams **去掉 TenantID** 之后的样子。
// 业务代码看到的参数里压根没有租户这一项，填不了也漏不了。

type AddRolePermissionArgs struct {
	RoleID   uuid.UUID
	Resource string
	Action   string
}

type AssignUserRoleArgs struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

type CountAuditLogsArgs struct {
	ActorID  *uuid.UUID
	Resource *string
	Action   *string
	From     *time.Time
	To       *time.Time
}

type CountRolesArgs struct {
	Keyword *string
	Status  *string
}

type CountServiceAccountsArgs struct {
	Keyword *string
	Status  *string
}

type CountSuppliersArgs struct {
	Keyword   *string
	Status    *string
	StartedAt *time.Time
}

type CountUsersFilteredArgs struct {
	Keyword           *string
	Status            *string
	DepartmentIds     []uuid.UUID
	IncludeUnassigned bool
}

type CreateDepartmentArgs struct {
	ID        uuid.UUID
	ParentID  *uuid.UUID
	Name      string
	Code      string
	SortOrder int32
	Remark    string
	Status    string
	CreatedBy *uuid.UUID
}

type CreateManagedUserArgs struct {
	ID           uuid.UUID
	Username     string
	DisplayName  string
	Email        *string
	Phone        *string
	PasswordHash string
	Status       string
	DepartmentID *uuid.UUID
	CreatedBy    *uuid.UUID
}

type CreatePasswordResetTokenArgs struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

type CreateRoleArgs struct {
	ID          uuid.UUID
	Key         string
	Name        string
	Description string
	DataScope   string
	Status      string
	CreatedBy   *uuid.UUID
}

type CreateServiceAccountArgs struct {
	ID          uuid.UUID
	Name        string
	Description string
	KeyPrefix   string
	KeyHash     []byte
	RoleID      uuid.UUID
	Status      string
	ExpiresAt   *time.Time
	CreatedBy   *uuid.UUID
}

type CreateSessionArgs struct {
	ID        uuid.UUID
	TokenHash []byte
	UserID    uuid.UUID
	IP        *netip.Addr
	UserAgent string
	ExpiresAt time.Time
}

type CreateSupplierArgs struct {
	ID        uuid.UUID
	Name      string
	Status    *string
	Credit    *decimal.Decimal
	StartedAt *time.Time
	Remark    *string
	CreatedBy *uuid.UUID
}

type CreateUserArgs struct {
	ID                 uuid.UUID
	Username           string
	DisplayName        string
	Email              *string
	Phone              *string
	PasswordHash       string
	MustChangePassword bool
	CreatedBy          *uuid.UUID
}

type ListAuditLogsArgs struct {
	ActorID  *uuid.UUID
	Resource *string
	Action   *string
	From     *time.Time
	To       *time.Time
	Offset   int32
	Limit    int32
}

type ListDepartmentsArgs struct {
	Keyword *string
	Status  *string
}

type ListRolesArgs struct {
	Keyword *string
	Status  *string
	Offset  int32
	Limit   int32
}

type ListServiceAccountsArgs struct {
	Keyword *string
	Status  *string
	Offset  int32
	Limit   int32
}

type ListSuppliersArgs struct {
	Keyword   *string
	Status    *string
	StartedAt *time.Time
	Offset    int32
	Limit     int32
}

type ListUsersArgs struct {
	Keyword           *string
	Status            *string
	DepartmentIds     []uuid.UUID
	IncludeUnassigned bool
	Offset            int32
	Limit             int32
}

type ListUsersNotInDepartmentArgs struct {
	DepartmentID *uuid.UUID
	Keyword      *string
	Limit        int32
}

type MarkLoginFailureArgs struct {
	MaxFailures int32
	LockMinutes int32
	ID          uuid.UUID
}

type ResetUserPasswordArgs struct {
	PasswordHash string
	ID           uuid.UUID
}

type RevokeOtherUserSessionsArgs struct {
	UserID        uuid.UUID
	KeepSessionID uuid.UUID
}

type RotateServiceAccountKeyArgs struct {
	KeyPrefix string
	KeyHash   []byte
	ID        uuid.UUID
}

type SetUserPasswordArgs struct {
	PasswordHash string
	ID           uuid.UUID
}

type SetUsersDepartmentArgs struct {
	DepartmentID *uuid.UUID
	UserIds      []uuid.UUID
}

type SoftDeleteDepartmentArgs struct {
	ID      uuid.UUID
	Version int32
}

type SoftDeleteRoleArgs struct {
	ID      uuid.UUID
	Version int32
}

type SoftDeleteServiceAccountArgs struct {
	ID      uuid.UUID
	Version int32
}

type SoftDeleteSupplierArgs struct {
	ID      uuid.UUID
	Version int32
}

type SoftDeleteUserArgs struct {
	ID      uuid.UUID
	Version int32
}

type UpdateDepartmentArgs struct {
	ParentID  *uuid.UUID
	Name      string
	Code      string
	SortOrder int32
	Remark    string
	Status    string
	ID        uuid.UUID
	Version   int32
}

type UpdateManagedUserArgs struct {
	DisplayName  string
	Email        *string
	Phone        *string
	Status       string
	DepartmentID *uuid.UUID
	ID           uuid.UUID
	Version      int32
}

type UpdateRoleArgs struct {
	Name        string
	Description string
	DataScope   string
	Status      string
	ID          uuid.UUID
	Version     int32
}

type UpdateServiceAccountArgs struct {
	Name        string
	Description string
	RoleID      uuid.UUID
	Status      string
	ExpiresAt   *time.Time
	ID          uuid.UUID
	Version     int32
}

type UpdateSupplierArgs struct {
	Name      string
	Status    *string
	Credit    *decimal.Decimal
	StartedAt *time.Time
	Remark    *string
	ID        uuid.UUID
	Version   int32
}

type UpsertSettingArgs struct {
	Key       string
	Value     []byte
	UpdatedBy *uuid.UUID
}

// ---------------------------------------------------------------- 租户绑定的句柄

// TenantQueries 是业务代码唯一能拿到的查询句柄，从 Store.ForTenant / Store.ForContext 取。
//
// 它上面的每个方法都会把租户填进底层 params，调用方看不到也传不了那个字段。
type TenantQueries struct {
	q        *sqlcgen.Queries
	db       TxBeginner
	tenantID uuid.UUID
}

// TenantID 返回这个句柄绑定的租户。
// 只给需要把租户写进别的地方（审计、日志）的场景用，**不要**拿它去手拼查询条件。
func (q *TenantQueries) TenantID() uuid.UUID { return q.tenantID }

func (q *TenantQueries) AddRolePermission(ctx context.Context, arg AddRolePermissionArgs) error {
	return q.q.AddRolePermission(ctx, sqlcgen.AddRolePermissionParams{
		TenantID: q.tenantID,
		RoleID:   arg.RoleID,
		Resource: arg.Resource,
		Action:   arg.Action,
	})
}

func (q *TenantQueries) AssignUserRole(ctx context.Context, arg AssignUserRoleArgs) error {
	return q.q.AssignUserRole(ctx, sqlcgen.AssignUserRoleParams{
		TenantID: q.tenantID,
		UserID:   arg.UserID,
		RoleID:   arg.RoleID,
	})
}

func (q *TenantQueries) ClearRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	return q.q.ClearRolePermissions(ctx, sqlcgen.ClearRolePermissionsParams{TenantID: q.tenantID, RoleID: roleID})
}

func (q *TenantQueries) ClearUserRoles(ctx context.Context, userID uuid.UUID) error {
	return q.q.ClearUserRoles(ctx, sqlcgen.ClearUserRolesParams{TenantID: q.tenantID, UserID: userID})
}

// 还有几个「启用状态 + 拥有通配权限」的人。
// 停用/删除最后一个管理员会把所有人锁在门外，必须拦住。
//
// ⚠️ 这条**必须**按租户数（§3.2 ①）。原来是一条不带租户条件的全表 count，
// 多租户下等于：A 公司还有 admin，B 公司删掉自己最后一个 admin 时检查照样通过 ——
// **B 公司被锁在门外，只能上数据库救。**
func (q *TenantQueries) CountActiveAdmins(ctx context.Context, excludeUserID uuid.UUID) (int64, error) {
	row, err := q.q.CountActiveAdmins(ctx, sqlcgen.CountActiveAdminsParams{TenantID: q.tenantID, ExcludeUserID: excludeUserID})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountAuditLogs(ctx context.Context, arg CountAuditLogsArgs) (int64, error) {
	row, err := q.q.CountAuditLogs(ctx, sqlcgen.CountAuditLogsParams{
		TenantID: q.tenantID,
		ActorID:  arg.ActorID,
		Resource: arg.Resource,
		Action:   arg.Action,
		From:     arg.From,
		To:       arg.To,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountDepartmentChildren(ctx context.Context, parentID *uuid.UUID) (int64, error) {
	row, err := q.q.CountDepartmentChildren(ctx, sqlcgen.CountDepartmentChildrenParams{TenantID: q.tenantID, ParentID: parentID})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountDepartmentUsers(ctx context.Context, departmentID *uuid.UUID) (int64, error) {
	row, err := q.q.CountDepartmentUsers(ctx, sqlcgen.CountDepartmentUsersParams{TenantID: q.tenantID, DepartmentID: departmentID})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountRoleServiceAccounts(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row, err := q.q.CountRoleServiceAccounts(ctx, sqlcgen.CountRoleServiceAccountsParams{TenantID: q.tenantID, RoleID: roleID})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountRoleUsers(ctx context.Context, roleID uuid.UUID) (int64, error) {
	row, err := q.q.CountRoleUsers(ctx, sqlcgen.CountRoleUsersParams{TenantID: q.tenantID, RoleID: roleID})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountRoles(ctx context.Context, arg CountRolesArgs) (int64, error) {
	row, err := q.q.CountRoles(ctx, sqlcgen.CountRolesParams{
		TenantID: q.tenantID,
		Keyword:  arg.Keyword,
		Status:   arg.Status,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountServiceAccounts(ctx context.Context, arg CountServiceAccountsArgs) (int64, error) {
	row, err := q.q.CountServiceAccounts(ctx, sqlcgen.CountServiceAccountsParams{
		TenantID: q.tenantID,
		Keyword:  arg.Keyword,
		Status:   arg.Status,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountSuppliers(ctx context.Context, arg CountSuppliersArgs) (int64, error) {
	row, err := q.q.CountSuppliers(ctx, sqlcgen.CountSuppliersParams{
		TenantID:  q.tenantID,
		Keyword:   arg.Keyword,
		Status:    arg.Status,
		StartedAt: arg.StartedAt,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountUsers(ctx context.Context) (int64, error) {
	row, err := q.q.CountUsers(ctx, q.tenantID)
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CountUsersFiltered(ctx context.Context, arg CountUsersFilteredArgs) (int64, error) {
	row, err := q.q.CountUsersFiltered(ctx, sqlcgen.CountUsersFilteredParams{
		TenantID:          q.tenantID,
		Keyword:           arg.Keyword,
		Status:            arg.Status,
		DepartmentIds:     arg.DepartmentIds,
		IncludeUnassigned: arg.IncludeUnassigned,
	})
	return assertTenant(q.tenantID, row, err)
}

// 开组织时给新组织建它自己的内置 admin 角色（MULTI-TENANCY.md §3.2 ①）。
//
// 和 CreateRole 分开是因为**只有这条能设 builtin = true**：
// 管理页面新建出来的一律是普通角色，内置角色只由「开组织」这条链路建。
// 内置角色不可改不可删，是权限体系的兜底 —— 它被谁随手建出来都不行。
func (q *TenantQueries) CreateBuiltinAdminRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row, err := q.q.CreateBuiltinAdminRole(ctx, sqlcgen.CreateBuiltinAdminRoleParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CreateDepartment(ctx context.Context, arg CreateDepartmentArgs) (Department, error) {
	row, err := q.q.CreateDepartment(ctx, sqlcgen.CreateDepartmentParams{
		TenantID:  q.tenantID,
		ID:        arg.ID,
		ParentID:  arg.ParentID,
		Name:      arg.Name,
		Code:      arg.Code,
		SortOrder: arg.SortOrder,
		Remark:    arg.Remark,
		Status:    arg.Status,
		CreatedBy: arg.CreatedBy,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CreateManagedUser(ctx context.Context, arg CreateManagedUserArgs) (User, error) {
	row, err := q.q.CreateManagedUser(ctx, sqlcgen.CreateManagedUserParams{
		TenantID:     q.tenantID,
		ID:           arg.ID,
		Username:     arg.Username,
		DisplayName:  arg.DisplayName,
		Email:        arg.Email,
		Phone:        arg.Phone,
		PasswordHash: arg.PasswordHash,
		Status:       arg.Status,
		DepartmentID: arg.DepartmentID,
		CreatedBy:    arg.CreatedBy,
	})
	return assertTenant(q.tenantID, row, err)
}

// 忘记密码的一次性 token（MULTI-TENANCY.md §5）。库里只存哈希。
// 租户已知的（申请、改密）走 ForTenant；按 token_hash 校验那一条租户未知，走 Unscoped + 豁免。
// 豁免注释写在 `-- name:` 之后（SplitQueries 按此归属）。
// CreatePasswordResetToken 建一条 token。申请时按公司代码定位了租户，走 ForTenant。
func (q *TenantQueries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenArgs) error {
	return q.q.CreatePasswordResetToken(ctx, sqlcgen.CreatePasswordResetTokenParams{
		TenantID:  q.tenantID,
		ID:        arg.ID,
		UserID:    arg.UserID,
		TokenHash: arg.TokenHash,
		ExpiresAt: arg.ExpiresAt,
	})
}

// builtin 不给传：内置角色只由「开租户」那条链路建（第 ⑤ 步），
// 管理页面新建出来的一律是普通角色。
func (q *TenantQueries) CreateRole(ctx context.Context, arg CreateRoleArgs) (Role, error) {
	row, err := q.q.CreateRole(ctx, sqlcgen.CreateRoleParams{
		TenantID:    q.tenantID,
		ID:          arg.ID,
		Key:         arg.Key,
		Name:        arg.Name,
		Description: arg.Description,
		DataScope:   arg.DataScope,
		Status:      arg.Status,
		CreatedBy:   arg.CreatedBy,
	})
	return assertTenant(q.tenantID, row, err)
}

// 返回的行同样不含 key_hash：明文密钥在应用侧，调用方手里已经有了，
// 不需要也不该从这里再拿一次。
func (q *TenantQueries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountArgs) (CreateServiceAccountRow, error) {
	row, err := q.q.CreateServiceAccount(ctx, sqlcgen.CreateServiceAccountParams{
		TenantID:    q.tenantID,
		ID:          arg.ID,
		Name:        arg.Name,
		Description: arg.Description,
		KeyPrefix:   arg.KeyPrefix,
		KeyHash:     arg.KeyHash,
		RoleID:      arg.RoleID,
		Status:      arg.Status,
		ExpiresAt:   arg.ExpiresAt,
		CreatedBy:   arg.CreatedBy,
	})
	return assertTenant(q.tenantID, row, err)
}

// ---------------------------------------------------------------- 会话
// sessions.tenant_id 看着像冗余（能从 users 推出来），但整套隔离都以「会话里的租户」
// 为唯一来源，所以它必须存在这里。两份真相会不会漂？不会 ——
// 复合外键 (tenant_id, user_id) → users (tenant_id, id) 让数据库保证它们永远一致（§10.2）。
func (q *TenantQueries) CreateSession(ctx context.Context, arg CreateSessionArgs) (Session, error) {
	row, err := q.q.CreateSession(ctx, sqlcgen.CreateSessionParams{
		TenantID:  q.tenantID,
		ID:        arg.ID,
		TokenHash: arg.TokenHash,
		UserID:    arg.UserID,
		IP:        arg.IP,
		UserAgent: arg.UserAgent,
		ExpiresAt: arg.ExpiresAt,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CreateSupplier(ctx context.Context, arg CreateSupplierArgs) (Supplier, error) {
	row, err := q.q.CreateSupplier(ctx, sqlcgen.CreateSupplierParams{
		TenantID:  q.tenantID,
		ID:        arg.ID,
		Name:      arg.Name,
		Status:    arg.Status,
		Credit:    arg.Credit,
		StartedAt: arg.StartedAt,
		Remark:    arg.Remark,
		CreatedBy: arg.CreatedBy,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) CreateUser(ctx context.Context, arg CreateUserArgs) (User, error) {
	row, err := q.q.CreateUser(ctx, sqlcgen.CreateUserParams{
		TenantID:           q.tenantID,
		ID:                 arg.ID,
		Username:           arg.Username,
		DisplayName:        arg.DisplayName,
		Email:              arg.Email,
		Phone:              arg.Phone,
		PasswordHash:       arg.PasswordHash,
		MustChangePassword: arg.MustChangePassword,
		CreatedBy:          arg.CreatedBy,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row, err := q.q.GetDepartment(ctx, sqlcgen.GetDepartmentParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

// 计数和 ListRoles 保持一致 —— 详情页要显示「有多少人在用这个角色」，
// 少一个 user_count 就会显示成「还没有人用」，而列表上明明写着 2 个人。
// 同一个字段两个接口说法不一样，比不显示还糟。
func (q *TenantQueries) GetRole(ctx context.Context, id uuid.UUID) (GetRoleRow, error) {
	row, err := q.q.GetRole(ctx, sqlcgen.GetRoleParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

// ---------------------------------------------------------------- 角色
// 角色 key 现在是**租户内**唯一：每家公司各有一个自己的内置 admin（§3.2 ①）。
func (q *TenantQueries) GetRoleByKey(ctx context.Context, key string) (Role, error) {
	row, err := q.q.GetRoleByKey(ctx, sqlcgen.GetRoleByKeyParams{TenantID: q.tenantID, Key: key})
	return assertTenant(q.tenantID, row, err)
}

// ⚠️ 「按 id 查一行」也带 tenant_id（MULTI-TENANCY.md §11.1）—— id 唯一不代表这一行是你的。
func (q *TenantQueries) GetServiceAccount(ctx context.Context, id uuid.UUID) (GetServiceAccountRow, error) {
	row, err := q.q.GetServiceAccount(ctx, sqlcgen.GetServiceAccountParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row, err := q.q.GetSupplier(ctx, sqlcgen.GetSupplierParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

// ⚠️ 「按 id 查一行」也必须带 tenant_id（§11.1）—— 这是 OWASP API Top 10 第一名的 BOLA。
// id 唯一不代表这一行是你的。
func (q *TenantQueries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row, err := q.q.GetUserByID(ctx, sqlcgen.GetUserByIDParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

// 认证相关查询（DECISIONS.md §3、§6、§8.1）。
//
// ⚠️ 这个文件是整套租户隔离里**最需要小心**的地方（MULTI-TENANCY.md §3.2 ③）：
// 认证发生在租户上下文建立**之前**。验证会话是「拿 cookie 里的 token 去查这是谁」，
// 那一刻还不知道租户是谁；API Key 同理。所以查 sessions / service_accounts 的那几条
// 只能靠代码自觉，标了 `-- tenant-exempt:`。**其余每一条都必须带 tenant_id。**
// ---------------------------------------------------------------- 用户
// 登录标识符：用户名 / 邮箱 / 手机号都行。**租户内**唯一 ——
// 登录时先用公司代码查到租户，再拿租户 + 标识符查人。
// 万一有人的用户名恰好等于另一个人的邮箱，优先按用户名匹配，结果才是确定的。
func (q *TenantQueries) GetUserByIdentifier(ctx context.Context, identifier string) (User, error) {
	row, err := q.q.GetUserByIdentifier(ctx, sqlcgen.GetUserByIdentifierParams{TenantID: q.tenantID, Identifier: identifier})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) GetUserWithDepartment(ctx context.Context, id uuid.UUID) (GetUserWithDepartmentRow, error) {
	row, err := q.q.GetUserWithDepartment(ctx, sqlcgen.GetUserWithDepartmentParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

// InvalidateUserResetTokens 把某人还没用的 token 全标记成已用 —— 申请新的时先作废旧的，
// 保证一个用户同时只有一条有效 token。
func (q *TenantQueries) InvalidateUserResetTokens(ctx context.Context, userID uuid.UUID) error {
	return q.q.InvalidateUserResetTokens(ctx, sqlcgen.InvalidateUserResetTokensParams{TenantID: q.tenantID, UserID: userID})
}

// 按写入顺序取出某个租户的哈希链，用来验完整性。链现在**每租户各一条**（§2.4）。
func (q *TenantQueries) ListAuditChain(ctx context.Context) ([]ListAuditChainRow, error) {
	row, err := q.q.ListAuditChain(ctx, q.tenantID)
	return assertTenant(q.tenantID, row, err)
}

// resource / action 传的是 ILIKE 模式（`%li%`），由 repo.LikePattern 拼 ——
// **别在这里拼 '%' || ... || '%'**，那样用户输入的 % 和 _ 就成了通配符。
//
// tenant_id = ? 是等值条件，NULL 的那批（平台级事件）自然落不进来 —— 这是想要的。
func (q *TenantQueries) ListAuditLogs(ctx context.Context, arg ListAuditLogsArgs) ([]AuditLog, error) {
	row, err := q.q.ListAuditLogs(ctx, sqlcgen.ListAuditLogsParams{
		TenantID: q.tenantID,
		ActorID:  arg.ActorID,
		Resource: arg.Resource,
		Action:   arg.Action,
		From:     arg.From,
		To:       arg.To,
		Offset:   arg.Offset,
		Limit:    arg.Limit,
	})
	return assertTenant(q.tenantID, row, err)
}

// 取一个节点和它所有后代的 id。改父节点时用来挡「把自己挂到自己的子孙下面」——
// 那会造出一个从树上断开的环，整棵树直接查不出来。
//
// ⚠️ **递归那一半也要带 tenant_id**（§10.7）。种子那半带了就完事，是最容易漏的一处：
// 递归部分只靠 parent_id 关联，看着「跟着种子走自然就在租户里」。
// 复合外键确实保证了不会有跨租户的父子关系，所以实际泄不了 —— 但这里要的是**纵深防御**：
// 不依赖另一个约束的正确性。SQL 静态检查也会拦下不带租户条件的那一半。
func (q *TenantQueries) ListDepartmentSubtreeIDs(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	row, err := q.q.ListDepartmentSubtreeIDs(ctx, sqlcgen.ListDepartmentSubtreeIDsParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

// 部门（DECISIONS.md §2）。
// 部门是树，**一次全取**：内部系统撑死几百个节点，分页反而会把树切断。
// 排序保证同一个父下按 sort_order，前端拼树时不用再排一遍。
func (q *TenantQueries) ListDepartments(ctx context.Context, arg ListDepartmentsArgs) ([]ListDepartmentsRow, error) {
	row, err := q.q.ListDepartments(ctx, sqlcgen.ListDepartmentsParams{
		TenantID: q.tenantID,
		Keyword:  arg.Keyword,
		Status:   arg.Status,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) ListRoleIDsOfUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	row, err := q.q.ListRoleIDsOfUser(ctx, sqlcgen.ListRoleIDsOfUserParams{TenantID: q.tenantID, UserID: userID})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]ListRolePermissionsRow, error) {
	row, err := q.q.ListRolePermissions(ctx, sqlcgen.ListRolePermissionsParams{TenantID: q.tenantID, RoleID: roleID})
	return assertTenant(q.tenantID, row, err)
}

// 下面三个查询喂给 Casbin：策略加载进内存，变更靠 LISTEN/NOTIFY 触发重载。
//
// 都带上了 tenant_id —— 加载方按租户逐个加载。Casbin 的 **domain 模型已经落地**：
// 策略和角色绑定都以 tenant_id 作为 domain 写进 enforcer（authz/checker.go 的 Reload），
// 所以两个租户的同名角色 key 不会串。判定侧没有租户（TenantID 为 Nil）一律拒绝。
func (q *TenantQueries) ListRolePolicies(ctx context.Context) ([]ListRolePoliciesRow, error) {
	row, err := q.q.ListRolePolicies(ctx, q.tenantID)
	return assertTenant(q.tenantID, row, err)
}

// 角色管理（DECISIONS.md §3）。
//
// Casbin 用的那几个策略查询在 auth.sql 里，别混在一起：
// 那些是**认证链路**用的（加载进内存），这里是**管理页面**用的。
//
// 角色的 key 现在是**租户内**唯一：每家公司各有一个自己的内置 admin（§3.2 ①）。
// 子查询里的 count 也要带租户 —— 少一处就会把别家公司的人数算进来。
func (q *TenantQueries) ListRoles(ctx context.Context, arg ListRolesArgs) ([]ListRolesRow, error) {
	row, err := q.q.ListRoles(ctx, sqlcgen.ListRolesParams{
		TenantID: q.tenantID,
		Keyword:  arg.Keyword,
		Status:   arg.Status,
		Offset:   arg.Offset,
		Limit:    arg.Limit,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) ListRolesByIDs(ctx context.Context, ids []uuid.UUID) ([]Role, error) {
	row, err := q.q.ListRolesByIDs(ctx, sqlcgen.ListRolesByIDsParams{TenantID: q.tenantID, Ids: ids})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) ListRolesOfUser(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	row, err := q.q.ListRolesOfUser(ctx, sqlcgen.ListRolesOfUserParams{TenantID: q.tenantID, UserID: userID})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) ListServiceAccountRoleBindings(ctx context.Context) ([]ListServiceAccountRoleBindingsRow, error) {
	row, err := q.q.ListServiceAccountRoleBindings(ctx, q.tenantID)
	return assertTenant(q.tenantID, row, err)
}

// Service Account（机器身份）管理（DECISIONS.md §8.1）。
//
// 🔴 **这个文件里的查询一律不返回 `key_hash`。**
// 所以每条都写明列名，不用 `SELECT *` —— 加一列的时候 `*` 会把新列自动带出去，
// 而这张表上「不该出去的列」正是它的核心资产。密钥只在新建和轮换时以明文返回一次，
// 之后库里只有哈希，谁都取不回来。
//
// ⚠️ 认证链路用的那两条（按 prefix 定位、写 last_used_at）在 auth.sql 里，别混：
// 那条按 prefix 查的是**不带租户条件**的（认证发生在租户上下文之前，§3.2 ③），
// 而这里每一条都必须带租户。
func (q *TenantQueries) ListServiceAccounts(ctx context.Context, arg ListServiceAccountsArgs) ([]ListServiceAccountsRow, error) {
	row, err := q.q.ListServiceAccounts(ctx, sqlcgen.ListServiceAccountsParams{
		TenantID: q.tenantID,
		Keyword:  arg.Keyword,
		Status:   arg.Status,
		Offset:   arg.Offset,
		Limit:    arg.Limit,
	})
	return assertTenant(q.tenantID, row, err)
}

// 配置的第二层：可在后台改、改完立即生效（DECISIONS.md §5）。
//
// 多租户之后 settings 是**租户级**的（主键 `(tenant_id, key)`，MULTI-TENANCY.md §7.2）：
// 密码策略、会话超时每家公司自己定。平台级的那些（是否允许自助注册、租户设置的上下界）
// 在 platform_settings 里，不走这里。
func (q *TenantQueries) ListSettings(ctx context.Context) ([]ListSettingsRow, error) {
	row, err := q.q.ListSettings(ctx, q.tenantID)
	return assertTenant(q.tenantID, row, err)
}

// 供应商（supplier）的 CRUD 查询。由 fries-gen 生成。
// Code generated by fries-gen. DO NOT EDIT.
func (q *TenantQueries) ListSuppliers(ctx context.Context, arg ListSuppliersArgs) ([]Supplier, error) {
	row, err := q.q.ListSuppliers(ctx, sqlcgen.ListSuppliersParams{
		TenantID:  q.tenantID,
		Keyword:   arg.Keyword,
		Status:    arg.Status,
		StartedAt: arg.StartedAt,
		Offset:    arg.Offset,
		Limit:     arg.Limit,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) ListUserRoleBindings(ctx context.Context) ([]ListUserRoleBindingsRow, error) {
	row, err := q.q.ListUserRoleBindings(ctx, q.tenantID)
	return assertTenant(q.tenantID, row, err)
}

// 用户管理（DECISIONS.md §3、§6）。
//
// 登录链路用的那几个查询在 auth.sql 里，别混：那些是**认证**用的，
// 这里是**管理页面**用的。
//
// ⚠️ 这个文件里**每一条**都必须带 tenant_id，包括「按 id 改一行」的那些（§11.1）：
// 按 id 更新时最容易觉得「id 是唯一的，够了」—— 不够，那是 BOLA。
// 跨租户测试会拿 A 的上下文去 update/delete B 的 id，影响行数必须是 0（§10.8）。
func (q *TenantQueries) ListUsers(ctx context.Context, arg ListUsersArgs) ([]ListUsersRow, error) {
	row, err := q.q.ListUsers(ctx, sqlcgen.ListUsersParams{
		TenantID:          q.tenantID,
		Keyword:           arg.Keyword,
		Status:            arg.Status,
		DepartmentIds:     arg.DepartmentIds,
		IncludeUnassigned: arg.IncludeUnassigned,
		Offset:            arg.Offset,
		Limit:             arg.Limit,
	})
	return assertTenant(q.tenantID, row, err)
}

// 「添加成员」候选：不在这个部门里的人。department_id 传 NULL 表示「不在任何部门的人」。
func (q *TenantQueries) ListUsersNotInDepartment(ctx context.Context, arg ListUsersNotInDepartmentArgs) ([]ListUsersNotInDepartmentRow, error) {
	row, err := q.q.ListUsersNotInDepartment(ctx, sqlcgen.ListUsersNotInDepartmentParams{
		TenantID:     q.tenantID,
		DepartmentID: arg.DepartmentID,
		Keyword:      arg.Keyword,
		Limit:        arg.Limit,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) MarkLoginFailure(ctx context.Context, arg MarkLoginFailureArgs) (MarkLoginFailureRow, error) {
	row, err := q.q.MarkLoginFailure(ctx, sqlcgen.MarkLoginFailureParams{
		TenantID:    q.tenantID,
		MaxFailures: arg.MaxFailures,
		LockMinutes: arg.LockMinutes,
		ID:          arg.ID,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) MarkLoginSuccess(ctx context.Context, id uuid.UUID) error {
	return q.q.MarkLoginSuccess(ctx, sqlcgen.MarkLoginSuccessParams{TenantID: q.tenantID, ID: id})
}

// MarkPasswordResetTokenUsed **原子认领**一条 token：只有还没被用的才标记成功、返回 1 行。
// 改密前先认领，认领到 0 行说明并发里别人已经用掉了 —— 保证一次性、防 TOCTOU 重用。
func (q *TenantQueries) MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) (int64, error) {
	row, err := q.q.MarkPasswordResetTokenUsed(ctx, sqlcgen.MarkPasswordResetTokenUsedParams{TenantID: q.tenantID, ID: id})
	return assertTenant(q.tenantID, row, err)
}

// 管理员重置密码：**一定要 must_change_password = true** ——
// 临时密码经过了管理员的手，本人必须马上换掉。
func (q *TenantQueries) ResetUserPassword(ctx context.Context, arg ResetUserPasswordArgs) (int64, error) {
	row, err := q.q.ResetUserPassword(ctx, sqlcgen.ResetUserPasswordParams{
		TenantID:     q.tenantID,
		PasswordHash: arg.PasswordHash,
		ID:           arg.ID,
	})
	return assertTenant(q.tenantID, row, err)
}

// 改密码之后用：把这个人的其它会话全踢掉，只留当前这条。
func (q *TenantQueries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsArgs) error {
	return q.q.RevokeOtherUserSessions(ctx, sqlcgen.RevokeOtherUserSessionsParams{
		TenantID:      q.tenantID,
		UserID:        arg.UserID,
		KeepSessionID: arg.KeepSessionID,
	})
}

func (q *TenantQueries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	return q.q.RevokeSession(ctx, sqlcgen.RevokeSessionParams{TenantID: q.tenantID, ID: id})
}

func (q *TenantQueries) RevokeUserSessions(ctx context.Context, userID uuid.UUID) error {
	return q.q.RevokeUserSessions(ctx, sqlcgen.RevokeUserSessionsParams{TenantID: q.tenantID, UserID: userID})
}

// 换一副新密钥，记录本身不动。
//
// 泄露之后要的就是这个：对接方换一串新的继续跑，不用重建记录、不用重配权限。
// 旧密钥当场失效 —— 认证是按 key_prefix 定位的，prefix 一换，旧的那串谁也对不上。
func (q *TenantQueries) RotateServiceAccountKey(ctx context.Context, arg RotateServiceAccountKeyArgs) (int64, error) {
	row, err := q.q.RotateServiceAccountKey(ctx, sqlcgen.RotateServiceAccountKeyParams{
		TenantID:  q.tenantID,
		KeyPrefix: arg.KeyPrefix,
		KeyHash:   arg.KeyHash,
		ID:        arg.ID,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) SetUserPassword(ctx context.Context, arg SetUserPasswordArgs) error {
	return q.q.SetUserPassword(ctx, sqlcgen.SetUserPasswordParams{
		TenantID:     q.tenantID,
		PasswordHash: arg.PasswordHash,
		ID:           arg.ID,
	})
}

// 批量调整部门归属。department_id 传 NULL 就是移出部门。
// **不动 version**：调部门是管理动作，不该让正在编辑这个人的另一个页面撞版本冲突。
//
// ⚠️ 批量按 id 改是 BOLA 的重灾区：不带 tenant_id 的话，传一串别家公司的 user_id
// 就能把人从他们的部门里摘出来。影响行数会如实返回，也就成了一个存在性探针。
func (q *TenantQueries) SetUsersDepartment(ctx context.Context, arg SetUsersDepartmentArgs) (int64, error) {
	row, err := q.q.SetUsersDepartment(ctx, sqlcgen.SetUsersDepartmentParams{
		TenantID:     q.tenantID,
		DepartmentID: arg.DepartmentID,
		UserIds:      arg.UserIds,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) SoftDeleteDepartment(ctx context.Context, arg SoftDeleteDepartmentArgs) (uuid.UUID, error) {
	row, err := q.q.SoftDeleteDepartment(ctx, sqlcgen.SoftDeleteDepartmentParams{
		TenantID: q.tenantID,
		ID:       arg.ID,
		Version:  arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleArgs) (uuid.UUID, error) {
	row, err := q.q.SoftDeleteRole(ctx, sqlcgen.SoftDeleteRoleParams{
		TenantID: q.tenantID,
		ID:       arg.ID,
		Version:  arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) SoftDeleteServiceAccount(ctx context.Context, arg SoftDeleteServiceAccountArgs) (uuid.UUID, error) {
	row, err := q.q.SoftDeleteServiceAccount(ctx, sqlcgen.SoftDeleteServiceAccountParams{
		TenantID: q.tenantID,
		ID:       arg.ID,
		Version:  arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierArgs) (int64, error) {
	row, err := q.q.SoftDeleteSupplier(ctx, sqlcgen.SoftDeleteSupplierParams{
		TenantID: q.tenantID,
		ID:       arg.ID,
		Version:  arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserArgs) (uuid.UUID, error) {
	row, err := q.q.SoftDeleteUser(ctx, sqlcgen.SoftDeleteUserParams{
		TenantID: q.tenantID,
		ID:       arg.ID,
		Version:  arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) TouchServiceAccount(ctx context.Context, id uuid.UUID) error {
	return q.q.TouchServiceAccount(ctx, sqlcgen.TouchServiceAccountParams{TenantID: q.tenantID, ID: id})
}

func (q *TenantQueries) TouchSession(ctx context.Context, id uuid.UUID) error {
	return q.q.TouchSession(ctx, sqlcgen.TouchSessionParams{TenantID: q.tenantID, ID: id})
}

// 乐观锁：影响 0 行说明版本对不上，service 层翻成 common.version_conflict（§2.4）
func (q *TenantQueries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentArgs) (Department, error) {
	row, err := q.q.UpdateDepartment(ctx, sqlcgen.UpdateDepartmentParams{
		TenantID:  q.tenantID,
		ParentID:  arg.ParentID,
		Name:      arg.Name,
		Code:      arg.Code,
		SortOrder: arg.SortOrder,
		Remark:    arg.Remark,
		Status:    arg.Status,
		ID:        arg.ID,
		Version:   arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

// username 不给改：它是登录标识，也是审计里认人的依据。
// 改了之后老审计记录指向的那个人就对不上了。
func (q *TenantQueries) UpdateManagedUser(ctx context.Context, arg UpdateManagedUserArgs) (User, error) {
	row, err := q.q.UpdateManagedUser(ctx, sqlcgen.UpdateManagedUserParams{
		TenantID:     q.tenantID,
		DisplayName:  arg.DisplayName,
		Email:        arg.Email,
		Phone:        arg.Phone,
		Status:       arg.Status,
		DepartmentID: arg.DepartmentID,
		ID:           arg.ID,
		Version:      arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

// key 不给改：它是 Casbin 策略里的标识，改了等于换了一个角色，
// 而已经发出去的会话还带着老 key。要换就新建一个。
func (q *TenantQueries) UpdateRole(ctx context.Context, arg UpdateRoleArgs) (Role, error) {
	row, err := q.q.UpdateRole(ctx, sqlcgen.UpdateRoleParams{
		TenantID:    q.tenantID,
		Name:        arg.Name,
		Description: arg.Description,
		DataScope:   arg.DataScope,
		Status:      arg.Status,
		ID:          arg.ID,
		Version:     arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

// 乐观锁：影响 0 行说明版本对不上，service 层翻成 common.version_conflict。
//
// ⚠️ **key_prefix / key_hash 不在这里改** —— 换密钥是另一个动作、另一个权限点，
// 走 RotateServiceAccountKey。混在一起的话，「改个描述」和「作废对接方手里的凭据」
// 就成了同一个按钮。
func (q *TenantQueries) UpdateServiceAccount(ctx context.Context, arg UpdateServiceAccountArgs) (UpdateServiceAccountRow, error) {
	row, err := q.q.UpdateServiceAccount(ctx, sqlcgen.UpdateServiceAccountParams{
		TenantID:    q.tenantID,
		Name:        arg.Name,
		Description: arg.Description,
		RoleID:      arg.RoleID,
		Status:      arg.Status,
		ExpiresAt:   arg.ExpiresAt,
		ID:          arg.ID,
		Version:     arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) UpdateSupplier(ctx context.Context, arg UpdateSupplierArgs) (Supplier, error) {
	row, err := q.q.UpdateSupplier(ctx, sqlcgen.UpdateSupplierParams{
		TenantID:  q.tenantID,
		Name:      arg.Name,
		Status:    arg.Status,
		Credit:    arg.Credit,
		StartedAt: arg.StartedAt,
		Remark:    arg.Remark,
		ID:        arg.ID,
		Version:   arg.Version,
	})
	return assertTenant(q.tenantID, row, err)
}

func (q *TenantQueries) UpsertSetting(ctx context.Context, arg UpsertSettingArgs) error {
	return q.q.UpsertSetting(ctx, sqlcgen.UpsertSettingParams{
		TenantID:  q.tenantID,
		Key:       arg.Key,
		Value:     arg.Value,
		UpdatedBy: arg.UpdatedBy,
	})
}

// ---------------------------------------------------------------- 不带租户的句柄

// UnscopedQueries 是**不带租户**的查询句柄，从 Store.Unscoped 取。
//
// ⚠️ 这上面的每一条都是绕过租户隔离的。它们不是被遗漏的，是三类确实做不到的：
//
//  1. **认证链路** —— 认证发生在租户上下文建立之前：拿 cookie 里的 token 查这是谁、
//     拿 API Key 的 prefix 查这是哪个机器身份、拿公司代码查这是哪家公司。
//     那一刻还不知道租户是谁，查出来的那一行才告诉我们（§3.2 ③）。
//  2. **写审计** —— 未认证请求也要写审计，那时 tenant_id 就是 NULL（§7.1）。
//  3. **跨租户的后台任务** —— 清理过期会话、建审计分区，本来就不属于任何租户。
//
// 每一条在 SQL 里都写了 `-- tenant-exempt: <理由>`，`gen lint-sql` 会核对。
// **要往这里加东西，先去 MULTI-TENANCY.md §3.2 ③ 那份清单上加，并说明理由。**
type UnscopedQueries struct {
	q  *sqlcgen.Queries
	db TxBeginner
}

// 限流器的持久化存储（SCALING.md §1）。表没有 tenant_id（维度已拼进 key），
// 跨租户 infra 表，走 Unscoped 句柄。豁免注释写在 `-- name:` 之后（SplitQueries 按此归属）。
// BumpRateLimit 原子地把 (key, 当前窗口) 的计数 +1，返回加完之后的值。
// 靠一条 INSERT ... ON CONFLICT DO UPDATE 完成，多副本并发自增不会丢。
// tenant-exempt: rate_limits 是跨租户 infra 表，没有 tenant_id（维度已拼进 key）
func (q *UnscopedQueries) BumpRateLimit(ctx context.Context, arg BumpRateLimitParams) (int32, error) {
	return q.q.BumpRateLimit(ctx, arg)
}

// 幂等键的持久化存储（SCALING.md §1）。表没有 tenant_id（租户已拼进 key），
// 是跨租户的 infra 表 —— 不在 tenantsql 的租户表清单里，查询天然走 Unscoped 句柄。
// 豁免注释一律写在 `-- name:` 之后（SplitQueries 按此归属，写在前面会错位到上一条）。
// ClaimIdempotencyKey 原子地「认领」一个键：能认领（新键、或旧键已过期）返回 1 行，
// 键还有效（重放）返回 0 行。靠 ON CONFLICT ... WHERE 一条语句做完，不用先查后写。
// tenant-exempt: idempotency_keys 是跨租户 infra 表，没有 tenant_id 列（租户已拼进 key 字符串）
func (q *UnscopedQueries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (int64, error) {
	return q.q.ClaimIdempotencyKey(ctx, arg)
}

// ClaimPendingRegistrationByToken 按 token_hash **原子认领**一条还没过期的待验证记录：
// 一条 DELETE ... RETURNING 同时删掉并取回资料。并发里两次验证只有一个能拿到行，
// 另一个 0 行 → 「链接无效或已过期」，天然防重复建租户（TOCTOU）。
// tenant-exempt: 验证时还没有租户，按 token 定位（token_hash 全平台唯一）
func (q *UnscopedQueries) ClaimPendingRegistrationByToken(ctx context.Context, tokenHash []byte) (ClaimPendingRegistrationByTokenRow, error) {
	return q.q.ClaimPendingRegistrationByToken(ctx, tokenHash)
}

// 自助注册的待验证记录（MULTI-TENANCY.md §5）。表没有 tenant_id（还没建租户），
// 跨租户 infra 表，全走 Unscoped 句柄。豁免注释写在 `-- name:` 之后。
// CreatePendingRegistration 存一条待验证注册。
// tenant-exempt: pending_registrations 是「建租户之前」的 infra 表，没有 tenant_id
func (q *UnscopedQueries) CreatePendingRegistration(ctx context.Context, arg CreatePendingRegistrationParams) error {
	return q.q.CreatePendingRegistration(ctx, arg)
}

// 探活用的最小查询：/readyz 靠它确认「连得上库，且库真的在响应」，
// 而不是只看连接池状态。
// tenant-exempt: 探活查询，一张表都不碰
func (q *UnscopedQueries) DatabaseNow(ctx context.Context) (time.Time, error) {
	return q.q.DatabaseNow(ctx)
}

// tenant-exempt: 清理过期会话的后台任务是跨租户的一次扫描，不属于任何租户。
//
//	它只按时间删已经死掉的行，读不到任何租户数据。
func (q *UnscopedQueries) DeleteDeadSessions(ctx context.Context) (int64, error) {
	return q.q.DeleteDeadSessions(ctx)
}

// DeleteExpiredIdempotencyKeys 清过期键，后台任务定时调。
// tenant-exempt: 清过期键的后台任务，跨租户一次扫描
func (q *UnscopedQueries) DeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	return q.q.DeleteExpiredIdempotencyKeys(ctx)
}

// DeleteExpiredPasswordResetTokens 清死掉的 token（过期或已用），后台任务定时调。
// tenant-exempt: 清理任务跨租户一次扫描，只按状态删死掉的行。
func (q *UnscopedQueries) DeleteExpiredPasswordResetTokens(ctx context.Context) (int64, error) {
	return q.q.DeleteExpiredPasswordResetTokens(ctx)
}

// DeleteExpiredPendingRegistrations 清过期记录，后台任务定时调。
// tenant-exempt: 清理任务跨租户一次扫描
func (q *UnscopedQueries) DeleteExpiredPendingRegistrations(ctx context.Context) (int64, error) {
	return q.q.DeleteExpiredPendingRegistrations(ctx)
}

// DeleteOldRateLimits 清掉早于 cutoff 的窗口，后台任务定时调。
// tenant-exempt: 清旧窗口的后台任务，跨租户一次扫描
func (q *UnscopedQueries) DeleteOldRateLimits(ctx context.Context, cutoff time.Time) (int64, error) {
	return q.q.DeleteOldRateLimits(ctx, cutoff)
}

// tenant-exempt: 同上。保留期到了整分区 DROP，保留天数也是平台级配置
func (q *UnscopedQueries) DropOldAuditPartitions(ctx context.Context, cutoff time.Time) (int32, error) {
	return q.q.DropOldAuditPartitions(ctx, cutoff)
}

// tenant-exempt: 建分区是跨租户的后台任务 —— 分区按月切，不按租户切
func (q *UnscopedQueries) EnsureAuditPartition(ctx context.Context, target time.Time) (string, error) {
	return q.q.EnsureAuditPartition(ctx, target)
}

// ForgetIdempotencyKey 释放一个键，让客户端能安全重试。请求失败时调。
// tenant-exempt: 同上，跨租户 infra 表
func (q *UnscopedQueries) ForgetIdempotencyKey(ctx context.Context, key string) error {
	return q.q.ForgetIdempotencyKey(ctx, key)
}

// GetLivePasswordResetToken 按 token_hash 取一条还有效的 token（未用、未过期）。
// tenant-exempt: 校验 token 的那一刻用户还没登录、租户未知 —— 查出来的这行才告诉我们
//
//	tenant_id + user_id（和 GetLiveSession 一个道理，token_hash 全平台唯一）。
func (q *UnscopedQueries) GetLivePasswordResetToken(ctx context.Context, tokenHash []byte) (GetLivePasswordResetTokenRow, error) {
	return q.q.GetLivePasswordResetToken(ctx, tokenHash)
}

// tenant-exempt: 这就是「认证发生在租户上下文之前」的那一刻 —— 拿 cookie 里的 token
//
//	查这是谁，查出来的这一行才告诉我们 tenant_id。所以 uk_sessions_token 也保持
//	全平台唯一，没加 tenant_id（§2.2）。
//	⚠️ 返回的 session.tenant_id 是后续所有隔离的唯一来源，谁都别再从别处推。
//
// 顺带把租户状态一起取出来（§8.2）。**停用一个租户必须立刻生效** ——
// 只挡新登录的话，客户的人拿着已有 cookie 能一直用到过期，而界面上显示「已停用」。
// 在这里查而不是「停用时逐条吊销会话」：这样连绕过应用直接改库的停用也照样生效。
func (q *UnscopedQueries) GetLiveSession(ctx context.Context, tokenHash []byte) (GetLiveSessionRow, error) {
	return q.q.GetLiveSession(ctx, tokenHash)
}

// ---------------------------------------------------------------- Service Account
// tenant-exempt: 和 GetLiveSession 同理 —— 拿 API Key 的 prefix 定位到一行，
//
//	那一行才告诉我们它属于哪个租户。uk_service_accounts_prefix 也保持全平台唯一。
//	租户状态同样要带上：机器身份也不能在停用的租户里继续跑（§8.2）。
func (q *UnscopedQueries) GetServiceAccountByPrefix(ctx context.Context, keyPrefix string) (GetServiceAccountByPrefixRow, error) {
	return q.q.GetServiceAccountByPrefix(ctx, keyPrefix)
}

// 审计日志（DECISIONS.md §6）。只有写入和查询 —— 改和删在 DB 层就被禁了。
//
// ⚠️ audit_logs 的 tenant_id **可空**（MULTI-TENANCY.md §7.1）：未认证请求
// （登录失败、健康检查、直接打接口）也要写审计，那些记录没有租户。
// NULL = 平台级 / 无租户事件，只有平台端看得到。
// 细节：公司代码有效、密码错误的登录失败要记在**那个租户名下**，客户才能看到
// 「有人在爆破我们的账号」；只有公司代码本身无效时才记 NULL。
// tenant-exempt: 写审计的中间件不是租户绑定的 —— 未认证请求也要写，那时 tenant_id 是 NULL。
//
//	列里带着 tenant_id，租户归属由调用方显式传，不靠 ForTenant 注入。
//
// prev_hash / hash 由触发器算，应用不传：应用能算就意味着应用能伪造。
func (q *UnscopedQueries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	return q.q.InsertAuditLog(ctx, arg)
}

// InvalidatePendingRegistrationsByEmail 删掉同一邮箱之前没验证的记录 —— 重发验证信时先清旧的。
// tenant-exempt: 同上，跨租户 infra 表
func (q *UnscopedQueries) InvalidatePendingRegistrationsByEmail(ctx context.Context, email string) error {
	return q.q.InvalidatePendingRegistrationsByEmail(ctx, email)
}

// tenant-exempt: 平台级事件（未认证请求）的那条链，tenant_id 就是 NULL ——
//
//	它不属于任何租户，按定义就带不了租户条件。只有平台管理端查得到。
//
// 单独一条查询而不是在 ListAuditChain 里 coalesce：
//  1. 那样 ListAuditChain 用不上 (tenant_id, occurred_at) 索引
//  2. 更要紧的是，coalesce 版本要传全零哨兵 UUID 才能取到平台链，
//     而 ForTenant 现在拒绝零值租户（零值只该来自 bug）。两件事分开各走各的路。
func (q *UnscopedQueries) ListPlatformAuditChain(ctx context.Context) ([]ListPlatformAuditChainRow, error) {
	return q.q.ListPlatformAuditChain(ctx)
}

// ---------------------------------------------------------------- 平台级句柄

// PlatformQueries 是**平台管理端**的查询句柄，从 Store.Platform() 取。
//
// 它上面只有「引用的表全是平台级表」的查询 —— tenants / platform_admins /
// platform_sessions / platform_settings 这四张。分流是生成器按 SQL 里的表名做的，
// 不是靠人分类：哪天有人在 platform.sql 里写一条去查业务表（users、departments……）
// 的查询，那条查询会掉到别的句柄上，平台服务当场编译不过。
//
// 为什么这么在意（MULTI-TENANCY.md §6、§10.11）：平台管理员开租户、停租户，
// 但**结构上碰不到客户的业务数据**。这个性质是将来跟客户解释隔离时最有力的一句话，
// 而它只有在「代码里根本没有那条路」时才成立 —— 写在文档里的版本不算数。
//
// 「租户列表要显示人数」就是靠 tenants.user_count 冗余绕开的，不是去关联业务表。
type PlatformQueries struct {
	q  *sqlcgen.Queries
	db TxBeginner
}

// ---------------------------------------------------------------- 平台管理员
// tenant-exempt: platform_admins 是平台级表，平台管理员不属于任何租户（§2.3）
func (q *PlatformQueries) CountPlatformAdmins(ctx context.Context) (int64, error) {
	return q.q.CountPlatformAdmins(ctx)
}

// tenant-exempt: 同上
func (q *PlatformQueries) CountTenantsForPlatform(ctx context.Context, arg CountTenantsForPlatformParams) (int64, error) {
	return q.q.CountTenantsForPlatform(ctx, arg)
}

// tenant-exempt: 同上
func (q *PlatformQueries) CreatePlatformAdmin(ctx context.Context, arg CreatePlatformAdminParams) (PlatformAdmin, error) {
	return q.q.CreatePlatformAdmin(ctx, arg)
}

// ---------------------------------------------------------------- 平台会话
// tenant-exempt: 平台会话不属于任何租户（§10.1）
func (q *PlatformQueries) CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error) {
	return q.q.CreatePlatformSession(ctx, arg)
}

// tenant-exempt: 同上
func (q *PlatformQueries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	return q.q.CreateTenant(ctx, arg)
}

// tenant-exempt: 清理任务，只按时间删已经死掉的行
func (q *PlatformQueries) DeleteDeadPlatformSessions(ctx context.Context) (int64, error) {
	return q.q.DeleteDeadPlatformSessions(ctx)
}

// tenant-exempt: 和租户那边的 GetLiveSession 同理 —— 拿 token 查这是谁
func (q *PlatformQueries) GetLivePlatformSession(ctx context.Context, tokenHash []byte) (GetLivePlatformSessionRow, error) {
	return q.q.GetLivePlatformSession(ctx, tokenHash)
}

// tenant-exempt: 同上
func (q *PlatformQueries) GetPlatformAdminByID(ctx context.Context, id uuid.UUID) (PlatformAdmin, error) {
	return q.q.GetPlatformAdminByID(ctx, id)
}

// tenant-exempt: 同上。平台登录只按用户名 —— 没有公司代码这一层
func (q *PlatformQueries) GetPlatformAdminByUsername(ctx context.Context, username string) (PlatformAdmin, error) {
	return q.q.GetPlatformAdminByUsername(ctx, username)
}

// 租户本身（MULTI-TENANCY.md §2.1）。
//
// ⚠️ `tenants` 是**平台级**的表，它自己没有 tenant_id ——
// 和 sessions / service_accounts 一样属于「只能靠代码自觉」的那三张（§3.2 ③）。
// 原因是认证发生在租户上下文建立**之前**：登录时先拿公司代码来这张表找租户，
// 那一刻还不知道租户是谁。**清单就这三张，加第四张要单独讨论。**
//
// 所以这里每一条都要写 `-- tenant-exempt:`，让 SQL 静态检查放行并留下理由。
//
// 平台管理端自己的租户查询在 platform.sql 里。这里放的是**认证链路和启动加载**
// 要用的那几条 —— 它们不属于平台端，但同样只碰 tenants 这一张平台级表。
// tenant-exempt: tenants 是平台级表，登录按公司代码找租户时还没有租户上下文
// code 存的一律是小写（DB 有 CHECK 保证），查询侧 lower() 是为了用上 uk_tenants_code
// 这个函数索引 —— 用户在登录框里敲 ACME 也要认得出来。
func (q *PlatformQueries) GetTenantByCode(ctx context.Context, code string) (Tenant, error) {
	return q.q.GetTenantByCode(ctx, code)
}

// tenant-exempt: 同上
func (q *PlatformQueries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	return q.q.GetTenantByID(ctx, id)
}

// 平台管理端（MULTI-TENANCY.md §6、第 ⑤ 步）+ 平台级配置（§7.2）。
//
// ⚠️ **这个文件里的查询只许碰四张平台级表**：
// `tenants` / `platform_admins` / `platform_sessions` / `platform_settings`。
//
// 这不是口头约定：生成器按「引用的表全在平台级清单里」把它们分流到
// `Store.Platform()` 那个句柄上，平台服务**结构上就够不到业务表**。
// 哪天有人在这里写一条 `SELECT ... FROM users`，这条查询会掉到别的句柄上，
// 平台服务编译不过。
//
// 为什么这么在意：一旦平台端能查 users，「平台端结构上碰不到客户业务数据」
// 这个性质就没了 —— 而那句话是将来跟客户解释隔离时最有力的一句（§10.11）。
// 「租户列表要显示人数」这个需求就是靠 tenants.user_count 冗余绕开的，不是靠 join。
// ---------------------------------------------------------------- 平台级配置
// tenant-exempt: platform_settings 是平台级表，没有 tenant_id 这一列
func (q *PlatformQueries) ListPlatformSettings(ctx context.Context) ([]ListPlatformSettingsRow, error) {
	return q.q.ListPlatformSettings(ctx)
}

// tenant-exempt: 同上。加载权限策略、加载各租户配置都要遍历租户
//
// ⚠️ **不要按 status 过滤。** 这里曾经写的是 `WHERE status = 'active'`，
// 结果是：停用一个租户 → 下次刷新策略时它的权限从 enforcer 里消失 →
// 重新启用之后**没有任何东西会触发重载**（authz_changed 只在角色相关的表上有触发器），
// 那家公司的人能登录但**每个请求都 403**，只能重启服务或者随便改个角色才恢复。
//
// 停用的租户根本认证不过去（认证时会核 tenants.status），
// 所以把它们的策略留在内存里没有任何风险，反而省掉一整类「状态没跟上」的问题。
func (q *PlatformQueries) ListTenants(ctx context.Context) ([]Tenant, error) {
	return q.q.ListTenants(ctx)
}

// ---------------------------------------------------------------- 租户
// tenant-exempt: tenants 是平台级表。这是平台端的租户列表 ——
//
//	人数走 tenants.user_count 冗余列，**不 join users**（§6）
func (q *PlatformQueries) ListTenantsForPlatform(ctx context.Context, arg ListTenantsForPlatformParams) ([]Tenant, error) {
	return q.q.ListTenantsForPlatform(ctx, arg)
}

// tenant-exempt: 同上
func (q *PlatformQueries) MarkPlatformLoginFailure(ctx context.Context, arg MarkPlatformLoginFailureParams) (MarkPlatformLoginFailureRow, error) {
	return q.q.MarkPlatformLoginFailure(ctx, arg)
}

// tenant-exempt: 同上
func (q *PlatformQueries) MarkPlatformLoginSuccess(ctx context.Context, id uuid.UUID) error {
	return q.q.MarkPlatformLoginSuccess(ctx, id)
}

// tenant-exempt: 同上。改密码之后把其它会话全踢掉，只留当前这条
func (q *PlatformQueries) RevokeOtherPlatformSessions(ctx context.Context, arg RevokeOtherPlatformSessionsParams) error {
	return q.q.RevokeOtherPlatformSessions(ctx, arg)
}

// tenant-exempt: 同上
func (q *PlatformQueries) RevokePlatformSession(ctx context.Context, id uuid.UUID) error {
	return q.q.RevokePlatformSession(ctx, id)
}

// tenant-exempt: 同上
func (q *PlatformQueries) SetPlatformAdminPassword(ctx context.Context, arg SetPlatformAdminPasswordParams) error {
	return q.q.SetPlatformAdminPassword(ctx, arg)
}

// tenant-exempt: 同上。租户只停用不删除（§9.3）—— 没有删除语句是有意的
func (q *PlatformQueries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error) {
	return q.q.SetTenantStatus(ctx, arg)
}

// tenant-exempt: 同上
func (q *PlatformQueries) TouchPlatformSession(ctx context.Context, id uuid.UUID) error {
	return q.q.TouchPlatformSession(ctx, id)
}

// tenant-exempt: 同上
func (q *PlatformQueries) UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) error {
	return q.q.UpsertPlatformSetting(ctx, arg)
}

// ---------------------------------------------------------------- 运行期兜底的豁免清单

// exemptQueries 是 SQL 里写了 `-- tenant-exempt: <理由>` 的查询名。
//
// 运行期的 tracer 拿 SQL 里的查询名来这里对（trace.go）。理由不在这里 ——
// 理由写在 db/queries/*.sql 那一行上，`make lint-sql` 每次都会打出来。
var exemptQueries = map[string]bool{
	"BumpRateLimit":                         true,
	"ClaimIdempotencyKey":                   true,
	"ClaimPendingRegistrationByToken":       true,
	"CountPlatformAdmins":                   true,
	"CountTenantsForPlatform":               true,
	"CreatePendingRegistration":             true,
	"CreatePlatformAdmin":                   true,
	"CreatePlatformSession":                 true,
	"CreateTenant":                          true,
	"DatabaseNow":                           true,
	"DeleteDeadPlatformSessions":            true,
	"DeleteDeadSessions":                    true,
	"DeleteExpiredIdempotencyKeys":          true,
	"DeleteExpiredPasswordResetTokens":      true,
	"DeleteExpiredPendingRegistrations":     true,
	"DeleteOldRateLimits":                   true,
	"DropOldAuditPartitions":                true,
	"EnsureAuditPartition":                  true,
	"ForgetIdempotencyKey":                  true,
	"GetLivePasswordResetToken":             true,
	"GetLivePlatformSession":                true,
	"GetLiveSession":                        true,
	"GetPlatformAdminByID":                  true,
	"GetPlatformAdminByUsername":            true,
	"GetServiceAccountByPrefix":             true,
	"GetTenantByCode":                       true,
	"GetTenantByID":                         true,
	"InsertAuditLog":                        true,
	"InvalidatePendingRegistrationsByEmail": true,
	"ListPlatformAuditChain":                true,
	"ListPlatformSettings":                  true,
	"ListTenants":                           true,
	"ListTenantsForPlatform":                true,
	"MarkPlatformLoginFailure":              true,
	"MarkPlatformLoginSuccess":              true,
	"RevokeOtherPlatformSessions":           true,
	"RevokePlatformSession":                 true,
	"SetPlatformAdminPassword":              true,
	"SetTenantStatus":                       true,
	"TouchPlatformSession":                  true,
	"UpsertPlatformSetting":                 true,
}
